[package]
name = "sdk_bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
# cbindgen = "0.27.0"
game = { path = "../game" }
platform = { path = "../platform" }


[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[build-dependencies]
cc = "1.0.79"
bindgen = "0.64.0"
csbindgen = "1.2.0"
