// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
// Schema version: 0.0.837 x-release-please-version

#ifndef GOUD_CPP_SDK_GENERATED_HPP
#define GOUD_CPP_SDK_GENERATED_HPP

/** @file goud.g.hpp
 *  @brief Auto-generated C++17 RAII wrapper for GoudEngine.
 *
 *  Provides move-only wrappers around the C SDK handles.
 *  Most methods are noexcept and return integer status codes (0 = success).
 *  Methods that allocate (Error::last, createUnique, createShared) may throw.
 */

#include <goud/goud.h>

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace goud {

/** @brief Coordinate origin for draw calls. Controls how (x, y) position is interpreted in DrawQuad and DrawSprite. */
enum class CoordinateOrigin : std::uint32_t {
    Center = 0,
    TopLeft = 1,
};

/** @brief Keyboard key codes matching GLFW values */
enum class Key : std::int32_t {
    Unknown = -1,
    Space = 32,
    Apostrophe = 39,
    Comma = 44,
    Minus = 45,
    Period = 46,
    Slash = 47,
    Digit0 = 48,
    Digit1 = 49,
    Digit2 = 50,
    Digit3 = 51,
    Digit4 = 52,
    Digit5 = 53,
    Digit6 = 54,
    Digit7 = 55,
    Digit8 = 56,
    Digit9 = 57,
    Semicolon = 59,
    Equal = 61,
    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,
    LeftBracket = 91,
    Backslash = 92,
    RightBracket = 93,
    GraveAccent = 96,
    Escape = 256,
    Enter = 257,
    Tab = 258,
    Backspace = 259,
    Insert = 260,
    Delete = 261,
    Right = 262,
    Left = 263,
    Down = 264,
    Up = 265,
    PageUp = 266,
    PageDown = 267,
    Home = 268,
    End = 269,
    CapsLock = 280,
    ScrollLock = 281,
    NumLock = 282,
    PrintScreen = 283,
    Pause = 284,
    F1 = 290,
    F2 = 291,
    F3 = 292,
    F4 = 293,
    F5 = 294,
    F6 = 295,
    F7 = 296,
    F8 = 297,
    F9 = 298,
    F10 = 299,
    F11 = 300,
    F12 = 301,
    Numpad0 = 320,
    Numpad1 = 321,
    Numpad2 = 322,
    Numpad3 = 323,
    Numpad4 = 324,
    Numpad5 = 325,
    Numpad6 = 326,
    Numpad7 = 327,
    Numpad8 = 328,
    Numpad9 = 329,
    NumpadDecimal = 330,
    NumpadDivide = 331,
    NumpadMultiply = 332,
    NumpadSubtract = 333,
    NumpadAdd = 334,
    NumpadEnter = 335,
    LeftShift = 340,
    LeftControl = 341,
    LeftAlt = 342,
    LeftSuper = 343,
    RightShift = 344,
    RightControl = 345,
    RightAlt = 346,
    RightSuper = 347,
};

/** @brief Mouse button identifiers */
enum class MouseButton : std::int32_t {
    Left = 0,
    Right = 1,
    Middle = 2,
    Button4 = 3,
    Button5 = 4,
    Button6 = 5,
    Button7 = 6,
    Button8 = 7,
};

/** @brief Screen corner where the debug overlay is displayed */
enum class OverlayCorner : std::int32_t {
    TopLeft = 0,
    TopRight = 1,
    BottomLeft = 2,
    BottomRight = 3,
};

/** @brief Step unit used by the debugger control plane. */
enum class DebuggerStepKind : std::int32_t {
    Frame = 0,
    Tick = 1,
};

/** @brief Animation playback mode */
enum class PlaybackMode : std::int32_t {
    Loop = 0,
    OneShot = 1,
};

/** @brief Type of rigid body */
enum class BodyType : std::int32_t {
    Dynamic = 0,
    Static = 1,
    Kinematic = 2,
};

/** @brief Collider shape type */
enum class ShapeType : std::int32_t {
    Box = 0,
    Circle = 1,
};

/** @brief 2D physics backend selection */
enum class PhysicsBackend2D : std::uint32_t {
    Default = 0,
    Rapier = 1,
    Simple = 2,
};

/** @brief Native render backend selection */
enum class RenderBackendKind : std::uint32_t {
    Wgpu = 0,
    OpenGlLegacy = 1,
};

/** @brief Native window backend selection */
enum class WindowBackendKind : std::uint32_t {
    Winit = 0,
    GlfwLegacy = 1,
};

/** @brief Easing function for tweens */
enum class EasingType : std::int32_t {
    Linear = 0,
    EaseInQuad = 1,
    EaseOutQuad = 2,
    EaseInOutQuad = 3,
};

/** @brief Network transport protocol */
enum class NetworkProtocol : std::int32_t {
    UDP = 0,
    WebSocket = 1,
    Tcp = 2,
};

/** @brief Scene transition type */
enum class TransitionType : std::uint8_t {
    Instant = 0,
    Fade = 1,
    Custom = 2,
};

/** @brief Horizontal text alignment */
enum class TextAlignment : std::uint8_t {
    Left = 0,
    Center = 1,
    Right = 2,
};

/** @brief Text flow direction */
enum class TextDirection : std::uint8_t {
    Auto = 0,
    Ltr = 1,
    Rtl = 2,
};

/** @brief How an animation layer blends with layers below it */
enum class BlendMode : std::int32_t {
    Override = 0,
    Additive = 1,
};

/** @brief Discriminant for animation event payload data */
enum class EventPayloadType : std::int32_t {
    None = 0,
    Int = 1,
    Float = 2,
    String = 3,
};

/** @brief Direction constraint for an RPC handler */
enum class RpcDirection : std::int32_t {
    ServerToClient = 0,
    ClientToServer = 1,
    Bidirectional = 2,
};

/** @brief Snapshot of the last engine error.
 *
 *  Retrieve the most recent error with Error::last().  An Error is falsy
 *  when no error has occurred (code == SUCCESS).
 */
class Error {
public:
    /** @brief Construct an empty (no-error) instance. */
    Error() noexcept = default;

    /** @brief Capture the last error from the engine thread-local state.
     *  @return An Error populated with code, message, subsystem, and operation.
     */
    static Error last() {
        ::goud_error_info info;
        ::goud_get_last_error(&info);
        return Error(info);
    }

    /** @brief True when an error is present (code != SUCCESS). */
    explicit operator bool() const noexcept {
        return code_ != SUCCESS;
    }

    /** @brief Numeric error code. */
    ::GoudErrorCode code() const noexcept {
        return code_;
    }

    /** @brief Recovery class hint (0 = unrecoverable). */
    int recoveryClass() const noexcept {
        return recovery_class_;
    }

    /** @brief Human-readable error description. */
    const std::string &message() const noexcept {
        return message_;
    }

    /** @brief Engine subsystem that raised the error. */
    const std::string &subsystem() const noexcept {
        return subsystem_;
    }

    /** @brief Operation that failed. */
    const std::string &operation() const noexcept {
        return operation_;
    }

private:
    explicit Error(const ::goud_error_info &info)
        : code_(info.code),
          recovery_class_(info.recovery_class),
          message_(info.message),
          subsystem_(info.subsystem),
          operation_(info.operation) {}

    ::GoudErrorCode code_ = SUCCESS;
    int recovery_class_ = 0;
    std::string message_;
    std::string subsystem_;
    std::string operation_;
};

/** @brief RAII wrapper for an engine configuration handle.
 *
 *  Move-only.  The underlying handle is freed on destruction.  Use create()
 *  for stack allocation or createUnique() for heap allocation.
 */
class EngineConfig {
public:
    /** @brief Construct an empty (invalid) config. */
    EngineConfig() noexcept = default;

    /** @brief Destroy the config, releasing the underlying handle. */
    ~EngineConfig() noexcept {
        reset();
    }

    EngineConfig(const EngineConfig &) = delete;
    EngineConfig &operator=(const EngineConfig &) = delete;

    /** @brief Move-construct from another config. */
    EngineConfig(EngineConfig &&other) noexcept
        : handle_(other.release()) {}

    /** @brief Move-assign from another config. */
    EngineConfig &operator=(EngineConfig &&other) noexcept {
        if (this != &other) {
            reset();
            handle_ = other.release();
        }
        return *this;
    }

    /** @brief Allocate a new engine configuration on the stack.
     *  @param[out] out_status  Optional pointer to receive the status code.
     *  @return A valid EngineConfig on success.
     */
    static EngineConfig create(int *out_status = nullptr) noexcept {
        EngineConfig config;
        int status = config.init();
        if (out_status != nullptr) {
            *out_status = status;
        }
        return config;
    }

    /** @brief Allocate a new engine configuration on the heap.
     *  @param[out] out_status  Optional pointer to receive the status code.
     *  @return A unique_ptr owning the config.
     */
    static std::unique_ptr<EngineConfig> createUnique(int *out_status = nullptr) {
        auto config = std::unique_ptr<EngineConfig>(new EngineConfig());
        int status = config->init();
        if (out_status != nullptr) {
            *out_status = status;
        }
        return config;
    }

    /** @brief Initialize the underlying config handle.
     *  @return SUCCESS if the handle was created or was already valid.
     */
    int init() noexcept {
        if (valid()) {
            return SUCCESS;
        }
        return ::goud_engine_config_init(&handle_);
    }

    /** @brief Check whether the config handle is valid.
     *  @return true when the handle is non-NULL.
     */
    bool valid() const noexcept {
        return ::goud_engine_config_valid(handle_);
    }

    /** @brief Set the window title. */
    int setTitle(const char * title) noexcept {
        return ::goud_engine_config_set_title_utf8(handle_, title);
    }

    /** @brief Set the window dimensions. */
    int setSize(std::uint32_t width, std::uint32_t height) noexcept {
        return ::goud_engine_config_set_window_size(handle_, width, height);
    }

    /** @brief Enable or disable vertical sync. */
    int setVsync(bool enabled) noexcept {
        return ::goud_engine_config_set_vsync_enabled(handle_, enabled);
    }

    /** @brief Enable or disable fullscreen mode. */
    int setFullscreen(bool enabled) noexcept {
        return ::goud_engine_config_set_fullscreen_enabled(handle_, enabled);
    }

    /** @brief Set the target frames per second. */
    int setTargetFps(std::uint32_t fps) noexcept {
        return ::goud_engine_config_set_target_fps_value(handle_, fps);
    }

    /** @brief Enable or disable the FPS debug overlay. */
    int setFpsOverlay(bool enabled) noexcept {
        return ::goud_engine_config_set_fps_overlay_enabled(handle_, enabled);
    }

    /** @brief Enable or disable physics debug rendering. */
    int setPhysicsDebug(bool enabled) noexcept {
        return ::goud_engine_config_set_physics_debug_enabled(handle_, enabled);
    }

    /** @brief Select the 2D physics backend. */
    int setPhysicsBackend2d(std::uint32_t backend) noexcept {
        return ::goud_engine_config_set_physics_backend_2d_value(handle_, backend);
    }

    /** @brief Select the rendering backend. */
    int setRenderBackend(std::uint32_t backend) noexcept {
        return ::goud_engine_config_set_render_backend_value(handle_, backend);
    }

    /** @brief Select the window backend. */
    int setWindowBackend(std::uint32_t backend) noexcept {
        return ::goud_engine_config_set_window_backend_value(handle_, backend);
    }

    /** @brief Access the raw FFI config handle.
     *  @return The underlying handle (may be NULL).
     */
    ::goud_engine_config raw() const noexcept {
        return handle_;
    }

    /** @brief Release ownership of the raw handle.
     *  @return The underlying handle.  The config is left in an invalid state.
     */
    ::goud_engine_config release() noexcept {
        ::goud_engine_config handle = handle_;
        handle_ = nullptr;
        return handle;
    }

    /** @brief Destroy the underlying handle and reset to invalid. */
    void reset() noexcept {
        if (handle_ != nullptr) {
            (void)::goud_engine_config_dispose(&handle_);
        }
    }

private:
    ::goud_engine_config handle_ = nullptr;
};

/** @brief RAII wrapper for an engine context.
 *
 *  Move-only.  Provides methods for ECS, assets, rendering, input, and
 *  window management.  The context is destroyed on destruction.
 */
class Context {
public:
    /** @brief Construct an invalid context. */
    Context() noexcept
        : handle_(::goud_context_invalid()) {}

    /** @brief Construct from a raw FFI context handle.
     *  @param handle  Raw context handle.
     */
    explicit Context(::goud_context handle) noexcept
        : handle_(handle) {}

    /** @brief Destroy the context. */
    ~Context() noexcept {
        reset();
    }

    Context(const Context &) = delete;
    Context &operator=(const Context &) = delete;

    /** @brief Move-construct from another context. */
    Context(Context &&other) noexcept
        : handle_(other.release()) {}

    /** @brief Move-assign from another context. */
    Context &operator=(Context &&other) noexcept {
        if (this != &other) {
            reset();
            handle_ = other.release();
        }
        return *this;
    }

    /** @brief Create a standalone context (without an engine).
     *  @param[out] out_status  Optional pointer to receive the status code.
     *  @return A valid Context on success.
     */
    static Context create(int *out_status = nullptr) noexcept {
        Context context;
        int status = ::goud_context_init(&context.handle_);
        if (out_status != nullptr) {
            *out_status = status;
        }
        return context;
    }

    /** @brief Create a shared-ownership context.
     *  @param[out] out_status  Optional pointer to receive the status code.
     *  @return A shared_ptr owning the context.
     */
    static std::shared_ptr<Context> createShared(int *out_status = nullptr) {
        auto context = std::make_shared<Context>();
        int status = ::goud_context_init(&context->handle_);
        if (out_status != nullptr) {
            *out_status = status;
        }
        return context;
    }

    /** @brief Check whether the context handle is valid.
     *  @return true when the context is not the invalid sentinel.
     */
    bool valid() const noexcept {
        return ::goud_context_valid(handle_);
    }

    /** @brief Access the raw FFI context handle.
     *  @return The underlying handle.
     */
    ::goud_context raw() const noexcept {
        return handle_;
    }

    /** @brief Destroy the underlying context and reset to invalid.
     *  @return SUCCESS on success.
     */
    int reset() noexcept {
        return ::goud_context_dispose(&handle_);
    }

    /** @brief Release ownership of the raw handle.
     *  @return The underlying handle.  The context is left invalid.
     */
    ::goud_context release() noexcept {
        ::goud_context handle = handle_;
        handle_ = ::goud_context_invalid();
        return handle;
    }

    /** @brief Returns true if the window close has been requested */
    bool shouldClose() const noexcept {
        return ::goud_window_should_close_checked(handle_);
    }

    /** @brief Starts a new render frame with the given clear color */
    int beginFrame() const noexcept {
        return ::goud_renderer_begin_frame(handle_);
    }

    /** @brief Finishes the current frame and presents it to the screen */
    int endFrame() const noexcept {
        return ::goud_renderer_end_frame(handle_);
    }

    /** @brief Loads a texture from a file path and returns its handle */
    int loadTexture(const char * path, ::goud_texture & out_texture) const noexcept {
        return ::goud_texture_load_path(handle_, path, &out_texture);
    }

    /** @brief Destroys a previously loaded texture */
    int destroyTexture(::goud_texture texture) const noexcept {
        return ::goud_texture_dispose(handle_, texture);
    }

    /** @brief Loads a font from a file path and returns its handle */
    int loadFont(const char * path, ::goud_font & out_font) const noexcept {
        return ::goud_font_load_path(handle_, path, &out_font);
    }

    /** @brief Destroys a previously loaded font */
    int destroyFont(::goud_font font) const noexcept {
        return ::goud_font_dispose(handle_, font);
    }

    /** @brief Draws a textured sprite. Position (x,y) interpretation depends on the coordinate origin setting (center by default). */
    int drawSprite(::goud_texture texture, float x, float y, float width, float height, float rotation, ::goud_color color) const noexcept {
        return ::goud_renderer_draw_sprite_color(handle_, texture, x, y, width, height, rotation, color);
    }

    /** @brief Draws a colored rectangle */
    int drawQuad(float x, float y, float width, float height, ::goud_color color) const noexcept {
        return ::goud_renderer_draw_quad_color(handle_, x, y, width, height, color);
    }

    /** @brief Returns true if the key is currently held down */
    bool keyDown(::goud_key key) const noexcept {
        return ::goud_input_key_down(handle_, key);
    }

    /** @brief Returns true if the key was pressed this frame */
    bool keyJustPressed(::goud_key key) const noexcept {
        return ::goud_input_key_pressed_once(handle_, key);
    }

    /** @brief Returns true if the mouse button is currently held */
    bool mouseDown(::goud_mouse_button button) const noexcept {
        return ::goud_input_mouse_down(handle_, button);
    }

    /** @brief Returns the mouse position relative to the window */
    int mousePosition(::goud_vec2 & out_position) const noexcept {
        return ::goud_input_mouse_position(handle_, &out_position);
    }

    /** @brief Returns the scroll wheel delta this frame */
    int scrollDelta(::goud_vec2 & out_delta) const noexcept {
        return ::goud_input_scroll_delta(handle_, &out_delta);
    }

    /** @brief Creates a new empty entity */
    int spawnEntity(std::uint64_t & out_entity) const noexcept {
        return ::goud_entity_spawn(handle_, &out_entity);
    }

    /** @brief Destroys an entity and all its components */
    int destroyEntity(std::uint64_t entity) const noexcept {
        return ::goud_entity_remove(handle_, entity);
    }

    /** @brief Returns true if the entity still exists */
    bool isEntityAlive(std::uint64_t entity) const noexcept {
        return ::goud_entity_alive(handle_, entity);
    }

    /** @brief Poll window events and return the frame delta time. */
    float pollEvents() const noexcept {
        return ::goud_window_poll_events_checked(handle_);
    }

    /** @brief Swap the front and back framebuffers. */
    void swapBuffers() const noexcept {
        ::goud_window_swap_buffers_checked(handle_);
    }

    /** @brief Enable alpha blending for the renderer. */
    void enableBlending() const noexcept {
        ::goud_renderer_enable_blending_checked(handle_);
    }

    /** @brief Get the delta time for the current frame. */
    float deltaTime() const noexcept {
        return ::goud_window_delta_time(handle_);
    }

    /** @brief Clear the framebuffer with a solid colour. */
    void clear(::goud_color color) const noexcept {
        ::goud_renderer_clear_color(handle_, color);
    }

    /** @brief Activate the audio subsystem. */
    int activateAudio() const noexcept {
        return ::goud_audio_activate_checked(handle_);
    }

    /** @brief Play audio from an in-memory buffer. */
    int playAudio(const void * asset_data, std::size_t asset_len, ::goud_audio_player & out_player) const noexcept {
        return ::goud_audio_play_memory(handle_, asset_data, asset_len, &out_player);
    }

    /** @brief Stop an active audio player. */
    int stopAudio(::goud_audio_player player_id) const noexcept {
        return ::goud_audio_stop_checked(handle_, player_id);
    }

    /** @brief Set the global audio volume. */
    int setGlobalVolume(float volume) const noexcept {
        return ::goud_audio_set_global_volume_checked(handle_, volume);
    }

    /** @brief Retrieve per-frame render statistics. */
    int renderStats(::goud_render_stats & out_stats) const noexcept {
        return ::goud_renderer_stats(handle_, &out_stats);
    }

private:
    ::goud_context handle_;
};

/** @brief High-level engine wrapper that owns a Context.
 *
 *  Created from an EngineConfig via Engine::create().  Delegates window
 *  and rendering operations to the owned Context.
 */
class Engine {
public:
    /** @brief Construct an empty (invalid) engine. */
    Engine() noexcept = default;

    /** @brief Construct from an existing context.
     *  @param context  Context to take ownership of (moved).
     */
    explicit Engine(Context &&context) noexcept
        : context_(std::move(context)) {}

    /** @brief Create an engine from a configuration.
     *
     *  The config is consumed (moved) regardless of success or failure.
     *
     *  @param config            Configuration to consume.
     *  @param[out] out_status   Optional pointer to receive the status code.
     *  @return A valid Engine on success.
     */
    static Engine create(EngineConfig &&config, int *out_status = nullptr) noexcept {
        Engine engine;
        ::goud_context handle = ::goud_context_invalid();
        ::goud_engine_config raw_config = config.release();
        int status = ::goud_engine_create_checked(&raw_config, &handle);
        engine.context_ = Context(handle);
        if (out_status != nullptr) {
            *out_status = status;
        }
        return engine;
    }

    /** @brief Create a shared-ownership engine.
     *  @param config            Configuration to consume.
     *  @param[out] out_status   Optional pointer to receive the status code.
     *  @return A shared_ptr owning the engine.
     */
    static std::shared_ptr<Engine> createShared(EngineConfig &&config, int *out_status = nullptr) {
        auto engine = std::make_shared<Engine>();
        ::goud_context handle = ::goud_context_invalid();
        ::goud_engine_config raw_config = config.release();
        int status = ::goud_engine_create_checked(&raw_config, &handle);
        engine->context_ = Context(handle);
        if (out_status != nullptr) {
            *out_status = status;
        }
        return engine;
    }

    /** @brief Check whether the engine context is valid. */
    bool valid() const noexcept {
        return context_.valid();
    }

    /** @brief Access the owned context (mutable).
     *  @return Reference to the context.
     */
    Context &context() noexcept {
        return context_;
    }

    /** @brief Access the owned context (const).
     *  @return Const reference to the context.
     */
    const Context &context() const noexcept {
        return context_;
    }

    /** @brief Access the raw FFI context handle.
     *  @return The underlying handle.
     */
    ::goud_context raw() const noexcept {
        return context_.raw();
    }

    /** @brief Check whether the window close has been requested.
     *  @return true if the window should close.
     */
    bool shouldClose() const noexcept {
        return context_.shouldClose();
    }

    /** @brief Poll window events and return the frame delta time.
     *  @return Delta time in seconds.
     */
    float pollEvents() noexcept {
        return context_.pollEvents();
    }

    /** @brief Swap the front and back framebuffers. */
    void swapBuffers() noexcept {
        context_.swapBuffers();
    }

    /** @brief Enable alpha blending for the renderer. */
    void enableBlending() noexcept {
        context_.enableBlending();
    }

    /** @brief Get the delta time for the current frame.
     *  @return Delta time in seconds.
     */
    float deltaTime() const noexcept {
        return context_.deltaTime();
    }

private:
    Context context_;
};

}  // namespace goud

#endif
