// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class AudioCapabilities {
    public boolean supportsSpatial;
    public int maxChannels;

    public AudioCapabilities() {}

    public AudioCapabilities(boolean supportsSpatial, int maxChannels) {
        this.supportsSpatial = supportsSpatial;
        this.maxChannels = maxChannels;
    }
}
