// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class Contact {
    public float pointX;
    public float pointY;
    public float normalX;
    public float normalY;
    public float penetration;

    public Contact() {}

    public Contact(float pointX, float pointY, float normalX, float normalY, float penetration) {
        this.pointX = pointX;
        this.pointY = pointY;
        this.normalX = normalX;
        this.normalY = normalY;
        this.penetration = penetration;
    }
}
