// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class FramePhaseTimings {
    public long surfaceAcquireUs;
    public long shadowPassUs;
    public long shadowBuildUs;
    public long render3dSceneUs;
    public long uniformUploadUs;
    public long renderPassUs;
    public long gpuSubmitUs;
    public long readbackStallUs;
    public long surfacePresentUs;
    public long animEvalUs;
    public long bonePackUs;
    public long boneUploadUs;

    public FramePhaseTimings() {}

    public FramePhaseTimings(long surfaceAcquireUs, long shadowPassUs, long shadowBuildUs, long render3dSceneUs, long uniformUploadUs, long renderPassUs, long gpuSubmitUs, long readbackStallUs, long surfacePresentUs, long animEvalUs, long bonePackUs, long boneUploadUs) {
        this.surfaceAcquireUs = surfaceAcquireUs;
        this.shadowPassUs = shadowPassUs;
        this.shadowBuildUs = shadowBuildUs;
        this.render3dSceneUs = render3dSceneUs;
        this.uniformUploadUs = uniformUploadUs;
        this.renderPassUs = renderPassUs;
        this.gpuSubmitUs = gpuSubmitUs;
        this.readbackStallUs = readbackStallUs;
        this.surfacePresentUs = surfacePresentUs;
        this.animEvalUs = animEvalUs;
        this.bonePackUs = bonePackUs;
        this.boneUploadUs = boneUploadUs;
    }
}
