// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class JniSmokeMain {
    private JniSmokeMain() {}

    public static void main(String[] args) {
        if (args.length != 1) throw new IllegalArgumentException("Expected library path");
        System.load(args[0]);

        long ctx = GoudContextNative.create();
        if (ctx == 0L || !GoudContextNative.isValid(ctx)) throw new AssertionError("Context should be valid");

        Color color = ColorNative.rgba(0.25f, 0.5f, 0.75f, 1.0f);
        if (Math.abs(color.g - 0.5f) > 0.0001f) throw new AssertionError("Color bridge failed");

        Transform2D transform = Transform2DNative.create(10.0f, 20.0f, 0.0f, 1.0f, 1.0f);
        Transform2DNative.translate(transform, 5.0f, -3.0f);
        Vec2 position = Transform2DNative.getPosition(transform);
        if (Math.abs(position.x - 15.0f) > 0.0001f || Math.abs(position.y - 17.0f) > 0.0001f) {
            throw new AssertionError("Transform mutation bridge failed");
        }

        PluginNative.register(ctx, "jni-smoke");
        if (!PluginNative.isRegistered(ctx, "jni-smoke")) throw new AssertionError("Plugin register failed");
        String list = PluginNative.list(ctx);
        if (!list.contains("jni-smoke")) throw new AssertionError("Plugin list missing registration");
        PluginNative.unregister(ctx, "jni-smoke");

        try {
            PluginNative.register(0L, "bad");
            throw new AssertionError("Expected IllegalStateException for invalid context");
        } catch (IllegalStateException expected) {
        }

        try {
            PluginNative.register(ctx, null);
            throw new AssertionError("Expected NullPointerException for null plugin id");
        } catch (NullPointerException expected) {
        }

        try {
            NetworkNative.send(ctx, -1L, 1L, new byte[] {1, 2, 3}, 0);
            throw new AssertionError("Expected IllegalStateException for invalid network handle");
        } catch (IllegalStateException expected) {
        }

        GoudContextNative.destroy(ctx);
    }
}
