// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class NetworkNative {
    private NetworkNative() {}

    public static native long host(long contextId, int protocol, int port);
    public static native long connect(long contextId, int protocol, String address, int port);
    public static native int disconnect(long contextId, long handle);
    public static native int send(long contextId, long handle, long peerId, byte[] data, int channel);
    public static native byte[] receive(long contextId, long handle);
    public static native int poll(long contextId, long handle);
    public static native Object getStats(long contextId, long handle);
    public static native int peerCount(long contextId, long handle);
}
