// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class NetworkNative {
    private NetworkNative() {}

    public static native long host(long contextId, int protocol, int port);
    public static native long connect(long contextId, int protocol, String address, int port);
    public static native int disconnect(long contextId, long handle);
    public static native int send(long contextId, long handle, long peerId, byte[] data, int channel);
    public static native byte[] receive(long contextId, long handle);
    public static native int poll(long contextId, long handle);
    public static native Object getStats(long contextId, long handle);
    public static native int peerCount(long contextId, long handle);
    public static native long p2pCreateMesh(long contextId, int protocol, int port, P2pMeshConfig config);
    public static native long p2pJoinMesh(long contextId, int protocol, String address, int port, P2pMeshConfig config);
    public static native int p2pLeaveMesh(long contextId, long handle);
    public static native int p2pGetPeers(long contextId, long handle);
    public static native long p2pGetHost(long contextId, long handle);
    public static native long rollbackCreate(RollbackConfig config, int localPlayer, byte[] playerIds, long statePtr, long advanceFn, long hashFn, long cloneFn, long freeFn);
    public static native int rollbackDestroy(long handle);
    public static native int rollbackAdvanceFrame(long handle, byte[] input);
    public static native int rollbackReceiveRemoteInput(long handle, int playerId, long frame, byte[] input);
    public static native int rollbackShouldRollback(long handle);
    public static native int rollbackResimulate(long handle);
    public static native long rollbackConfirmedFrame(long handle);
    public static native long rollbackCurrentFrame(long handle);
    public static native int rollbackCheckDesync(long handle, long remoteHash, long frame);
    public static native long rpcCreate(long timeoutMs, int maxPayload);
    public static native int rpcDestroy(long handle);
    public static native int rpcRegister(long handle, int rpcId, String name, int direction);
    public static native long rpcCall(long handle, long peerId, int rpcId, byte[] payload);
    public static native int rpcPoll(long handle, float deltaSecs);
    public static native int rpcProcessIncoming(long handle, long peerId, byte[] data);
    public static native byte[] rpcReceiveResponse(long handle, long callId);
    public static native byte[] rpcDrainOne(long handle);
}
