// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class PhysicsCollisionEvent2D {
    public long bodyA;
    public long bodyB;
    public int kind;

    public PhysicsCollisionEvent2D() {}

    public PhysicsCollisionEvent2D(long bodyA, long bodyB, int kind) {
        this.bodyA = bodyA;
        this.bodyB = bodyB;
        this.kind = kind;
    }
}
