// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class PluginNative {
    private PluginNative() {}

    public static native int register(long contextId, String pluginId);
    public static native int unregister(long contextId, String pluginId);
    public static native boolean isRegistered(long contextId, String pluginId);
    public static native String list(long contextId);
}
