// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class SkeletonNative {
    private SkeletonNative() {}

    public static native int create(long contextId, long entity);
    public static native int addBone(long contextId, long entity, String boneName, int parentIndex, float x, float y, float rotation);
    public static native int setBoneTransform(long contextId, long entity, int boneIndex, float x, float y, float rotation);
    public static native int playClip(long contextId, long entity, String clipName, boolean looping);
}
