// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class SpriteNative {
    private SpriteNative() {}

    public static native Sprite create(long textureHandle);
    public static native Sprite defaultValue();
    public static native void setColor(Sprite self, float r, float g, float b, float a);
    public static native Color getColor(Sprite self);
    public static native Sprite withColor(Sprite self, float r, float g, float b, float a);
    public static native void setAlpha(Sprite self, float alpha);
    public static native float getAlpha(Sprite self);
    public static native void setSourceRect(Sprite self, float x, float y, float width, float height);
    public static native void clearSourceRect(Sprite self);
    public static native Rect getSourceRect(Sprite self);
    public static native boolean hasSourceRect(Sprite self);
    public static native Sprite withSourceRect(Sprite self, float x, float y, float width, float height);
    public static native void setFlipX(Sprite self, boolean flip);
    public static native boolean getFlipX(Sprite self);
    public static native void setFlipY(Sprite self, boolean flip);
    public static native boolean getFlipY(Sprite self);
    public static native void setFlip(Sprite self, boolean flipX, boolean flipY);
    public static native Sprite withFlipX(Sprite self, boolean flip);
    public static native Sprite withFlipY(Sprite self, boolean flip);
    public static native Sprite withFlip(Sprite self, boolean flipX, boolean flipY);
    public static native boolean isFlipped(Sprite self);
    public static native void setZLayer(Sprite self, int zLayer);
    public static native int getZLayer(Sprite self);
    public static native Sprite withZLayer(Sprite self, int zLayer);
    public static native void setAnchor(Sprite self, float x, float y);
    public static native Vec2 getAnchor(Sprite self);
    public static native Sprite withAnchor(Sprite self, float x, float y);
    public static native void setCustomSize(Sprite self, float width, float height);
    public static native void clearCustomSize(Sprite self);
    public static native Vec2 getCustomSize(Sprite self);
    public static native boolean hasCustomSize(Sprite self);
    public static native Sprite withCustomSize(Sprite self, float width, float height);
    public static native void setTexture(Sprite self, long handle);
    public static native long getTexture(Sprite self);
    public static native Vec2 sizeOrRect(Sprite self);
}
