// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class UiStyle {
    public boolean hasBackgroundColor;
    public Color backgroundColor;
    public boolean hasForegroundColor;
    public Color foregroundColor;
    public boolean hasBorderColor;
    public Color borderColor;
    public boolean hasBorderWidth;
    public float borderWidth;
    public boolean hasFontFamily;
    public long fontFamilyPtr;
    public long fontFamilyLen;
    public boolean hasFontSize;
    public float fontSize;
    public boolean hasTexturePath;
    public long texturePathPtr;
    public long texturePathLen;
    public boolean hasWidgetSpacing;
    public float widgetSpacing;

    public UiStyle() {}

    public UiStyle(boolean hasBackgroundColor, Color backgroundColor, boolean hasForegroundColor, Color foregroundColor, boolean hasBorderColor, Color borderColor, boolean hasBorderWidth, float borderWidth, boolean hasFontFamily, long fontFamilyPtr, long fontFamilyLen, boolean hasFontSize, float fontSize, boolean hasTexturePath, long texturePathPtr, long texturePathLen, boolean hasWidgetSpacing, float widgetSpacing) {
        this.hasBackgroundColor = hasBackgroundColor;
        this.backgroundColor = backgroundColor;
        this.hasForegroundColor = hasForegroundColor;
        this.foregroundColor = foregroundColor;
        this.hasBorderColor = hasBorderColor;
        this.borderColor = borderColor;
        this.hasBorderWidth = hasBorderWidth;
        this.borderWidth = borderWidth;
        this.hasFontFamily = hasFontFamily;
        this.fontFamilyPtr = fontFamilyPtr;
        this.fontFamilyLen = fontFamilyLen;
        this.hasFontSize = hasFontSize;
        this.fontSize = fontSize;
        this.hasTexturePath = hasTexturePath;
        this.texturePathPtr = texturePathPtr;
        this.texturePathLen = texturePathLen;
        this.hasWidgetSpacing = hasWidgetSpacing;
        this.widgetSpacing = widgetSpacing;
    }
}
