// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.AudioNative

class Audio(private val contextId: Long) {

    fun stop(playerId: Long): Int =
        AudioNative.stop(contextId, playerId)

    fun pause(playerId: Long): Int =
        AudioNative.pause(contextId, playerId)

    fun resume(playerId: Long): Int =
        AudioNative.resume(contextId, playerId)

    fun stopAll(): Int =
        AudioNative.stopAll(contextId)

    fun setGlobalVolume(volume: Float): Int =
        AudioNative.setGlobalVolume(contextId, volume)

    fun getGlobalVolume(): Float =
        AudioNative.getGlobalVolume(contextId)

    fun setChannelVolume(channel: Int, volume: Float): Int =
        AudioNative.setChannelVolume(contextId, channel, volume)

    fun getChannelVolume(channel: Int): Float =
        AudioNative.getChannelVolume(contextId, channel)

    fun isPlaying(playerId: Long): Int =
        AudioNative.isPlaying(contextId, playerId)

    fun activeCount(): Int =
        AudioNative.activeCount(contextId)

    fun cleanupFinished(): Int =
        AudioNative.cleanupFinished(contextId)

}
