// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

/** Coordinate origin for draw calls. Controls how (x, y) position is interpreted in DrawQuad and DrawSprite. */
enum class CoordinateOrigin(val value: Int) {
    Center(0),
    TopLeft(1);

    companion object {
        fun fromValue(value: Int): CoordinateOrigin? =
            entries.firstOrNull { it.value == value }
    }
}
