// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.GoudContextNative
import com.goudengine.types.*

/** Headless engine context for CI tests and non-windowed entity management. */
class GoudContext internal constructor(internal val contextId: Long) : AutoCloseable {

    companion object {
        fun create(): GoudContext {
            val ctx = GoudContextNative.create()
            require(ctx != 0L) { "Failed to create GoudContext" }
            return GoudContext(ctx)
        }
    }

    fun isValid(): Boolean =
        GoudContextNative.isValid(contextId)

    fun networkHost(protocol: Int, port: Int): Long =
        GoudContextNative.networkHost(contextId, protocol, port)

    fun networkConnect(protocol: Int, address: String, port: Int): Long =
        GoudContextNative.networkConnect(contextId, protocol, address, port)

    fun networkDisconnect(handle: Long): Int =
        GoudContextNative.networkDisconnect(contextId, handle)

    fun networkSend(handle: Long, peerId: Long, data: ByteArray, channel: Int): Int =
        GoudContextNative.networkSend(contextId, handle, peerId, data, channel)

    fun networkReceive(handle: Long): ByteArray =
        GoudContextNative.networkReceive(contextId, handle)

    fun networkPoll(handle: Long): Int =
        GoudContextNative.networkPoll(contextId, handle)

    fun networkPeerCount(handle: Long): Int =
        GoudContextNative.networkPeerCount(contextId, handle)

    fun clearNetworkSimulation(handle: Long): Int =
        GoudContextNative.clearNetworkSimulation(contextId, handle)

    fun setNetworkOverlayHandle(handle: Long): Int =
        GoudContextNative.setNetworkOverlayHandle(contextId, handle)

    fun clearNetworkOverlayHandle(): Int =
        GoudContextNative.clearNetworkOverlayHandle(contextId)

    fun setDebuggerPaused(paused: Boolean) {
        GoudContextNative.setDebuggerPaused(contextId, paused)
    }

    fun stepDebugger(kind: com.goudengine.core.DebuggerStepKind, count: Int) {
        GoudContextNative.stepDebugger(contextId, kind.value, count)
    }

    fun setDebuggerTimeScale(scale: Float) {
        GoudContextNative.setDebuggerTimeScale(contextId, scale)
    }

    fun setDebuggerDebugDrawEnabled(enabled: Boolean) {
        GoudContextNative.setDebuggerDebugDrawEnabled(contextId, enabled)
    }

    fun injectDebuggerKeyEvent(key: com.goudengine.input.Key, pressed: Boolean) {
        GoudContextNative.injectDebuggerKeyEvent(contextId, key.value, pressed)
    }

    fun injectDebuggerMouseButton(button: com.goudengine.input.MouseButton, pressed: Boolean) {
        GoudContextNative.injectDebuggerMouseButton(contextId, button.value, pressed)
    }

    fun injectDebuggerMousePosition(position: com.goudengine.types.Vec2) {
        GoudContextNative.injectDebuggerMousePosition(contextId, position.toNative())
    }

    fun injectDebuggerScroll(delta: com.goudengine.types.Vec2) {
        GoudContextNative.injectDebuggerScroll(contextId, delta.toNative())
    }

    fun setDebuggerProfilingEnabled(enabled: Boolean) {
        GoudContextNative.setDebuggerProfilingEnabled(contextId, enabled)
    }

    fun setDebuggerSelectedEntity(entityId: Long) {
        GoudContextNative.setDebuggerSelectedEntity(contextId, entityId)
    }

    fun clearDebuggerSelectedEntity() {
        GoudContextNative.clearDebuggerSelectedEntity(contextId)
    }

    fun startDebuggerRecording() {
        GoudContextNative.startDebuggerRecording(contextId)
    }

    fun startDebuggerReplay(recording: ByteArray) {
        GoudContextNative.startDebuggerReplay(contextId, recording)
    }

    fun stopDebuggerReplay() {
        GoudContextNative.stopDebuggerReplay(contextId)
    }

    fun spawnEmpty(): com.goudengine.core.EntityHandle {
        val r = GoudContextNative.spawnEmpty(contextId)
        return com.goudengine.core.EntityHandle(r)
    }

    fun despawn(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.despawn(contextId, entity.id)

    fun cloneEntity(entity: com.goudengine.core.EntityHandle): com.goudengine.core.EntityHandle {
        val r = GoudContextNative.cloneEntity(contextId, entity.id)
        return com.goudengine.core.EntityHandle(r)
    }

    fun cloneEntityRecursive(entity: com.goudengine.core.EntityHandle): com.goudengine.core.EntityHandle {
        val r = GoudContextNative.cloneEntityRecursive(contextId, entity.id)
        return com.goudengine.core.EntityHandle(r)
    }

    fun isAlive(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.isAlive(contextId, entity.id)

    fun entityCount(): Int =
        GoudContextNative.entityCount(contextId)

    fun addTransform2d(entity: com.goudengine.core.EntityHandle, transform: com.goudengine.components.Transform2D) {
        GoudContextNative.addTransform2d(contextId, entity.id, transform.native)
    }

    fun getTransform2d(entity: com.goudengine.core.EntityHandle): com.goudengine.components.Transform2D? {
        val r = GoudContextNative.getTransform2d(contextId, entity.id)
        if (r == null) return null
        return com.goudengine.components.Transform2D(r)
    }

    fun setTransform2d(entity: com.goudengine.core.EntityHandle, transform: com.goudengine.components.Transform2D) {
        GoudContextNative.setTransform2d(contextId, entity.id, transform.native)
    }

    fun hasTransform2d(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.hasTransform2d(contextId, entity.id)

    fun removeTransform2d(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.removeTransform2d(contextId, entity.id)

    fun addSprite(entity: com.goudengine.core.EntityHandle, sprite: com.goudengine.components.Sprite) {
        GoudContextNative.addSprite(contextId, entity.id, sprite.native)
    }

    fun getSprite(entity: com.goudengine.core.EntityHandle): com.goudengine.components.Sprite? {
        val r = GoudContextNative.getSprite(contextId, entity.id)
        if (r == null) return null
        return com.goudengine.components.Sprite(r)
    }

    fun setSprite(entity: com.goudengine.core.EntityHandle, sprite: com.goudengine.components.Sprite) {
        GoudContextNative.setSprite(contextId, entity.id, sprite.native)
    }

    fun hasSprite(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.hasSprite(contextId, entity.id)

    fun removeSprite(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.removeSprite(contextId, entity.id)

    fun addName(entity: com.goudengine.core.EntityHandle, name: String) {
        GoudContextNative.addName(contextId, entity.id, name)
    }

    fun getName(entity: com.goudengine.core.EntityHandle): String? =
        GoudContextNative.getName(contextId, entity.id)

    fun hasName(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.hasName(contextId, entity.id)

    fun removeName(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudContextNative.removeName(contextId, entity.id)

    fun componentRegisterType(typeIdHash: Long, name: String, size: Long, align: Long): Boolean =
        GoudContextNative.componentRegisterType(typeIdHash, name, size, align)

    fun componentRemove(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Boolean =
        GoudContextNative.componentRemove(contextId, entity.id, typeIdHash)

    fun componentHas(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Boolean =
        GoudContextNative.componentHas(contextId, entity.id, typeIdHash)

    fun componentCount(typeIdHash: Long): Int =
        GoudContextNative.componentCount(contextId, typeIdHash)

    fun sceneCreate(name: String): Int =
        GoudContextNative.sceneCreate(contextId, name)

    fun sceneGetByName(name: String): Int =
        GoudContextNative.sceneGetByName(contextId, name)

    fun loadScene(name: String, json: String): Int =
        GoudContextNative.loadScene(contextId, name, json)

    fun sceneIsActive(sceneId: Int): Boolean =
        GoudContextNative.sceneIsActive(contextId, sceneId)

    fun sceneCount(): Int =
        GoudContextNative.sceneCount(contextId)

    fun sceneGetCurrent(): Int =
        GoudContextNative.sceneGetCurrent(contextId)

    fun sceneTransitionProgress(): Float =
        GoudContextNative.sceneTransitionProgress(contextId)

    fun sceneTransitionIsActive(): Boolean =
        GoudContextNative.sceneTransitionIsActive(contextId)

    fun getFrameMetrics(): RenderMetrics {
        val r = GoudContextNative.getFrameMetrics(contextId)
        return com.goudengine.types.RenderMetrics(r.drawCallCount, r.spritesSubmitted, r.spritesDrawn, r.spritesCulled, r.batchesSubmitted, r.avgSpritesPerBatch, r.spriteRenderMs, r.textRenderMs, r.uiRenderMs, r.totalRenderMs, r.textDrawCalls, r.textGlyphCount, r.uiDrawCalls)
    }

    fun destroy() {
        GoudContextNative.destroy(contextId)
    }

    override fun close() = destroy()
}
