// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.GoudGameNative

class GoudGame private constructor(internal val contextId: Long) : AutoCloseable {

    companion object {
        fun create(width: Int = 800, height: Int = 600, title: String = "GoudEngine"): GoudGame {
            val ctx = GoudGameNative.create(width, height, title)
            require(ctx != 0L) { "Failed to create GoudGame" }
            return GoudGame(ctx)
        }
    }

    fun shouldClose(): Boolean =
        GoudGameNative.shouldClose(contextId)

    fun requestClose() {
        GoudGameNative.close(contextId)
    }

    fun setWindowSize(width: Int, height: Int): Boolean =
        GoudGameNative.setWindowSize(contextId, width, height)

    fun beginFrame(r: Float, g: Float, b: Float, a: Float) {
        GoudGameNative.beginFrame(contextId, r, g, b, a)
    }

    fun endFrame() {
        GoudGameNative.endFrame(contextId)
    }

    fun run(update: Callback(f32)) {
        GoudGameNative.run(contextId, update)
    }

    fun loadTexture(path: String): Long =
        GoudGameNative.loadTexture(contextId, path)

    fun destroyTexture(handle: Long) {
        GoudGameNative.destroyTexture(contextId, handle)
    }

    fun loadFont(path: String): Long =
        GoudGameNative.loadFont(contextId, path)

    fun destroyFont(handle: Long): Boolean =
        GoudGameNative.destroyFont(contextId, handle)

    fun drawText(fontHandle: Long, text: String, x: Float, y: Float, fontSize: Float, alignment: com.goudengine.core.TextAlignment, maxWidth: Float, lineSpacing: Float, direction: com.goudengine.core.TextDirection, color: com.goudengine.types.Color): Boolean =
        GoudGameNative.drawText(contextId, fontHandle, text, x, y, fontSize, alignment.value, maxWidth, lineSpacing, direction.value, color.toNative())

    fun drawSprite(texture: Long, x: Float, y: Float, width: Float, height: Float, rotation: Float, color: com.goudengine.types.Color) {
        GoudGameNative.drawSprite(contextId, texture, x, y, width, height, rotation, color.toNative())
    }

    fun drawQuad(x: Float, y: Float, width: Float, height: Float, color: com.goudengine.types.Color) {
        GoudGameNative.drawQuad(contextId, x, y, width, height, color.toNative())
    }

    fun isKeyPressed(key: com.goudengine.input.Key): Boolean =
        GoudGameNative.isKeyPressed(contextId, key.value)

    fun isKeyJustPressed(key: com.goudengine.input.Key): Boolean =
        GoudGameNative.isKeyJustPressed(contextId, key.value)

    fun isKeyJustReleased(key: com.goudengine.input.Key): Boolean =
        GoudGameNative.isKeyJustReleased(contextId, key.value)

    fun isMouseButtonPressed(button: com.goudengine.input.MouseButton): Boolean =
        GoudGameNative.isMouseButtonPressed(contextId, button.value)

    fun isMouseButtonJustPressed(button: com.goudengine.input.MouseButton): Boolean =
        GoudGameNative.isMouseButtonJustPressed(contextId, button.value)

    fun isMouseButtonJustReleased(button: com.goudengine.input.MouseButton): Boolean =
        GoudGameNative.isMouseButtonJustReleased(contextId, button.value)

    fun getMousePosition(): com.goudengine.types.Vec2 {
        val r = GoudGameNative.getMousePosition(contextId)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun getMouseDelta(): com.goudengine.types.Vec2 {
        val r = GoudGameNative.getMouseDelta(contextId)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun getScrollDelta(): com.goudengine.types.Vec2 {
        val r = GoudGameNative.getScrollDelta(contextId)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun spawnEmpty(): com.goudengine.core.EntityHandle {
        val r = GoudGameNative.spawnEmpty(contextId)
        return com.goudengine.core.EntityHandle(r)
    }

    fun despawn(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.despawn(contextId, entity.id)

    fun cloneEntity(entity: com.goudengine.core.EntityHandle): com.goudengine.core.EntityHandle {
        val r = GoudGameNative.cloneEntity(contextId, entity.id)
        return com.goudengine.core.EntityHandle(r)
    }

    fun cloneEntityRecursive(entity: com.goudengine.core.EntityHandle): com.goudengine.core.EntityHandle {
        val r = GoudGameNative.cloneEntityRecursive(contextId, entity.id)
        return com.goudengine.core.EntityHandle(r)
    }

    fun entityCount(): Int =
        GoudGameNative.entityCount(contextId)

    fun isAlive(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.isAlive(contextId, entity.id)

    fun isAliveBatch(entities: Entity[], outResults: U8[]): Int =
        GoudGameNative.isAliveBatch(contextId, entities, outResults)

    fun addTransform2d(entity: com.goudengine.core.EntityHandle, transform: com.goudengine.components.Transform2D) {
        GoudGameNative.addTransform2d(contextId, entity.id, transform.native)
    }

    fun getTransform2d(entity: com.goudengine.core.EntityHandle): com.goudengine.components.Transform2D? {
        val r = GoudGameNative.getTransform2d(contextId, entity.id)
        return com.goudengine.components.Transform2D(r)
    }

    fun setTransform2d(entity: com.goudengine.core.EntityHandle, transform: com.goudengine.components.Transform2D) {
        GoudGameNative.setTransform2d(contextId, entity.id, transform.native)
    }

    fun hasTransform2d(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.hasTransform2d(contextId, entity.id)

    fun removeTransform2d(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.removeTransform2d(contextId, entity.id)

    fun addName(entity: com.goudengine.core.EntityHandle, name: String) {
        GoudGameNative.addName(contextId, entity.id, name)
    }

    fun getName(entity: com.goudengine.core.EntityHandle): String? =
        GoudGameNative.getName(contextId, entity.id)

    fun hasName(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.hasName(contextId, entity.id)

    fun removeName(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.removeName(contextId, entity.id)

    fun addSprite(entity: com.goudengine.core.EntityHandle, sprite: com.goudengine.components.Sprite) {
        GoudGameNative.addSprite(contextId, entity.id, sprite.native)
    }

    fun getSprite(entity: com.goudengine.core.EntityHandle): com.goudengine.components.Sprite? {
        val r = GoudGameNative.getSprite(contextId, entity.id)
        return com.goudengine.components.Sprite(r)
    }

    fun setSprite(entity: com.goudengine.core.EntityHandle, sprite: com.goudengine.components.Sprite) {
        GoudGameNative.setSprite(contextId, entity.id, sprite.native)
    }

    fun hasSprite(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.hasSprite(contextId, entity.id)

    fun removeSprite(entity: com.goudengine.core.EntityHandle): Boolean =
        GoudGameNative.removeSprite(contextId, entity.id)

    fun spawnBatch(count: Int): Array<com.goudengine.core.EntityHandle> {
        val r = GoudGameNative.spawnBatch(contextId, count)
        return com.goudengine.core.EntityHandle(r)
    }

    fun despawnBatch(entities: Entity[]): Int =
        GoudGameNative.despawnBatch(contextId, entities)

    fun play(entity: com.goudengine.core.EntityHandle): Int =
        GoudGameNative.play(contextId, entity.id)

    fun stop(entity: com.goudengine.core.EntityHandle): Int =
        GoudGameNative.stop(contextId, entity.id)

    fun setState(entity: com.goudengine.core.EntityHandle, stateName: String): Int =
        GoudGameNative.setState(contextId, entity.id, stateName)

    fun setParameterBool(entity: com.goudengine.core.EntityHandle, name: String, value: Boolean): Int =
        GoudGameNative.setParameterBool(contextId, entity.id, name, value)

    fun setParameterFloat(entity: com.goudengine.core.EntityHandle, name: String, value: Float): Int =
        GoudGameNative.setParameterFloat(contextId, entity.id, name, value)

    fun createCube(textureId: Int, width: Float, height: Float, depth: Float): Int =
        GoudGameNative.createCube(contextId, textureId, width, height, depth)

    fun createPlane(textureId: Int, width: Float, depth: Float): Int =
        GoudGameNative.createPlane(contextId, textureId, width, depth)

    fun createSphere(textureId: Int, diameter: Float, segments: Int): Int =
        GoudGameNative.createSphere(contextId, textureId, diameter, segments)

    fun createCylinder(textureId: Int, radius: Float, height: Float, segments: Int): Int =
        GoudGameNative.createCylinder(contextId, textureId, radius, height, segments)

    fun setObjectPosition(objectId: Int, x: Float, y: Float, z: Float): Boolean =
        GoudGameNative.setObjectPosition(contextId, objectId, x, y, z)

    fun setObjectRotation(objectId: Int, x: Float, y: Float, z: Float): Boolean =
        GoudGameNative.setObjectRotation(contextId, objectId, x, y, z)

    fun setObjectScale(objectId: Int, x: Float, y: Float, z: Float): Boolean =
        GoudGameNative.setObjectScale(contextId, objectId, x, y, z)

    fun destroyObject(objectId: Int): Boolean =
        GoudGameNative.destroyObject(contextId, objectId)

    fun addLight(lightType: Int, posX: Float, posY: Float, posZ: Float, dirX: Float, dirY: Float, dirZ: Float, r: Float, g: Float, b: Float, intensity: Float, range: Float, spotAngle: Float): Int =
        GoudGameNative.addLight(contextId, lightType, posX, posY, posZ, dirX, dirY, dirZ, r, g, b, intensity, range, spotAngle)

    fun updateLight(lightId: Int, lightType: Int, posX: Float, posY: Float, posZ: Float, dirX: Float, dirY: Float, dirZ: Float, r: Float, g: Float, b: Float, intensity: Float, range: Float, spotAngle: Float): Boolean =
        GoudGameNative.updateLight(contextId, lightId, lightType, posX, posY, posZ, dirX, dirY, dirZ, r, g, b, intensity, range, spotAngle)

    fun removeLight(lightId: Int): Boolean =
        GoudGameNative.removeLight(contextId, lightId)

    fun setCameraPosition3D(x: Float, y: Float, z: Float): Boolean =
        GoudGameNative.setCameraPosition3D(contextId, x, y, z)

    fun setCameraRotation3D(pitch: Float, yaw: Float, roll: Float): Boolean =
        GoudGameNative.setCameraRotation3D(contextId, pitch, yaw, roll)

    fun configureGrid(enabled: Boolean, size: Float, divisions: Int): Boolean =
        GoudGameNative.configureGrid(contextId, enabled, size, divisions)

    fun setGridEnabled(enabled: Boolean): Boolean =
        GoudGameNative.setGridEnabled(contextId, enabled)

    fun configureSkybox(enabled: Boolean, r: Float, g: Float, b: Float, a: Float): Boolean =
        GoudGameNative.configureSkybox(contextId, enabled, r, g, b, a)

    fun configureFog(enabled: Boolean, r: Float, g: Float, b: Float, density: Float): Boolean =
        GoudGameNative.configureFog(contextId, enabled, r, g, b, density)

    fun setFogEnabled(enabled: Boolean): Boolean =
        GoudGameNative.setFogEnabled(contextId, enabled)

    fun render3D(): Boolean =
        GoudGameNative.render3D(contextId)

    fun drawSpriteRect(texture: Long, x: Float, y: Float, width: Float, height: Float, rotation: Float, srcX: Float, srcY: Float, srcW: Float, srcH: Float, color: com.goudengine.types.Color): Boolean =
        GoudGameNative.drawSpriteRect(contextId, texture, x, y, width, height, rotation, srcX, srcY, srcW, srcH, color.toNative())

    fun setViewport(x: Int, y: Int, width: Int, height: Int) {
        GoudGameNative.setViewport(contextId, x, y, width, height)
    }

    fun enableDepthTest() {
        GoudGameNative.enableDepthTest(contextId)
    }

    fun disableDepthTest() {
        GoudGameNative.disableDepthTest(contextId)
    }

    fun clearDepth() {
        GoudGameNative.clearDepth(contextId)
    }

    fun disableBlending() {
        GoudGameNative.disableBlending(contextId)
    }

    fun getRenderStats(): RenderStats =
        GoudGameNative.getRenderStats(contextId)

    fun getFpsStats(): FpsStats =
        GoudGameNative.getFpsStats(contextId)

    fun setFpsOverlayEnabled(enabled: Boolean) {
        GoudGameNative.setFpsOverlayEnabled(contextId, enabled)
    }

    fun setFpsUpdateInterval(interval: Float) {
        GoudGameNative.setFpsUpdateInterval(contextId, interval)
    }

    fun setFpsOverlayCorner(corner: com.goudengine.core.OverlayCorner) {
        GoudGameNative.setFpsOverlayCorner(contextId, corner.value)
    }

    fun getDebuggerSnapshotJson(): String =
        GoudGameNative.getDebuggerSnapshotJson(contextId)

    fun getDebuggerManifestJson(): String =
        GoudGameNative.getDebuggerManifestJson(contextId)

    fun setDebuggerPaused(paused: Boolean) {
        GoudGameNative.setDebuggerPaused(contextId, paused)
    }

    fun stepDebugger(kind: com.goudengine.core.DebuggerStepKind, count: Int) {
        GoudGameNative.stepDebugger(contextId, kind.value, count)
    }

    fun setDebuggerTimeScale(scale: Float) {
        GoudGameNative.setDebuggerTimeScale(contextId, scale)
    }

    fun setDebuggerDebugDrawEnabled(enabled: Boolean) {
        GoudGameNative.setDebuggerDebugDrawEnabled(contextId, enabled)
    }

    fun injectDebuggerKeyEvent(key: com.goudengine.input.Key, pressed: Boolean) {
        GoudGameNative.injectDebuggerKeyEvent(contextId, key.value, pressed)
    }

    fun injectDebuggerMouseButton(button: com.goudengine.input.MouseButton, pressed: Boolean) {
        GoudGameNative.injectDebuggerMouseButton(contextId, button.value, pressed)
    }

    fun injectDebuggerMousePosition(position: com.goudengine.types.Vec2) {
        GoudGameNative.injectDebuggerMousePosition(contextId, position.toNative())
    }

    fun injectDebuggerScroll(delta: com.goudengine.types.Vec2) {
        GoudGameNative.injectDebuggerScroll(contextId, delta.toNative())
    }

    fun setDebuggerProfilingEnabled(enabled: Boolean) {
        GoudGameNative.setDebuggerProfilingEnabled(contextId, enabled)
    }

    fun setDebuggerSelectedEntity(entityId: Long) {
        GoudGameNative.setDebuggerSelectedEntity(contextId, entityId)
    }

    fun clearDebuggerSelectedEntity() {
        GoudGameNative.clearDebuggerSelectedEntity(contextId)
    }

    fun getMemorySummary(): MemorySummary =
        GoudGameNative.getMemorySummary(contextId)

    fun captureDebuggerFrame(): DebuggerCapture =
        GoudGameNative.captureDebuggerFrame(contextId)

    fun startDebuggerRecording() {
        GoudGameNative.startDebuggerRecording(contextId)
    }

    fun stopDebuggerRecording(): DebuggerReplayArtifact =
        GoudGameNative.stopDebuggerRecording(contextId)

    fun startDebuggerReplay(recording: ByteArray) {
        GoudGameNative.startDebuggerReplay(contextId, recording)
    }

    fun stopDebuggerReplay() {
        GoudGameNative.stopDebuggerReplay(contextId)
    }

    fun getDebuggerReplayStatusJson(): String =
        GoudGameNative.getDebuggerReplayStatusJson(contextId)

    fun getDebuggerMetricsTraceJson(): String =
        GoudGameNative.getDebuggerMetricsTraceJson(contextId)

    fun mapActionKey(action: String, key: com.goudengine.input.Key): Boolean =
        GoudGameNative.mapActionKey(contextId, action, key.value)

    fun isActionPressed(action: String): Boolean =
        GoudGameNative.isActionPressed(contextId, action)

    fun isActionJustPressed(action: String): Boolean =
        GoudGameNative.isActionJustPressed(contextId, action)

    fun isActionJustReleased(action: String): Boolean =
        GoudGameNative.isActionJustReleased(contextId, action)

    fun collisionAabbAabb(centerAx: Float, centerAy: Float, halfWa: Float, halfHa: Float, centerBx: Float, centerBy: Float, halfWb: Float, halfHb: Float): Contact? =
        GoudGameNative.collisionAabbAabb(contextId, centerAx, centerAy, halfWa, halfHa, centerBx, centerBy, halfWb, halfHb)

    fun collisionCircleCircle(centerAx: Float, centerAy: Float, radiusA: Float, centerBx: Float, centerBy: Float, radiusB: Float): Contact? =
        GoudGameNative.collisionCircleCircle(contextId, centerAx, centerAy, radiusA, centerBx, centerBy, radiusB)

    fun collisionCircleAabb(circleX: Float, circleY: Float, circleRadius: Float, boxX: Float, boxY: Float, boxHw: Float, boxHh: Float): Contact? =
        GoudGameNative.collisionCircleAabb(contextId, circleX, circleY, circleRadius, boxX, boxY, boxHw, boxHh)

    fun pointInRect(px: Float, py: Float, rx: Float, ry: Float, rw: Float, rh: Float): Boolean =
        GoudGameNative.pointInRect(contextId, px, py, rx, ry, rw, rh)

    fun pointInCircle(px: Float, py: Float, cx: Float, cy: Float, radius: Float): Boolean =
        GoudGameNative.pointInCircle(contextId, px, py, cx, cy, radius)

    fun aabbOverlap(minAx: Float, minAy: Float, maxAx: Float, maxAy: Float, minBx: Float, minBy: Float, maxBx: Float, maxBy: Float): Boolean =
        GoudGameNative.aabbOverlap(contextId, minAx, minAy, maxAx, maxAy, minBx, minBy, maxBx, maxBy)

    fun circleOverlap(x1: Float, y1: Float, r1: Float, x2: Float, y2: Float, r2: Float): Boolean =
        GoudGameNative.circleOverlap(contextId, x1, y1, r1, x2, y2, r2)

    fun distance(x1: Float, y1: Float, x2: Float, y2: Float): Float =
        GoudGameNative.distance(contextId, x1, y1, x2, y2)

    fun distanceSquared(x1: Float, y1: Float, x2: Float, y2: Float): Float =
        GoudGameNative.distanceSquared(contextId, x1, y1, x2, y2)

    fun physicsRaycastEx(originX: Float, originY: Float, dirX: Float, dirY: Float, maxDist: Float, layerMask: Int): PhysicsRaycastHit2D? =
        GoudGameNative.physicsRaycastEx(contextId, originX, originY, dirX, dirY, maxDist, layerMask)

    fun physicsCollisionEventsCount(): Int =
        GoudGameNative.physicsCollisionEventsCount(contextId)

    fun physicsCollisionEventsRead(index: Int): PhysicsCollisionEvent2D? =
        GoudGameNative.physicsCollisionEventsRead(contextId, index)

    fun physicsSetCollisionCallback(callbackPtr: Long, userData: Long): Int =
        GoudGameNative.physicsSetCollisionCallback(contextId, callbackPtr, userData)

    fun componentRegisterType(typeIdHash: Long, name: String, size: Long, align: Long): Boolean =
        GoudGameNative.componentRegisterType(contextId, typeIdHash, name, size, align)

    fun componentAdd(entity: com.goudengine.core.EntityHandle, typeIdHash: Long, dataPtr: Long, dataSize: Long): Boolean =
        GoudGameNative.componentAdd(contextId, entity.id, typeIdHash, dataPtr, dataSize)

    fun componentRemove(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Boolean =
        GoudGameNative.componentRemove(contextId, entity.id, typeIdHash)

    fun componentHas(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Boolean =
        GoudGameNative.componentHas(contextId, entity.id, typeIdHash)

    fun componentGet(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Long =
        GoudGameNative.componentGet(contextId, entity.id, typeIdHash)

    fun componentGetMut(entity: com.goudengine.core.EntityHandle, typeIdHash: Long): Long =
        GoudGameNative.componentGetMut(contextId, entity.id, typeIdHash)

    fun componentAddBatch(entities: Entity[], typeIdHash: Long, dataPtr: Long, componentSize: Long): Int =
        GoudGameNative.componentAddBatch(contextId, entities, typeIdHash, dataPtr, componentSize)

    fun componentRemoveBatch(entities: Entity[], typeIdHash: Long): Int =
        GoudGameNative.componentRemoveBatch(contextId, entities, typeIdHash)

    fun componentHasBatch(entities: Entity[], typeIdHash: Long, outResults: U8[]): Int =
        GoudGameNative.componentHasBatch(contextId, entities, typeIdHash, outResults)

    fun getRenderCapabilities(): RenderCapabilities =
        GoudGameNative.getRenderCapabilities(contextId)

    fun getPhysicsCapabilities(): PhysicsCapabilities =
        GoudGameNative.getPhysicsCapabilities(contextId)

    fun getAudioCapabilities(): AudioCapabilities =
        GoudGameNative.getAudioCapabilities(contextId)

    fun getInputCapabilities(): InputCapabilities =
        GoudGameNative.getInputCapabilities(contextId)

    fun getNetworkCapabilities(): NetworkCapabilities =
        GoudGameNative.getNetworkCapabilities(contextId)

    fun networkHost(protocol: Int, port: Int): Long =
        GoudGameNative.networkHost(contextId, protocol, port)

    fun networkConnect(protocol: Int, address: String, port: Int): Long =
        GoudGameNative.networkConnect(contextId, protocol, address, port)

    fun networkConnectWithPeer(protocol: Int, address: String, port: Int): NetworkConnectResult =
        GoudGameNative.networkConnectWithPeer(contextId, protocol, address, port)

    fun networkDisconnect(handle: Long): Int =
        GoudGameNative.networkDisconnect(contextId, handle)

    fun networkSend(handle: Long, peerId: Long, data: ByteArray, channel: Int): Int =
        GoudGameNative.networkSend(contextId, handle, peerId, data, channel)

    fun networkReceive(handle: Long): ByteArray =
        GoudGameNative.networkReceive(contextId, handle)

    fun networkReceivePacket(handle: Long): NetworkPacket? =
        GoudGameNative.networkReceivePacket(contextId, handle)

    fun networkPoll(handle: Long): Int =
        GoudGameNative.networkPoll(contextId, handle)

    fun getNetworkStats(handle: Long): NetworkStats =
        GoudGameNative.getNetworkStats(contextId, handle)

    fun networkPeerCount(handle: Long): Int =
        GoudGameNative.networkPeerCount(contextId, handle)

    fun setNetworkSimulation(handle: Long, config: NetworkSimulationConfig): Int =
        GoudGameNative.setNetworkSimulation(contextId, handle, config)

    fun clearNetworkSimulation(handle: Long): Int =
        GoudGameNative.clearNetworkSimulation(contextId, handle)

    fun setNetworkOverlayHandle(handle: Long): Int =
        GoudGameNative.setNetworkOverlayHandle(contextId, handle)

    fun clearNetworkOverlayHandle(): Int =
        GoudGameNative.clearNetworkOverlayHandle(contextId)

    fun audioPlay(data: ByteArray): Long =
        GoudGameNative.audioPlay(contextId, data)

    fun audioPlayOnChannel(data: ByteArray, channel: Int): Long =
        GoudGameNative.audioPlayOnChannel(contextId, data, channel)

    fun audioPlayWithSettings(data: ByteArray, volume: Float, speed: Float, looping: Boolean, channel: Int): Long =
        GoudGameNative.audioPlayWithSettings(contextId, data, volume, speed, looping, channel)

    fun audioStop(playerId: Long): Int =
        GoudGameNative.audioStop(contextId, playerId)

    fun audioPause(playerId: Long): Int =
        GoudGameNative.audioPause(contextId, playerId)

    fun audioResume(playerId: Long): Int =
        GoudGameNative.audioResume(contextId, playerId)

    fun audioStopAll(): Int =
        GoudGameNative.audioStopAll(contextId)

    fun audioSetGlobalVolume(volume: Float): Int =
        GoudGameNative.audioSetGlobalVolume(contextId, volume)

    fun audioGetGlobalVolume(): Float =
        GoudGameNative.audioGetGlobalVolume(contextId)

    fun audioSetChannelVolume(channel: Int, volume: Float): Int =
        GoudGameNative.audioSetChannelVolume(contextId, channel, volume)

    fun audioGetChannelVolume(channel: Int): Float =
        GoudGameNative.audioGetChannelVolume(contextId, channel)

    fun audioIsPlaying(playerId: Long): Int =
        GoudGameNative.audioIsPlaying(contextId, playerId)

    fun audioActiveCount(): Int =
        GoudGameNative.audioActiveCount(contextId)

    fun audioCleanupFinished(): Int =
        GoudGameNative.audioCleanupFinished(contextId)

    fun audioPlaySpatial3d(data: ByteArray, sourceX: Float, sourceY: Float, sourceZ: Float, listenerX: Float, listenerY: Float, listenerZ: Float, maxDistance: Float, rolloff: Float): Long =
        GoudGameNative.audioPlaySpatial3d(contextId, data, sourceX, sourceY, sourceZ, listenerX, listenerY, listenerZ, maxDistance, rolloff)

    fun audioUpdateSpatial3d(playerId: Long, sourceX: Float, sourceY: Float, sourceZ: Float, listenerX: Float, listenerY: Float, listenerZ: Float, maxDistance: Float, rolloff: Float): Int =
        GoudGameNative.audioUpdateSpatial3d(contextId, playerId, sourceX, sourceY, sourceZ, listenerX, listenerY, listenerZ, maxDistance, rolloff)

    fun audioSetListenerPosition3d(x: Float, y: Float, z: Float): Int =
        GoudGameNative.audioSetListenerPosition3d(contextId, x, y, z)

    fun audioSetSourcePosition3d(playerId: Long, x: Float, y: Float, z: Float, maxDistance: Float, rolloff: Float): Int =
        GoudGameNative.audioSetSourcePosition3d(contextId, playerId, x, y, z, maxDistance, rolloff)

    fun audioSetPlayerVolume(playerId: Long, volume: Float): Int =
        GoudGameNative.audioSetPlayerVolume(contextId, playerId, volume)

    fun audioSetPlayerSpeed(playerId: Long, speed: Float): Int =
        GoudGameNative.audioSetPlayerSpeed(contextId, playerId, speed)

    fun audioCrossfade(fromPlayerId: Long, toPlayerId: Long, mix: Float): Int =
        GoudGameNative.audioCrossfade(contextId, fromPlayerId, toPlayerId, mix)

    fun audioCrossfadeTo(fromPlayerId: Long, data: ByteArray, durationSec: Float, channel: Int): Long =
        GoudGameNative.audioCrossfadeTo(contextId, fromPlayerId, data, durationSec, channel)

    fun audioMixWith(primaryPlayerId: Long, data: ByteArray, secondaryVolume: Float, secondaryChannel: Int): Long =
        GoudGameNative.audioMixWith(contextId, primaryPlayerId, data, secondaryVolume, secondaryChannel)

    fun audioUpdateCrossfades(deltaSec: Float): Int =
        GoudGameNative.audioUpdateCrossfades(contextId, deltaSec)

    fun audioActiveCrossfadeCount(): Int =
        GoudGameNative.audioActiveCrossfadeCount(contextId)

    fun audioActivate(): Int =
        GoudGameNative.audioActivate(contextId)

    fun checkHotSwapShortcut(): Boolean =
        GoudGameNative.checkHotSwapShortcut(contextId)

    fun destroy() {
        GoudGameNative.destroy(contextId)
    }

    override fun close() = destroy()
}
