// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.NetworkNative

class Network(private val contextId: Long) {

    fun host(protocol: Int, port: Int): Long =
        NetworkNative.host(contextId, protocol, port)

    fun connect(protocol: Int, address: String, port: Int): Long =
        NetworkNative.connect(contextId, protocol, address, port)

    fun disconnect(handle: Long): Int =
        NetworkNative.disconnect(contextId, handle)

    fun send(handle: Long, peerId: Long, data: ByteArray, channel: Int): Int =
        NetworkNative.send(contextId, handle, peerId, data, channel)

    fun receive(handle: Long): ByteArray =
        NetworkNative.receive(contextId, handle)

    fun poll(handle: Long): Int =
        NetworkNative.poll(contextId, handle)

    fun peerCount(handle: Long): Int =
        NetworkNative.peerCount(contextId, handle)

    fun p2pCreateMesh(protocol: Int, port: Int, config: P2pMeshConfig): Long =
        NetworkNative.p2pCreateMesh(contextId, protocol, port, config)

    fun p2pJoinMesh(protocol: Int, address: String, port: Int, config: P2pMeshConfig): Long =
        NetworkNative.p2pJoinMesh(contextId, protocol, address, port, config)

    fun p2pLeaveMesh(handle: Long): Int =
        NetworkNative.p2pLeaveMesh(contextId, handle)

    fun p2pGetPeers(handle: Long): Int =
        NetworkNative.p2pGetPeers(contextId, handle)

    fun p2pGetHost(handle: Long): Long =
        NetworkNative.p2pGetHost(contextId, handle)

    fun rollbackCreate(config: RollbackConfig, localPlayer: Int, playerIds: ByteArray, statePtr: Long, advanceFn: Long, hashFn: Long, cloneFn: Long, freeFn: Long): Long =
        NetworkNative.rollbackCreate(contextId, config, localPlayer, playerIds, statePtr, advanceFn, hashFn, cloneFn, freeFn)

    fun rollbackDestroy(handle: Long): Int =
        NetworkNative.rollbackDestroy(contextId, handle)

    fun rollbackAdvanceFrame(handle: Long, input: ByteArray): Int =
        NetworkNative.rollbackAdvanceFrame(contextId, handle, input)

    fun rollbackReceiveRemoteInput(handle: Long, playerId: Int, frame: Long, input: ByteArray): Int =
        NetworkNative.rollbackReceiveRemoteInput(contextId, handle, playerId, frame, input)

    fun rollbackShouldRollback(handle: Long): Int =
        NetworkNative.rollbackShouldRollback(contextId, handle)

    fun rollbackResimulate(handle: Long): Int =
        NetworkNative.rollbackResimulate(contextId, handle)

    fun rollbackConfirmedFrame(handle: Long): Long =
        NetworkNative.rollbackConfirmedFrame(contextId, handle)

    fun rollbackCurrentFrame(handle: Long): Long =
        NetworkNative.rollbackCurrentFrame(contextId, handle)

    fun rollbackCheckDesync(handle: Long, remoteHash: Long, frame: Long): Int =
        NetworkNative.rollbackCheckDesync(contextId, handle, remoteHash, frame)

    fun rpcCreate(timeoutMs: Long, maxPayload: Int): Long =
        NetworkNative.rpcCreate(contextId, timeoutMs, maxPayload)

    fun rpcDestroy(handle: Long): Int =
        NetworkNative.rpcDestroy(contextId, handle)

    fun rpcRegister(handle: Long, rpcId: Int, name: String, direction: Int): Int =
        NetworkNative.rpcRegister(contextId, handle, rpcId, name, direction)

    fun rpcCall(handle: Long, peerId: Long, rpcId: Int, payload: ByteArray): Long =
        NetworkNative.rpcCall(contextId, handle, peerId, rpcId, payload)

    fun rpcPoll(handle: Long, deltaSecs: Float): Int =
        NetworkNative.rpcPoll(contextId, handle, deltaSecs)

    fun rpcProcessIncoming(handle: Long, peerId: Long, data: ByteArray): Int =
        NetworkNative.rpcProcessIncoming(contextId, handle, peerId, data)

    fun rpcReceiveResponse(handle: Long, callId: Long): ByteArray =
        NetworkNative.rpcReceiveResponse(contextId, handle, callId)

    fun rpcDrainOne(handle: Long): ByteArray =
        NetworkNative.rpcDrainOne(contextId, handle)

}
