// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.PhysicsWorld2DNative
import com.goudengine.internal.GoudContextNative

class PhysicsWorld2D private constructor(private val contextId: Long) : AutoCloseable {

    companion object {
        fun create(gravityX: Float, gravityY: Float): PhysicsWorld2D {
            val ctx = GoudContextNative.create()
            require(ctx != 0L) { "Failed to create context for PhysicsWorld2D" }
            val status = PhysicsWorld2DNative.create(ctx, gravityX, gravityY)
            if (status != 0) {
                GoudContextNative.destroy(ctx)
                error("Failed to create PhysicsWorld2D (status $status)")
            }
            return PhysicsWorld2D(ctx)
        }
    }

    fun destroy(): Int {
        val status = PhysicsWorld2DNative.destroy(contextId)
        GoudContextNative.destroy(contextId)
        return status
    }

    fun setGravity(x: Float, y: Float): Int =
        PhysicsWorld2DNative.setGravity(contextId, x, y)

    fun addRigidBody(bodyType: Int, x: Float, y: Float, gravityScale: Float): Long =
        PhysicsWorld2DNative.addRigidBody(contextId, bodyType, x, y, gravityScale)

    fun addRigidBodyEx(bodyType: Int, x: Float, y: Float, gravityScale: Float, ccdEnabled: Boolean): Long =
        PhysicsWorld2DNative.addRigidBodyEx(contextId, bodyType, x, y, gravityScale, ccdEnabled)

    fun addCollider(bodyHandle: Long, shapeType: Int, width: Float, height: Float, radius: Float, friction: Float, restitution: Float): Long =
        PhysicsWorld2DNative.addCollider(contextId, bodyHandle, shapeType, width, height, radius, friction, restitution)

    fun addColliderEx(bodyHandle: Long, shapeType: Int, width: Float, height: Float, radius: Float, friction: Float, restitution: Float, isSensor: Boolean, layer: Int, mask: Int): Long =
        PhysicsWorld2DNative.addColliderEx(contextId, bodyHandle, shapeType, width, height, radius, friction, restitution, isSensor, layer, mask)

    fun removeBody(handle: Long): Int =
        PhysicsWorld2DNative.removeBody(contextId, handle)

    fun createJoint(bodyA: Long, bodyB: Long, kind: Int, anchorAx: Float, anchorAy: Float, anchorBx: Float, anchorBy: Float, axisX: Float, axisY: Float, hasLimits: Boolean, limitMin: Float, limitMax: Float, hasMotor: Boolean, motorTargetVelocity: Float, motorMaxForce: Float): Long =
        PhysicsWorld2DNative.createJoint(contextId, bodyA, bodyB, kind, anchorAx, anchorAy, anchorBx, anchorBy, axisX, axisY, hasLimits, limitMin, limitMax, hasMotor, motorTargetVelocity, motorMaxForce)

    fun removeJoint(handle: Long): Int =
        PhysicsWorld2DNative.removeJoint(contextId, handle)

    fun step(dt: Float): Int =
        PhysicsWorld2DNative.step(contextId, dt)

    fun getPosition(handle: Long): com.goudengine.types.Vec2 {
        val r = PhysicsWorld2DNative.getPosition(contextId, handle)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun getVelocity(handle: Long): com.goudengine.types.Vec2 {
        val r = PhysicsWorld2DNative.getVelocity(contextId, handle)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun setVelocity(handle: Long, vx: Float, vy: Float): Int =
        PhysicsWorld2DNative.setVelocity(contextId, handle, vx, vy)

    fun applyForce(handle: Long, fx: Float, fy: Float): Int =
        PhysicsWorld2DNative.applyForce(contextId, handle, fx, fy)

    fun applyImpulse(handle: Long, ix: Float, iy: Float): Int =
        PhysicsWorld2DNative.applyImpulse(contextId, handle, ix, iy)

    fun raycast(originX: Float, originY: Float, dirX: Float, dirY: Float, maxDist: Float): com.goudengine.types.Vec2 {
        val r = PhysicsWorld2DNative.raycast(contextId, originX, originY, dirX, dirY, maxDist)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun collisionEventsCount(): Int =
        PhysicsWorld2DNative.collisionEventsCount(contextId)

    fun collisionEventCount(): Int =
        PhysicsWorld2DNative.collisionEventCount(contextId)

    fun getGravity(): com.goudengine.types.Vec2 {
        val r = PhysicsWorld2DNative.getGravity(contextId)
        return com.goudengine.types.Vec2.fromNative(r)
    }

    fun setBodyGravityScale(handle: Long, scale: Float): Int =
        PhysicsWorld2DNative.setBodyGravityScale(contextId, handle, scale)

    fun getBodyGravityScale(handle: Long): Float =
        PhysicsWorld2DNative.getBodyGravityScale(contextId, handle)

    fun setColliderFriction(handle: Long, friction: Float): Int =
        PhysicsWorld2DNative.setColliderFriction(contextId, handle, friction)

    fun getColliderFriction(handle: Long): Float =
        PhysicsWorld2DNative.getColliderFriction(contextId, handle)

    fun setColliderRestitution(handle: Long, restitution: Float): Int =
        PhysicsWorld2DNative.setColliderRestitution(contextId, handle, restitution)

    fun getColliderRestitution(handle: Long): Float =
        PhysicsWorld2DNative.getColliderRestitution(contextId, handle)

    fun setTimestep(dt: Float): Int =
        PhysicsWorld2DNative.setTimestep(contextId, dt)

    fun getTimestep(): Float =
        PhysicsWorld2DNative.getTimestep(contextId)

    override fun close() { destroy() }
}
