// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

import com.goudengine.internal.PluginNative

class Plugin(private val contextId: Long) {

    fun register(pluginId: String): Int =
        PluginNative.register(contextId, pluginId)

    fun unregister(pluginId: String): Int =
        PluginNative.unregister(contextId, pluginId)

    fun isRegistered(pluginId: String): Boolean =
        PluginNative.isRegistered(contextId, pluginId)

    fun list(): String =
        PluginNative.list(contextId)

}
