// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

/** Rendering backend selection */
enum class RendererType(val value: Int) {
    Renderer2D(0),
    Renderer3D(1);

    companion object {
        fun fromValue(value: Int): RendererType? =
            entries.firstOrNull { it.value == value }
    }
}
