// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

enum class RenderBackendKind(val value: Int) {
    Wgpu(0),
    OpenGlLegacy(1);

    companion object {
        fun fromValue(value: Int): RenderBackendKind? =
            entries.firstOrNull { it.value == value }
    }
}
