// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.core

/** Native window backend selection */
enum class WindowBackendKind(val value: Int) {
    Winit(0),
    GlfwLegacy(1);

    companion object {
        fun fromValue(value: Int): WindowBackendKind? =
            entries.firstOrNull { it.value == value }
    }
}
