[package]
name = "goud_engine"
version = "0.1.0"
edition = "2021"


[dependencies]
cpal = "0.15.3"
egui = "0.29.1"
wgpu = "23.0.0"
winit = "0.30.5"

[lib]
name = "goud_engine"
path = "src/lib.rs"

[[bin]]
name = "goud_engine_bin"
path = "src/main.rs"
