// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
use crate::game::GoudGame;
use goud_engine::ffi::audio::controls::{
    goud_audio_active_count, goud_audio_cleanup_finished, goud_audio_get_channel_volume,
    goud_audio_get_global_volume, goud_audio_is_playing, goud_audio_pause, goud_audio_resume,
    goud_audio_set_channel_volume, goud_audio_set_global_volume, goud_audio_stop,
    goud_audio_stop_all,
};
use goud_engine::ffi::audio::playback::{
    goud_audio_play, goud_audio_play_on_channel, goud_audio_play_with_settings,
};
use napi::bindgen_prelude::*;
use napi_derive::napi;

// =============================================================================
// Audio methods on GoudGame
// =============================================================================

#[napi]
impl GoudGame {
    /// Plays audio from raw bytes on the default SFX channel.
    /// Returns a positive player ID on success, or a negative value on error.
    #[napi]
    pub fn audio_play(&self, data: Buffer) -> f64 {
        // SAFETY: Buffer provides valid pointer and length from napi.
        unsafe { goud_audio_play(self.context_id, data.as_ptr(), data.len()) as f64 }
    }

    /// Plays audio on a specific channel.
    /// Returns a positive player ID on success, or a negative value on error.
    #[napi]
    pub fn audio_play_on_channel(&self, data: Buffer, channel: u32) -> f64 {
        // SAFETY: Buffer provides valid pointer and length from napi.
        unsafe {
            goud_audio_play_on_channel(self.context_id, data.as_ptr(), data.len(), channel as u8)
                as f64
        }
    }

    /// Plays audio with full control over volume, speed, looping, and channel.
    /// Returns a positive player ID on success, or a negative value on error.
    #[napi]
    pub fn audio_play_with_settings(
        &self,
        data: Buffer,
        volume: f64,
        speed: f64,
        looping: bool,
        channel: u32,
    ) -> f64 {
        // SAFETY: Buffer provides valid pointer and length from napi.
        unsafe {
            goud_audio_play_with_settings(
                self.context_id,
                data.as_ptr(),
                data.len(),
                volume as f32,
                speed as f32,
                looping,
                channel as u8,
            ) as f64
        }
    }

    /// Stops audio playback for the given player ID.
    #[napi]
    pub fn audio_stop(&self, player_id: f64) -> i32 {
        goud_audio_stop(self.context_id, player_id as u64)
    }

    /// Pauses audio playback for the given player ID.
    #[napi]
    pub fn audio_pause(&self, player_id: f64) -> i32 {
        goud_audio_pause(self.context_id, player_id as u64)
    }

    /// Resumes audio playback for the given player ID.
    #[napi]
    pub fn audio_resume(&self, player_id: f64) -> i32 {
        goud_audio_resume(self.context_id, player_id as u64)
    }

    /// Stops all currently playing audio.
    #[napi]
    pub fn audio_stop_all(&self) -> i32 {
        goud_audio_stop_all(self.context_id)
    }

    /// Sets the global audio volume (0.0 to 1.0).
    #[napi]
    pub fn audio_set_global_volume(&self, volume: f64) -> i32 {
        goud_audio_set_global_volume(self.context_id, volume as f32)
    }

    /// Returns the current global audio volume.
    #[napi]
    pub fn audio_get_global_volume(&self) -> f64 {
        goud_audio_get_global_volume(self.context_id) as f64
    }

    /// Sets the volume for a specific audio channel.
    #[napi]
    pub fn audio_set_channel_volume(&self, channel: u32, volume: f64) -> i32 {
        goud_audio_set_channel_volume(self.context_id, channel as u8, volume as f32)
    }

    /// Returns the current volume for a specific audio channel.
    #[napi]
    pub fn audio_get_channel_volume(&self, channel: u32) -> f64 {
        goud_audio_get_channel_volume(self.context_id, channel as u8) as f64
    }

    /// Checks whether a specific player is currently playing.
    /// Returns 1 if playing, 0 if not, -1 on error.
    #[napi]
    pub fn audio_is_playing(&self, player_id: f64) -> i32 {
        goud_audio_is_playing(self.context_id, player_id as u64)
    }

    /// Returns the number of active audio players.
    #[napi]
    pub fn audio_active_count(&self) -> i32 {
        goud_audio_active_count(self.context_id)
    }

    /// Removes finished audio players from the manager.
    #[napi]
    pub fn audio_cleanup_finished(&self) -> i32 {
        goud_audio_cleanup_finished(self.context_id)
    }
}
