// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
use napi::bindgen_prelude::*;
use napi_derive::napi;

/// PLACEHOLDER entity bits: index=u32::MAX, generation=0.
const PLACEHOLDER_BITS: u64 = u32::MAX as u64;

#[napi]
pub struct Entity {
    /// Packed entity bits: (generation << 32) | index.
    pub(crate) bits: u64,
}

#[napi]
impl Entity {
    #[napi(constructor)]
    pub fn new(index: u32, generation: u32) -> Self {
        Self { bits: ((generation as u64) << 32) | (index as u64) }
    }

    #[napi(factory)]
    pub fn placeholder() -> Self {
        Self { bits: PLACEHOLDER_BITS }
    }

    #[napi(factory)]
    pub fn from_bits(bits: BigInt) -> Result<Self> {
        let (_, value, _) = bits.get_u64();
        Ok(Self { bits: value })
    }

    #[napi(getter)]
    pub fn index(&self) -> u32 { self.bits as u32 }

    #[napi(getter)]
    pub fn generation(&self) -> u32 { (self.bits >> 32) as u32 }

    #[napi(getter)]
    pub fn is_placeholder(&self) -> bool { self.bits == PLACEHOLDER_BITS }

    #[napi]
    pub fn to_bits(&self) -> BigInt { BigInt::from(self.bits) }

    #[napi]
    pub fn display(&self) -> String {
        let index = self.bits as u32;
        let gen = (self.bits >> 32) as u32;
        format!("Entity({}:{})", index, gen)
    }
}
