// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
use crate::components::{SpriteData, Transform2DData};
use crate::entity::Entity;
use goud_engine::ffi::collision::{
    goud_collision_aabb_aabb, goud_collision_aabb_overlap, goud_collision_circle_aabb,
    goud_collision_circle_circle, goud_collision_circle_overlap,
    goud_collision_distance, goud_collision_distance_squared,
    goud_collision_point_in_circle, goud_collision_point_in_rect, GoudContact,
};
use goud_engine::ffi::context::{GoudContextId, GOUD_INVALID_CONTEXT_ID};
use goud_engine::ffi::debug::{
    goud_debug_get_fps_stats, goud_debug_set_fps_overlay_corner,
    goud_debug_set_fps_overlay_enabled, goud_debug_set_fps_update_interval,
};
use goud_engine::sdk::debug_overlay::FpsStats;
use goud_engine::ffi::entity::{
    goud_entity_count, goud_entity_despawn, goud_entity_is_alive,
    goud_entity_spawn_batch, goud_entity_spawn_empty,
};
use goud_engine::ffi::scene::goud_scene_set_active;
use goud_engine::ffi::scene_loading::{goud_scene_load, goud_scene_unload};
use goud_engine::ffi::input::{
    goud_input_get_mouse_delta, goud_input_get_mouse_position,
    goud_input_get_scroll_delta, goud_input_key_just_pressed,
    goud_input_key_just_released, goud_input_key_pressed,
    goud_input_mouse_button_just_pressed, goud_input_mouse_button_just_released,
    goud_input_mouse_button_pressed,
    goud_input_map_action_key, goud_input_action_pressed,
    goud_input_action_just_pressed, goud_input_action_just_released,
};
use goud_engine::ffi::renderer::{
    goud_renderer_begin, goud_renderer_clear_depth, goud_renderer_disable_blending,
    goud_renderer_disable_depth_test, goud_renderer_draw_quad,
    goud_renderer_draw_sprite, goud_renderer_draw_sprite_rect,
    goud_renderer_draw_text,
    goud_renderer_enable_blending, goud_renderer_enable_depth_test,
    goud_renderer_end, goud_renderer_get_stats, goud_renderer_set_viewport,
    goud_texture_destroy, goud_texture_load,
    goud_font_destroy, goud_font_load,
    GoudRenderStats,
};
use goud_engine::ffi::renderer3d::{
    goud_renderer3d_add_light, goud_renderer3d_configure_fog,
    goud_renderer3d_configure_grid, goud_renderer3d_configure_skybox,
    goud_renderer3d_create_cube, goud_renderer3d_create_cylinder,
    goud_renderer3d_create_plane, goud_renderer3d_create_sphere,
    goud_renderer3d_destroy_object, goud_renderer3d_remove_light,
    goud_renderer3d_render, goud_renderer3d_set_camera_position,
    goud_renderer3d_set_camera_rotation, goud_renderer3d_set_fog_enabled,
    goud_renderer3d_set_grid_enabled, goud_renderer3d_set_object_position,
    goud_renderer3d_set_object_rotation, goud_renderer3d_set_object_scale,
    goud_renderer3d_update_light,
};
use goud_engine::ffi::animation::{
    goud_animation_clip_add_event, goud_animation_events_count,
    goud_animation_events_read, goud_animation_layer_add,
    goud_animation_layer_add_frame, goud_animation_layer_play,
    goud_animation_layer_reset, goud_animation_layer_set_clip,
    goud_animation_layer_set_weight, goud_animation_layer_stack_create,
};
use goud_engine::ffi::providers::{
    goud_provider_render_capabilities, goud_provider_physics_capabilities,
    goud_provider_audio_capabilities, goud_provider_input_capabilities,
    goud_provider_network_capabilities, goud_provider_check_hot_swap_shortcut,
};
use goud_engine::core::providers::types::{
    RenderCapabilities, PhysicsCapabilities, AudioCapabilities,
};
use goud_engine::core::providers::input_types::InputCapabilities;
use goud_engine::core::providers::network_types::NetworkCapabilities;
use goud_engine::ffi::window::{
    goud_window_clear, goud_window_create, goud_window_destroy,
    goud_window_get_delta_time, goud_window_get_size, goud_window_poll_events,
    goud_window_set_should_close, goud_window_should_close,
    goud_window_swap_buffers,
};
use napi::bindgen_prelude::*;
use napi_derive::napi;
use std::ffi::CString;

// =============================================================================
// GameConfig
// =============================================================================

#[napi(object)]
#[derive(Clone, Debug)]
pub struct GameConfig {
    pub title: Option<String>,
    pub width: Option<u32>,
    pub height: Option<u32>,
}

// =============================================================================
// RenderStats / Contact napi objects
// =============================================================================

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiRenderStats {
    pub draw_calls: u32,
    pub triangles: u32,
    pub texture_binds: u32,
    pub shader_binds: u32,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiContact {
    pub point_x: f64,
    pub point_y: f64,
    pub normal_x: f64,
    pub normal_y: f64,
    pub penetration: f64,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiFpsStats {
    pub current_fps: f64,
    pub min_fps: f64,
    pub max_fps: f64,
    pub avg_fps: f64,
    pub frame_time_ms: f64,
}

// =============================================================================
// Provider Capabilities napi objects
// =============================================================================

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiRenderCapabilities {
    pub max_texture_units: u32,
    pub max_texture_size: u32,
    pub supports_instancing: bool,
    pub supports_compute: bool,
    pub supports_msaa: bool,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiPhysicsCapabilities {
    pub supports_continuous_collision: bool,
    pub supports_joints: bool,
    pub max_bodies: u32,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiAudioCapabilities {
    pub supports_spatial: bool,
    pub max_channels: u32,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiInputCapabilities {
    pub supports_gamepad: bool,
    pub supports_touch: bool,
    pub max_gamepads: u32,
}

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiNetworkCapabilities {
    pub supports_hosting: bool,
    pub max_connections: u32,
    pub max_channels: u32,
    pub max_message_size: u32,
}

// =============================================================================
// GoudGame -- FFI-only, no Rust SDK access
// =============================================================================

#[napi]
pub struct GoudGame {
    context_id: GoudContextId,
    last_delta_time: f32,
    title: String,
    frame_count: u64,
    total_time: f64,
}

#[napi]
impl GoudGame {
    #[napi(constructor)]
    pub fn new(config: Option<GameConfig>) -> Result<Self> {
        let width = config.as_ref().and_then(|c| c.width).unwrap_or(800);
        let height = config.as_ref().and_then(|c| c.height).unwrap_or(600);
        let title_str = config
            .as_ref()
            .and_then(|c| c.title.clone())
            .unwrap_or_else(|| "GoudEngine".to_string());

        let c_title = CString::new(title_str.as_str())
            .map_err(|e| Error::from_reason(format!("Invalid title string: {}", e)))?;

        // SAFETY: CString guarantees a valid null-terminated pointer.
        let context_id = unsafe { goud_window_create(width, height, c_title.as_ptr()) };
        if context_id == GOUD_INVALID_CONTEXT_ID {
            return Err(Error::from_reason("Failed to create GLFW window"));
        }

        Ok(Self { context_id, last_delta_time: 0.0, title: title_str, frame_count: 0, total_time: 0.0 })
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    #[napi]
    pub fn should_close(&self) -> bool { goud_window_should_close(self.context_id) }

    #[napi]
    pub fn close(&self) { goud_window_set_should_close(self.context_id, true); }

    #[napi]
    pub fn destroy(&self) -> bool { goud_window_destroy(self.context_id) }

    // =========================================================================
    // Frame Management
    // =========================================================================

    #[napi]
    pub fn begin_frame(&mut self, r: Option<f64>, g: Option<f64>, b: Option<f64>, a: Option<f64>) {
        let dt = goud_window_poll_events(self.context_id);
        self.last_delta_time = dt;
        goud_window_clear(self.context_id,
            r.unwrap_or(0.0) as f32, g.unwrap_or(0.0) as f32,
            b.unwrap_or(0.0) as f32, a.unwrap_or(1.0) as f32);
        goud_renderer_begin(self.context_id);
        goud_renderer_enable_blending(self.context_id);
    }

    #[napi]
    pub fn end_frame(&self) {
        goud_renderer_end(self.context_id);
        goud_window_swap_buffers(self.context_id);
    }

    // =========================================================================
    // Rendering
    // =========================================================================

    #[napi]
    pub fn load_texture(&self, path: String) -> Result<f64> {
        let c_path = CString::new(path)
            .map_err(|e| Error::from_reason(format!("Invalid path: {}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        let handle = unsafe { goud_texture_load(self.context_id, c_path.as_ptr()) };
        Ok(handle as f64)
    }

    #[napi]
    pub fn destroy_texture(&self, handle: f64) -> bool {
        goud_texture_destroy(self.context_id, handle as u64)
    }

    #[napi]
    pub fn load_font(&self, path: String) -> Result<f64> {
        let c_path = CString::new(path)
            .map_err(|e| Error::from_reason(format!("Invalid path: {}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        let handle = unsafe { goud_font_load(self.context_id, c_path.as_ptr()) };
        Ok(handle as f64)
    }

    #[napi]
    pub fn destroy_font(&self, handle: f64) -> bool {
        goud_font_destroy(self.context_id, handle as u64)
    }

    #[napi]
    pub fn draw_text(&self, font_handle: f64, text: String, x: f64, y: f64,
                     font_size: Option<f64>, alignment: Option<u32>, max_width: Option<f64>,
                     line_spacing: Option<f64>, direction: Option<u32>,
                     r: Option<f64>, g: Option<f64>, b: Option<f64>, a: Option<f64>) -> Result<bool> {
        let c_text = CString::new(text)
            .map_err(|e| Error::from_reason(format!("Invalid text: {}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        Ok(unsafe {
            goud_renderer_draw_text(
                self.context_id,
                font_handle as u64,
                c_text.as_ptr(),
                x as f32,
                y as f32,
                font_size.unwrap_or(16.0) as f32,
                alignment.unwrap_or(0) as u8,
                max_width.unwrap_or(0.0) as f32,
                line_spacing.unwrap_or(1.0) as f32,
                direction.unwrap_or(0) as u8,
                r.unwrap_or(1.0) as f32,
                g.unwrap_or(1.0) as f32,
                b.unwrap_or(1.0) as f32,
                a.unwrap_or(1.0) as f32,
            )
        })
    }

    #[napi]
    pub fn draw_sprite(&self, texture: f64, x: f64, y: f64, w: f64, h: f64,
                       rotation: Option<f64>, r: Option<f64>, g: Option<f64>,
                       b: Option<f64>, a: Option<f64>) -> bool {
        goud_renderer_draw_sprite(self.context_id, texture as u64,
            x as f32, y as f32, w as f32, h as f32, rotation.unwrap_or(0.0) as f32,
            r.unwrap_or(1.0) as f32, g.unwrap_or(1.0) as f32,
            b.unwrap_or(1.0) as f32, a.unwrap_or(1.0) as f32)
    }

    #[napi]
    pub fn draw_sprite_rect(&self, texture: f64, x: f64, y: f64, w: f64, h: f64,
                            rotation: Option<f64>, src_x: f64, src_y: f64,
                            src_w: f64, src_h: f64, r: Option<f64>, g: Option<f64>,
                            b: Option<f64>, a: Option<f64>) -> bool {
        goud_renderer_draw_sprite_rect(self.context_id, texture as u64,
            x as f32, y as f32, w as f32, h as f32, rotation.unwrap_or(0.0) as f32,
            src_x as f32, src_y as f32, src_w as f32, src_h as f32,
            r.unwrap_or(1.0) as f32, g.unwrap_or(1.0) as f32,
            b.unwrap_or(1.0) as f32, a.unwrap_or(1.0) as f32)
    }

    #[napi]
    pub fn draw_quad(&self, x: f64, y: f64, w: f64, h: f64,
                     r: Option<f64>, g: Option<f64>, b: Option<f64>, a: Option<f64>) -> bool {
        goud_renderer_draw_quad(self.context_id,
            x as f32, y as f32, w as f32, h as f32,
            r.unwrap_or(1.0) as f32, g.unwrap_or(1.0) as f32,
            b.unwrap_or(1.0) as f32, a.unwrap_or(1.0) as f32)
    }

    #[napi]
    pub fn set_viewport(&self, x: i32, y: i32, width: u32, height: u32) {
        goud_renderer_set_viewport(self.context_id, x, y, width, height);
    }

    #[napi]
    pub fn enable_depth_test(&self) { goud_renderer_enable_depth_test(self.context_id); }
    #[napi]
    pub fn disable_depth_test(&self) { goud_renderer_disable_depth_test(self.context_id); }
    #[napi]
    pub fn clear_depth(&self) { goud_renderer_clear_depth(self.context_id); }
    #[napi]
    pub fn disable_blending(&self) { goud_renderer_disable_blending(self.context_id); }

    #[napi]
    pub fn get_render_stats(&self) -> NapiRenderStats {
        let mut stats = GoudRenderStats { draw_calls: 0, triangles: 0, texture_binds: 0, shader_binds: 0 };
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_renderer_get_stats(self.context_id, &mut stats) };
        NapiRenderStats { draw_calls: stats.draw_calls, triangles: stats.triangles, texture_binds: stats.texture_binds, shader_binds: stats.shader_binds }
    }

    // =========================================================================
    // Debug overlay
    // =========================================================================

    #[napi]
    pub fn get_fps_stats(&self) -> NapiFpsStats {
        let mut stats = FpsStats::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_debug_get_fps_stats(self.context_id, &mut stats) };
        NapiFpsStats {
            current_fps: stats.current_fps as f64,
            min_fps: stats.min_fps as f64,
            max_fps: stats.max_fps as f64,
            avg_fps: stats.avg_fps as f64,
            frame_time_ms: stats.frame_time_ms as f64,
        }
    }

    #[napi]
    pub fn set_fps_overlay_enabled(&self, enabled: bool) {
        goud_debug_set_fps_overlay_enabled(self.context_id, enabled);
    }

    #[napi]
    pub fn set_fps_update_interval(&self, interval: f64) {
        goud_debug_set_fps_update_interval(self.context_id, interval as f32);
    }

    #[napi]
    pub fn set_fps_overlay_corner(&self, corner: i32) {
        goud_debug_set_fps_overlay_corner(self.context_id, corner);
    }

    // =========================================================================
    // Provider Capabilities
    // =========================================================================

    #[napi]
    pub fn get_render_capabilities(&self) -> NapiRenderCapabilities {
        let mut caps = RenderCapabilities::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_provider_render_capabilities(self.context_id, &mut caps) };
        NapiRenderCapabilities {
            max_texture_units: caps.max_texture_units,
            max_texture_size: caps.max_texture_size,
            supports_instancing: caps.supports_instancing,
            supports_compute: caps.supports_compute,
            supports_msaa: caps.supports_msaa,
        }
    }

    #[napi]
    pub fn get_physics_capabilities(&self) -> NapiPhysicsCapabilities {
        let mut caps = PhysicsCapabilities::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_provider_physics_capabilities(self.context_id, &mut caps) };
        NapiPhysicsCapabilities {
            supports_continuous_collision: caps.supports_continuous_collision,
            supports_joints: caps.supports_joints,
            max_bodies: caps.max_bodies,
        }
    }

    #[napi]
    pub fn get_audio_capabilities(&self) -> NapiAudioCapabilities {
        let mut caps = AudioCapabilities::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_provider_audio_capabilities(self.context_id, &mut caps) };
        NapiAudioCapabilities {
            supports_spatial: caps.supports_spatial,
            max_channels: caps.max_channels,
        }
    }

    #[napi]
    pub fn get_input_capabilities(&self) -> NapiInputCapabilities {
        let mut caps = InputCapabilities::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_provider_input_capabilities(self.context_id, &mut caps) };
        NapiInputCapabilities {
            supports_gamepad: caps.supports_gamepad,
            supports_touch: caps.supports_touch,
            max_gamepads: caps.max_gamepads,
        }
    }

    #[napi]
    pub fn get_network_capabilities(&self) -> NapiNetworkCapabilities {
        let mut caps = NetworkCapabilities::default();
        // SAFETY: Passing a valid mutable reference as out-pointer.
        unsafe { goud_provider_network_capabilities(self.context_id, &mut caps) };
        NapiNetworkCapabilities {
            supports_hosting: caps.supports_hosting,
            max_connections: caps.max_connections,
            max_channels: caps.max_channels as u32,
            max_message_size: caps.max_message_size,
        }
    }

    /// Checks if the hot-swap shortcut (F5) was pressed and cycles render provider. Debug builds only.
    #[napi]
    pub fn check_hot_swap_shortcut(&self) -> bool {
        // SAFETY: context_id is a valid opaque handle obtained at construction.
        goud_provider_check_hot_swap_shortcut(self.context_id) != 0
    }

    // =========================================================================
    // Input
    // =========================================================================

    #[napi]
    pub fn is_key_pressed(&self, key: i32) -> bool { goud_input_key_pressed(self.context_id, key) }
    #[napi]
    pub fn is_key_just_pressed(&self, key: i32) -> bool { goud_input_key_just_pressed(self.context_id, key) }
    #[napi]
    pub fn is_key_just_released(&self, key: i32) -> bool { goud_input_key_just_released(self.context_id, key) }
    #[napi]
    pub fn is_mouse_button_pressed(&self, button: i32) -> bool { goud_input_mouse_button_pressed(self.context_id, button) }
    #[napi]
    pub fn is_mouse_button_just_pressed(&self, button: i32) -> bool { goud_input_mouse_button_just_pressed(self.context_id, button) }
    #[napi]
    pub fn is_mouse_button_just_released(&self, button: i32) -> bool { goud_input_mouse_button_just_released(self.context_id, button) }

    #[napi]
    pub fn get_mouse_position(&self) -> Vec<f64> {
        let (mut x, mut y) = (0.0f32, 0.0f32);
        // SAFETY: Passing valid mutable references as out-pointers.
        unsafe { goud_input_get_mouse_position(self.context_id, &mut x, &mut y) };
        vec![x as f64, y as f64]
    }

    #[napi]
    pub fn get_mouse_delta(&self) -> Vec<f64> {
        let (mut dx, mut dy) = (0.0f32, 0.0f32);
        // SAFETY: Passing valid mutable references as out-pointers.
        unsafe { goud_input_get_mouse_delta(self.context_id, &mut dx, &mut dy) };
        vec![dx as f64, dy as f64]
    }

    #[napi]
    pub fn get_scroll_delta(&self) -> Vec<f64> {
        let (mut dx, mut dy) = (0.0f32, 0.0f32);
        // SAFETY: Passing valid mutable references as out-pointers.
        unsafe { goud_input_get_scroll_delta(self.context_id, &mut dx, &mut dy) };
        vec![dx as f64, dy as f64]
    }

    #[napi]
    pub fn map_action_key(&self, action: String, key: i32) -> Result<bool> {
        let c = CString::new(action).map_err(|e| Error::from_reason(format!("{}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        Ok(unsafe { goud_input_map_action_key(self.context_id, c.as_ptr(), key) })
    }

    #[napi]
    pub fn is_action_pressed(&self, action: String) -> Result<bool> {
        let c = CString::new(action).map_err(|e| Error::from_reason(format!("{}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        Ok(unsafe { goud_input_action_pressed(self.context_id, c.as_ptr()) })
    }

    #[napi]
    pub fn is_action_just_pressed(&self, action: String) -> Result<bool> {
        let c = CString::new(action).map_err(|e| Error::from_reason(format!("{}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        Ok(unsafe { goud_input_action_just_pressed(self.context_id, c.as_ptr()) })
    }

    #[napi]
    pub fn is_action_just_released(&self, action: String) -> Result<bool> {
        let c = CString::new(action).map_err(|e| Error::from_reason(format!("{}", e)))?;
        // SAFETY: CString guarantees a valid null-terminated pointer.
        Ok(unsafe { goud_input_action_just_released(self.context_id, c.as_ptr()) })
    }

    // =========================================================================
    // Entity Operations (ECS) -- via FFI
    // =========================================================================

    #[napi]
    pub fn spawn_empty(&self) -> Entity {
        Entity { bits: goud_entity_spawn_empty(self.context_id) }
    }

    #[napi]
    pub fn spawn_batch(&self, count: u32) -> Vec<Entity> {
        let mut out = vec![0u64; count as usize];
        // SAFETY: out buffer is correctly sized for count u64 values.
        let n = unsafe { goud_entity_spawn_batch(self.context_id, count, out.as_mut_ptr()) };
        out.truncate(n as usize);
        out.into_iter().map(|bits| Entity { bits }).collect()
    }

    #[napi]
    pub fn despawn(&self, entity: &Entity) -> bool {
        goud_entity_despawn(self.context_id, entity.bits).success
    }

    #[napi]
    pub fn entity_count(&self) -> u32 { goud_entity_count(self.context_id) }

    #[napi]
    pub fn is_alive(&self, entity: &Entity) -> bool {
        goud_entity_is_alive(self.context_id, entity.bits)
    }

    // =========================================================================
    // Scene Management Wrappers
    // =========================================================================

    #[napi]
    pub fn load_scene(&self, name: String, json: String) -> u32 {
        let name_bytes = name.as_bytes();
        let json_bytes = json.as_bytes();
        // SAFETY: String byte pointers are valid for their respective lengths.
        unsafe {
            goud_scene_load(
                self.context_id,
                name_bytes.as_ptr(),
                name_bytes.len() as u32,
                json_bytes.as_ptr(),
                json_bytes.len() as u32,
            )
        }
    }

    #[napi]
    pub fn unload_scene(&self, name: String) -> bool {
        let name_bytes = name.as_bytes();
        // SAFETY: name_bytes pointer is valid for name_bytes.len() bytes.
        unsafe {
            goud_scene_unload(
                self.context_id,
                name_bytes.as_ptr(),
                name_bytes.len() as u32,
            )
            .success
        }
    }

    #[napi]
    pub fn set_active_scene(&self, scene_id: u32, active: bool) -> bool {
        goud_scene_set_active(self.context_id, scene_id, active).success
    }

    // =========================================================================
    // Transform2D Component -- via FFI context registry
    // =========================================================================

    #[napi]
    pub fn add_transform2d(&self, entity: &Entity, data: Transform2DData) {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Transform2D;
        use goud_engine::core::math::Vec2;
        let mut reg = get_context_registry().lock().unwrap();
        if let Some(ctx) = reg.get_mut(self.context_id) {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            ctx.world_mut().insert(e, Transform2D {
                position: Vec2::new(data.position_x as f32, data.position_y as f32),
                rotation: data.rotation as f32,
                scale: Vec2::new(data.scale_x as f32, data.scale_y as f32),
            });
        }
    }

    #[napi]
    pub fn get_transform2d(&self, entity: &Entity) -> Option<Transform2DData> {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Transform2D;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).and_then(|ctx| {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            ctx.world().get::<Transform2D>(e).map(|t| Transform2DData {
                position_x: t.position.x as f64, position_y: t.position.y as f64,
                rotation: t.rotation as f64, scale_x: t.scale.x as f64, scale_y: t.scale.y as f64,
            })
        })
    }

    #[napi]
    pub fn set_transform2d(&self, entity: &Entity, data: Transform2DData) {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Transform2D;
        let mut reg = get_context_registry().lock().unwrap();
        if let Some(ctx) = reg.get_mut(self.context_id) {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            if let Some(t) = ctx.world_mut().get_mut::<Transform2D>(e) {
                t.position.x = data.position_x as f32; t.position.y = data.position_y as f32;
                t.rotation = data.rotation as f32;
                t.scale.x = data.scale_x as f32; t.scale.y = data.scale_y as f32;
            }
        }
    }

    #[napi]
    pub fn has_transform2d(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Transform2D;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).is_some_and(|ctx| {
            ctx.world().has::<Transform2D>(goud_engine::ecs::Entity::from_bits(entity.bits))
        })
    }

    #[napi]
    pub fn remove_transform2d(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Transform2D;
        let mut reg = get_context_registry().lock().unwrap();
        reg.get_mut(self.context_id).is_some_and(|ctx| {
            ctx.world_mut().remove::<Transform2D>(goud_engine::ecs::Entity::from_bits(entity.bits)).is_some()
        })
    }

    // =========================================================================
    // Sprite Component -- via FFI context registry
    // =========================================================================

    #[napi]
    pub fn add_sprite(&self, entity: &Entity, data: SpriteData) {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Sprite;
        use goud_engine::core::math::{Color, Rect, Vec2};
        let mut reg = get_context_registry().lock().unwrap();
        if let Some(ctx) = reg.get_mut(self.context_id) {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            ctx.world_mut().insert(e, Sprite {
                color: Color::rgba(data.color.r as f32, data.color.g as f32, data.color.b as f32, data.color.a as f32),
                flip_x: data.flip_x, flip_y: data.flip_y,
                anchor: Vec2::new(data.anchor_x as f32, data.anchor_y as f32),
                custom_size: match (data.custom_width, data.custom_height) {
                    (Some(w), Some(h)) => Some(Vec2::new(w as f32, h as f32)), _ => None,
                },
                source_rect: match (data.source_rect_x, data.source_rect_y, data.source_rect_width, data.source_rect_height) {
                    (Some(x), Some(y), Some(w), Some(h)) => Some(Rect::new(x as f32, y as f32, w as f32, h as f32)), _ => None,
                },
                ..Default::default()
            });
        }
    }

    #[napi]
    pub fn get_sprite(&self, entity: &Entity) -> Option<SpriteData> {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Sprite;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).and_then(|ctx| {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            ctx.world().get::<Sprite>(e).map(|s| {
                let (cw, ch) = s.custom_size.map_or((None, None), |sz| (Some(sz.x as f64), Some(sz.y as f64)));
                let (sx, sy, sw, sh) = s.source_rect.map_or((None,None,None,None), |r| (Some(r.x as f64), Some(r.y as f64), Some(r.width as f64), Some(r.height as f64)));
                SpriteData {
                    color: crate::types::Color { r: s.color.r as f64, g: s.color.g as f64, b: s.color.b as f64, a: s.color.a as f64 },
                    flip_x: s.flip_x, flip_y: s.flip_y,
                    anchor_x: s.anchor.x as f64, anchor_y: s.anchor.y as f64,
                    custom_width: cw, custom_height: ch,
                    source_rect_x: sx, source_rect_y: sy, source_rect_width: sw, source_rect_height: sh,
                }
            })
        })
    }

    #[napi]
    pub fn set_sprite(&self, entity: &Entity, data: SpriteData) {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Sprite;
        use goud_engine::core::math::{Color, Rect, Vec2};
        let mut reg = get_context_registry().lock().unwrap();
        if let Some(ctx) = reg.get_mut(self.context_id) {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            if let Some(s) = ctx.world_mut().get_mut::<Sprite>(e) {
                s.color = Color::rgba(data.color.r as f32, data.color.g as f32, data.color.b as f32, data.color.a as f32);
                s.flip_x = data.flip_x; s.flip_y = data.flip_y;
                s.anchor = Vec2::new(data.anchor_x as f32, data.anchor_y as f32);
                s.custom_size = match (data.custom_width, data.custom_height) { (Some(w), Some(h)) => Some(Vec2::new(w as f32, h as f32)), _ => None };
                s.source_rect = match (data.source_rect_x, data.source_rect_y, data.source_rect_width, data.source_rect_height) {
                    (Some(x), Some(y), Some(w), Some(h)) => Some(Rect::new(x as f32, y as f32, w as f32, h as f32)), _ => None };
            }
        }
    }

    #[napi]
    pub fn has_sprite(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Sprite;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).is_some_and(|ctx| {
            ctx.world().has::<Sprite>(goud_engine::ecs::Entity::from_bits(entity.bits))
        })
    }

    #[napi]
    pub fn remove_sprite(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Sprite;
        let mut reg = get_context_registry().lock().unwrap();
        reg.get_mut(self.context_id).is_some_and(|ctx| {
            ctx.world_mut().remove::<Sprite>(goud_engine::ecs::Entity::from_bits(entity.bits)).is_some()
        })
    }

    // =========================================================================
    // Name Component -- via FFI context registry
    // =========================================================================

    #[napi]
    pub fn add_name(&self, entity: &Entity, name: String) {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Name;
        let mut reg = get_context_registry().lock().unwrap();
        if let Some(ctx) = reg.get_mut(self.context_id) {
            let e = goud_engine::ecs::Entity::from_bits(entity.bits);
            ctx.world_mut().insert(e, Name::new(&name));
        }
    }

    #[napi]
    pub fn get_name(&self, entity: &Entity) -> Option<String> {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Name;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).and_then(|ctx| {
            ctx.world().get::<Name>(goud_engine::ecs::Entity::from_bits(entity.bits)).map(|n| n.as_str().to_string())
        })
    }

    #[napi]
    pub fn has_name(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Name;
        let reg = get_context_registry().lock().unwrap();
        reg.get(self.context_id).is_some_and(|ctx| {
            ctx.world().has::<Name>(goud_engine::ecs::Entity::from_bits(entity.bits))
        })
    }

    #[napi]
    pub fn remove_name(&self, entity: &Entity) -> bool {
        use goud_engine::ffi::context::get_context_registry;
        use goud_engine::ecs::components::Name;
        let mut reg = get_context_registry().lock().unwrap();
        reg.get_mut(self.context_id).is_some_and(|ctx| {
            ctx.world_mut().remove::<Name>(goud_engine::ecs::Entity::from_bits(entity.bits)).is_some()
        })
    }

    // =========================================================================
    // Collision -- via FFI (no context needed)
    // =========================================================================

    #[napi]
    pub fn collision_aabb_aabb(&self,
        ca_x: f64, ca_y: f64, hw_a: f64, hh_a: f64,
        cb_x: f64, cb_y: f64, hw_b: f64, hh_b: f64,
    ) -> Option<NapiContact> {
        let mut contact = std::mem::MaybeUninit::<GoudContact>::uninit();
        // SAFETY: Passing valid pointer to uninitialized memory for out-param.
        let hit = unsafe { goud_collision_aabb_aabb(
            ca_x as f32, ca_y as f32, hw_a as f32, hh_a as f32,
            cb_x as f32, cb_y as f32, hw_b as f32, hh_b as f32,
            contact.as_mut_ptr()) };
        if hit {
            // SAFETY: goud_collision_aabb_aabb wrote into contact on success.
            let c = unsafe { contact.assume_init() };
            Some(NapiContact { point_x: c.point_x as f64, point_y: c.point_y as f64,
                normal_x: c.normal_x as f64, normal_y: c.normal_y as f64, penetration: c.penetration as f64 })
        } else { None }
    }

    #[napi]
    pub fn collision_circle_circle(&self,
        ca_x: f64, ca_y: f64, ra: f64, cb_x: f64, cb_y: f64, rb: f64,
    ) -> Option<NapiContact> {
        let mut contact = std::mem::MaybeUninit::<GoudContact>::uninit();
        // SAFETY: Passing valid pointer to uninitialized memory for out-param.
        let hit = unsafe { goud_collision_circle_circle(
            ca_x as f32, ca_y as f32, ra as f32, cb_x as f32, cb_y as f32, rb as f32,
            contact.as_mut_ptr()) };
        if hit {
            // SAFETY: goud_collision_circle_circle wrote into contact on success.
            let c = unsafe { contact.assume_init() };
            Some(NapiContact { point_x: c.point_x as f64, point_y: c.point_y as f64,
                normal_x: c.normal_x as f64, normal_y: c.normal_y as f64, penetration: c.penetration as f64 })
        } else { None }
    }

    #[napi]
    pub fn collision_circle_aabb(&self,
        cx: f64, cy: f64, cr: f64, bx: f64, by: f64, bhw: f64, bhh: f64,
    ) -> Option<NapiContact> {
        let mut contact = std::mem::MaybeUninit::<GoudContact>::uninit();
        // SAFETY: Passing valid pointer to uninitialized memory for out-param.
        let hit = unsafe { goud_collision_circle_aabb(
            cx as f32, cy as f32, cr as f32, bx as f32, by as f32, bhw as f32, bhh as f32,
            contact.as_mut_ptr()) };
        if hit {
            // SAFETY: goud_collision_circle_aabb wrote into contact on success.
            let c = unsafe { contact.assume_init() };
            Some(NapiContact { point_x: c.point_x as f64, point_y: c.point_y as f64,
                normal_x: c.normal_x as f64, normal_y: c.normal_y as f64, penetration: c.penetration as f64 })
        } else { None }
    }

    #[napi]
    pub fn point_in_rect(&self, px: f64, py: f64, rx: f64, ry: f64, rw: f64, rh: f64) -> bool {
        goud_collision_point_in_rect(px as f32, py as f32, rx as f32, ry as f32, rw as f32, rh as f32)
    }
    #[napi]
    pub fn point_in_circle(&self, px: f64, py: f64, cx: f64, cy: f64, cr: f64) -> bool {
        goud_collision_point_in_circle(px as f32, py as f32, cx as f32, cy as f32, cr as f32)
    }
    #[napi]
    pub fn aabb_overlap(&self, ax1: f64, ay1: f64, ax2: f64, ay2: f64, bx1: f64, by1: f64, bx2: f64, by2: f64) -> bool {
        goud_collision_aabb_overlap(ax1 as f32, ay1 as f32, ax2 as f32, ay2 as f32, bx1 as f32, by1 as f32, bx2 as f32, by2 as f32)
    }
    #[napi]
    pub fn circle_overlap(&self, x1: f64, y1: f64, r1: f64, x2: f64, y2: f64, r2: f64) -> bool {
        goud_collision_circle_overlap(x1 as f32, y1 as f32, r1 as f32, x2 as f32, y2 as f32, r2 as f32)
    }
    #[napi]
    pub fn distance(&self, x1: f64, y1: f64, x2: f64, y2: f64) -> f64 {
        goud_collision_distance(x1 as f32, y1 as f32, x2 as f32, y2 as f32) as f64
    }
    #[napi]
    pub fn distance_squared(&self, x1: f64, y1: f64, x2: f64, y2: f64) -> f64 {
        goud_collision_distance_squared(x1 as f32, y1 as f32, x2 as f32, y2 as f32) as f64
    }

    // =========================================================================
    // 3D Renderer -- via FFI
    // =========================================================================

    #[napi]
    pub fn create_cube(&self, texture_id: u32, width: f64, height: f64, depth: f64) -> u32 {
        goud_renderer3d_create_cube(self.context_id, texture_id, width as f32, height as f32, depth as f32)
    }
    #[napi]
    pub fn create_plane(&self, texture_id: u32, width: f64, depth: f64) -> u32 {
        goud_renderer3d_create_plane(self.context_id, texture_id, width as f32, depth as f32)
    }
    #[napi]
    pub fn create_sphere(&self, texture_id: u32, diameter: f64, segments: u32) -> u32 {
        goud_renderer3d_create_sphere(self.context_id, texture_id, diameter as f32, segments)
    }
    #[napi]
    pub fn create_cylinder(&self, texture_id: u32, radius: f64, height: f64, segments: u32) -> u32 {
        goud_renderer3d_create_cylinder(self.context_id, texture_id, radius as f32, height as f32, segments)
    }
    #[napi]
    pub fn set_object_position(&self, id: u32, x: f64, y: f64, z: f64) -> bool {
        goud_renderer3d_set_object_position(self.context_id, id, x as f32, y as f32, z as f32)
    }
    #[napi]
    pub fn set_object_rotation(&self, id: u32, x: f64, y: f64, z: f64) -> bool {
        goud_renderer3d_set_object_rotation(self.context_id, id, x as f32, y as f32, z as f32)
    }
    #[napi]
    pub fn set_object_scale(&self, id: u32, x: f64, y: f64, z: f64) -> bool {
        goud_renderer3d_set_object_scale(self.context_id, id, x as f32, y as f32, z as f32)
    }
    #[napi]
    pub fn destroy_object(&self, id: u32) -> bool {
        goud_renderer3d_destroy_object(self.context_id, id)
    }
    #[napi]
    pub fn add_light(&self, lt: i32, px: f64, py: f64, pz: f64, dx: f64, dy: f64, dz: f64,
                     r: f64, g: f64, b: f64, intensity: f64, range: f64, spot_angle: f64) -> u32 {
        goud_renderer3d_add_light(self.context_id, lt,
            px as f32, py as f32, pz as f32, dx as f32, dy as f32, dz as f32,
            r as f32, g as f32, b as f32, intensity as f32, range as f32, spot_angle as f32)
    }
    #[napi]
    pub fn update_light(&self, lid: u32, lt: i32, px: f64, py: f64, pz: f64, dx: f64, dy: f64, dz: f64,
                        r: f64, g: f64, b: f64, intensity: f64, range: f64, spot_angle: f64) -> bool {
        goud_renderer3d_update_light(self.context_id, lid, lt,
            px as f32, py as f32, pz as f32, dx as f32, dy as f32, dz as f32,
            r as f32, g as f32, b as f32, intensity as f32, range as f32, spot_angle as f32)
    }
    #[napi]
    pub fn remove_light(&self, lid: u32) -> bool { goud_renderer3d_remove_light(self.context_id, lid) }
    #[napi]
    pub fn set_camera_position_3d(&self, x: f64, y: f64, z: f64) -> bool {
        goud_renderer3d_set_camera_position(self.context_id, x as f32, y as f32, z as f32)
    }
    #[napi]
    pub fn set_camera_rotation_3d(&self, pitch: f64, yaw: f64, roll: f64) -> bool {
        goud_renderer3d_set_camera_rotation(self.context_id, pitch as f32, yaw as f32, roll as f32)
    }
    #[napi]
    pub fn configure_grid(&self, enabled: bool, size: f64, divisions: u32) -> bool {
        goud_renderer3d_configure_grid(self.context_id, enabled, size as f32, divisions)
    }
    #[napi]
    pub fn set_grid_enabled(&self, enabled: bool) -> bool { goud_renderer3d_set_grid_enabled(self.context_id, enabled) }
    #[napi]
    pub fn configure_skybox(&self, enabled: bool, r: f64, g: f64, b: f64, a: f64) -> bool {
        goud_renderer3d_configure_skybox(self.context_id, enabled, r as f32, g as f32, b as f32, a as f32)
    }
    #[napi]
    pub fn configure_fog(&self, enabled: bool, r: f64, g: f64, b: f64, density: f64) -> bool {
        goud_renderer3d_configure_fog(self.context_id, enabled, r as f32, g as f32, b as f32, density as f32)
    }
    #[napi]
    pub fn set_fog_enabled(&self, enabled: bool) -> bool { goud_renderer3d_set_fog_enabled(self.context_id, enabled) }
    #[napi]
    pub fn render_3d(&self) -> bool { goud_renderer3d_render(self.context_id) }

    // =========================================================================
    // Timing / Stats (getters)
    // =========================================================================

    #[napi(getter)]
    pub fn delta_time(&self) -> f64 { self.last_delta_time as f64 }

    #[napi(getter)]
    pub fn fps(&self) -> f64 {
        if self.last_delta_time > 0.0 { (1.0 / self.last_delta_time) as f64 } else { 0.0 }
    }

    #[napi]
    pub fn update_frame(&mut self, dt: f64) {
        self.last_delta_time = dt as f32;
        self.frame_count += 1;
        self.total_time += dt;
    }

    #[napi(getter)]
    pub fn title(&self) -> String { self.title.clone() }

    #[napi(getter)]
    pub fn frame_count(&self) -> u32 { self.frame_count as u32 }

    #[napi(getter)]
    pub fn total_time(&self) -> f64 { self.total_time }

    #[napi(getter)]
    pub fn window_width(&self) -> u32 {
        let (mut w, mut h) = (0u32, 0u32);
        // SAFETY: Passing valid mutable references as out-pointers.
        unsafe { goud_window_get_size(self.context_id, &mut w, &mut h) };
        w
    }

    #[napi(getter)]
    pub fn window_height(&self) -> u32 {
        let (mut w, mut h) = (0u32, 0u32);
        // SAFETY: Passing valid mutable references as out-pointers.
        unsafe { goud_window_get_size(self.context_id, &mut w, &mut h) };
        h
    }

    #[napi(getter)]
    pub fn context_valid(&self) -> bool { self.context_id != GOUD_INVALID_CONTEXT_ID }

    /// Returns the raw FFI delta time from the last poll_events call.
    #[napi(getter)]
    pub fn ffi_delta_time(&self) -> f64 { goud_window_get_delta_time(self.context_id) as f64 }

    // =========================================================================
    // Animation Layer Stack
    // =========================================================================

    #[napi]
    pub fn animation_layer_stack_create(&self, entity: &Entity) -> i32 {
        goud_animation_layer_stack_create(self.context_id, entity.bits)
    }

    #[napi]
    pub fn animation_layer_add(&self, entity: &Entity, name: String, blend_mode: u32) -> Result<i32> {
        let bytes = name.as_bytes();
        // SAFETY: bytes pointer is valid for bytes.len() bytes (Rust String guarantee).
        Ok(unsafe { goud_animation_layer_add(self.context_id, entity.bits, bytes.as_ptr(), bytes.len() as u32, blend_mode) })
    }

    #[napi]
    pub fn animation_layer_set_weight(&self, entity: &Entity, layer_index: u32, weight: f64) -> i32 {
        goud_animation_layer_set_weight(self.context_id, entity.bits, layer_index, weight as f32)
    }

    #[napi]
    pub fn animation_layer_play(&self, entity: &Entity, layer_index: u32) -> i32 {
        goud_animation_layer_play(self.context_id, entity.bits, layer_index)
    }

    #[napi]
    pub fn animation_layer_set_clip(&self, entity: &Entity, layer_index: u32, frame_count: u32, frame_duration: f64, mode: u32) -> i32 {
        goud_animation_layer_set_clip(self.context_id, entity.bits, layer_index, frame_count, frame_duration as f32, mode)
    }

    #[napi]
    pub fn animation_layer_add_frame(&self, entity: &Entity, layer_index: u32, x: f64, y: f64, w: f64, h: f64) -> i32 {
        goud_animation_layer_add_frame(self.context_id, entity.bits, layer_index, x as f32, y as f32, w as f32, h as f32)
    }

    #[napi]
    pub fn animation_layer_reset(&self, entity: &Entity, layer_index: u32) -> i32 {
        goud_animation_layer_reset(self.context_id, entity.bits, layer_index)
    }

    // =========================================================================
    // Animation Events
    // =========================================================================

    #[napi]
    pub fn animation_clip_add_event(&self, entity: &Entity, frame_index: u32, name: String,
                                     payload_type: u32, payload_int: i32, payload_float: f64,
                                     payload_string: Option<String>) -> Result<i32> {
        let name_bytes = name.as_bytes();
        let ps = payload_string.unwrap_or_default();
        let ps_bytes = ps.as_bytes();
        // SAFETY: String byte pointers are valid for their respective lengths.
        Ok(unsafe { goud_animation_clip_add_event(
            self.context_id, entity.bits, frame_index,
            name_bytes.as_ptr(), name_bytes.len() as u32,
            payload_type, payload_int, payload_float as f32,
            ps_bytes.as_ptr(), ps_bytes.len() as u32,
        ) })
    }

    #[napi]
    pub fn animation_events_count(&self) -> i32 {
        goud_animation_events_count(self.context_id)
    }

    #[napi]
    pub fn animation_events_read(&self, index: u32) -> Result<NapiAnimationEventData> {
        let mut entity: u64 = 0;
        let mut name_ptr: *const u8 = std::ptr::null();
        let mut name_len: u32 = 0;
        let mut frame: u32 = 0;
        let mut payload_type: u32 = 0;
        let mut payload_int: i32 = 0;
        let mut payload_float: f32 = 0.0;
        let mut payload_str_ptr: *const u8 = std::ptr::null();
        let mut payload_str_len: u32 = 0;
        // SAFETY: All out-pointers point to valid stack-allocated memory.
        let rc = unsafe { goud_animation_events_read(
            self.context_id, index,
            &mut entity, &mut name_ptr, &mut name_len, &mut frame,
            &mut payload_type, &mut payload_int, &mut payload_float,
            &mut payload_str_ptr, &mut payload_str_len,
        ) };
        if rc != 0 {
            return Err(Error::from_reason(format!("animation_events_read failed: {}", rc)));
        }
        // SAFETY: FFI guarantees name_ptr is valid for name_len bytes on success.
        let name = unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(name_ptr, name_len as usize)) }.to_string();
        let payload_string = if payload_type == 3 && !payload_str_ptr.is_null() {
            // SAFETY: FFI guarantees payload_str_ptr is valid for payload_str_len bytes when type==3.
            unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(payload_str_ptr, payload_str_len as usize)) }.to_string()
        } else {
            String::new()
        };
        Ok(NapiAnimationEventData { entity: entity as i64, name, frame_index: frame, payload_type, payload_int, payload_float: payload_float as f64, payload_string })
    }
}

// =============================================================================
// NapiAnimationEventData
// =============================================================================

#[napi(object)]
#[derive(Clone, Debug)]
pub struct NapiAnimationEventData {
    pub entity: i64,
    pub name: String,
    pub frame_index: u32,
    pub payload_type: u32,
    pub payload_int: i32,
    pub payload_float: f64,
    pub payload_string: String,
}

// =============================================================================
// NativeEngineConfig -- Builder for GoudGame via FFI
// =============================================================================

#[napi(js_name = "NativeEngineConfig")]
pub struct NativeEngineConfig {
    handle: *mut std::ffi::c_void,
    title: String,
}

#[napi]
impl NativeEngineConfig {
    #[napi(constructor)]
    pub fn new() -> Self {
        let handle = goud_engine::ffi::engine_config::goud_engine_config_create();
        Self { handle, title: String::new() }
    }

    #[napi]
    pub fn set_title(&mut self, title: String) -> bool {
        if self.handle.is_null() { return false; }
        let c_title = match CString::new(title.clone()) {
            Ok(s) => s,
            Err(_) => return false,
        };
        self.title = title;
        // SAFETY: handle is valid, CString guarantees null-terminated.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_title(self.handle, c_title.as_ptr()) }
    }

    #[napi]
    pub fn set_size(&self, width: u32, height: u32) -> bool {
        if self.handle.is_null() { return false; }
        // SAFETY: handle is valid.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_size(self.handle, width, height) }
    }

    #[napi]
    pub fn set_vsync(&self, enabled: bool) -> bool {
        if self.handle.is_null() { return false; }
        // SAFETY: handle is valid.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_vsync(self.handle, enabled) }
    }

    #[napi]
    pub fn set_fullscreen(&self, enabled: bool) -> bool {
        if self.handle.is_null() { return false; }
        // SAFETY: handle is valid.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_fullscreen(self.handle, enabled) }
    }

    #[napi]
    pub fn set_target_fps(&self, fps: u32) -> bool {
        if self.handle.is_null() { return false; }
        // SAFETY: handle is valid.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_target_fps(self.handle, fps) }
    }

    #[napi]
    pub fn set_fps_overlay(&self, enabled: bool) -> bool {
        if self.handle.is_null() { return false; }
        // SAFETY: handle is valid.
        unsafe { goud_engine::ffi::engine_config::goud_engine_config_set_fps_overlay(self.handle, enabled) }
    }

    #[napi]
    pub fn build(&mut self) -> Result<GoudGame> {
        if self.handle.is_null() {
            return Err(Error::from_reason("EngineConfig already consumed"));
        }
        let handle = self.handle;
        self.handle = std::ptr::null_mut();
        // SAFETY: handle is valid and we take ownership.
        let context_id = unsafe { goud_engine::ffi::engine_config::goud_engine_create(handle) };
        if context_id == GOUD_INVALID_CONTEXT_ID {
            return Err(Error::from_reason("Failed to create engine from config"));
        }
        Ok(GoudGame {
            context_id,
            last_delta_time: 0.0,
            title: std::mem::take(&mut self.title),
            frame_count: 0,
            total_time: 0.0,
        })
    }

    #[napi]
    pub fn destroy(&mut self) {
        if !self.handle.is_null() {
            // SAFETY: handle is valid and we own it.
            unsafe { goud_engine::ffi::engine_config::goud_engine_config_destroy(self.handle) };
            self.handle = std::ptr::null_mut();
        }
    }
}
