// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
#[allow(dead_code)]
#[path = "audio.g.rs"]
mod audio;
#[allow(dead_code)]
#[path = "components.g.rs"]
mod components;
#[path = "entity.g.rs"]
mod entity;
#[path = "game.g.rs"]
mod game;
#[allow(dead_code)]
#[path = "types.g.rs"]
mod types;
