// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "nativelib";



        [DllImport(__DllName, EntryPoint = "create_point", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Point* create_point(double x, double y);

        [DllImport(__DllName, EntryPoint = "get_x", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double get_x(Point* point);

        [DllImport(__DllName, EntryPoint = "get_y", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double get_y(Point* point);

        [DllImport(__DllName, EntryPoint = "free_point", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_point(void* point);

        [DllImport(__DllName, EntryPoint = "create_game", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Game* create_game(void* window_builder);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Point
    {
        public double x;
        public double y;
    }



}
