// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
import XCTest
@testable import GoudEngine

final class EnumTests: XCTestCase {

    func testKeyRawValues() {
        // Spot-check a few well-known key codes
        XCTAssertEqual(Key.SPACE.rawValue, 32)
        XCTAssertEqual(Key.ESCAPE.rawValue, 256)
        XCTAssertEqual(Key.ENTER.rawValue, 257)
    }

    func testMouseButtonRawValues() {
        XCTAssertEqual(MouseButton.LEFT.rawValue, 0)
        XCTAssertEqual(MouseButton.RIGHT.rawValue, 1)
        XCTAssertEqual(MouseButton.MIDDLE.rawValue, 2)
    }

    func testRendererTypeRawValues() {
        XCTAssertEqual(RendererType.RENDERER2_D.rawValue, 0)
        XCTAssertEqual(RendererType.RENDERER3_D.rawValue, 1)
    }

    func testBodyTypeRawValues() {
        XCTAssertEqual(BodyType.DYNAMIC.rawValue, 0)
        XCTAssertEqual(BodyType.STATIC.rawValue, 1)
        XCTAssertEqual(BodyType.KINEMATIC.rawValue, 2)
    }

    func testKeyFromRawValue() {
        let key = Key(rawValue: 32)
        XCTAssertNotNil(key)
        XCTAssertEqual(key, Key.SPACE)
    }

    func testInvalidKeyRawValue() {
        let key = Key(rawValue: -999)
        XCTAssertNil(key)
    }
}
