"""Shared utilities for GoudEngine SDK code generators.

All generators import this module to load the schema, apply naming
conventions, and map SDK types to language-specific types.
"""

import json
import os
import re
import textwrap
from pathlib import Path

CODEGEN_DIR = Path(__file__).parent
ROOT_DIR = CODEGEN_DIR.parent
SDKS_DIR = ROOT_DIR / "sdks"

HEADER_COMMENT = "This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT."


def resolve_mixins(schema: dict) -> dict:
    """Expand mixin references in tool method lists.

    Tool methods may contain ``{"$ref": "MixinName", "name": "methodName"}``
    stubs.  This function replaces each stub with the full method definition
    from the referenced mixin, preserving the ordering of the tool's method
    array.  The ``mixins`` top-level key is removed after resolution so that
    generators see a flat, fully-resolved schema.
    """
    mixins = schema.get("mixins", {})
    if not mixins:
        return schema

    # Build a lookup: mixin_name -> {method_name -> method_def}
    mixin_lookup: dict[str, dict[str, dict]] = {}
    for mixin_name, mixin_def in mixins.items():
        mixin_lookup[mixin_name] = {
            m["name"]: m for m in mixin_def.get("methods", [])
        }

    for tool_def in schema.get("tools", {}).values():
        methods = tool_def.get("methods", [])
        resolved: list[dict] = []
        for m in methods:
            ref = m.get("$ref")
            if ref and ref in mixin_lookup:
                mixin_method = mixin_lookup[ref].get(m["name"])
                if mixin_method:
                    resolved.append(mixin_method)
                else:
                    resolved.append(m)
            else:
                resolved.append(m)
        tool_def["methods"] = resolved

    return schema


def load_schema() -> dict:
    with open(CODEGEN_DIR / "goud_sdk.schema.json") as f:
        schema = json.load(f)
    return resolve_mixins(schema)


def load_ffi_mapping() -> dict:
    with open(CODEGEN_DIR / "ffi_mapping.json") as f:
        return json.load(f)


# ── Naming conventions ──────────────────────────────────────────────


def to_pascal(name: str) -> str:
    """camelCase or PascalCase -> PascalCase"""
    if not name:
        return name
    return name[0].upper() + name[1:]


def to_snake(name: str) -> str:
    """camelCase -> snake_case"""
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s2 = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def to_screaming_snake(name: str) -> str:
    """camelCase -> SCREAMING_SNAKE_CASE"""
    return to_snake(name).upper()


def to_camel(name: str) -> str:
    """Already camelCase in schema, but ensure first char is lower."""
    if not name:
        return name
    return name[0].lower() + name[1:]


# ── Type mapping helpers ────────────────────────────────────────────

# Schema primitive types -> language types
CSHARP_TYPES = {
    "f32": "float", "f64": "double",
    "u8": "byte", "u16": "ushort", "u32": "uint", "u64": "ulong",
    "i8": "sbyte", "i16": "short", "i32": "int", "i64": "long",
    "bool": "bool", "string": "string", "bytes": "byte[]", "void": "void",
}

PYTHON_TYPES = {
    "f32": "float", "f64": "float",
    "u8": "int", "u16": "int", "u32": "int", "u64": "int",
    "i8": "int", "i16": "int", "i32": "int", "i64": "int",
    "usize": "int", "ptr": "int",
    "bool": "bool", "string": "str", "bytes": "bytes", "void": "None",
}

TYPESCRIPT_TYPES = {
    "f32": "number", "f64": "number",
    "u8": "number", "u16": "number", "u32": "number", "u64": "number",
    "i8": "number", "i16": "number", "i32": "number", "i64": "number",
    "usize": "number", "ptr": "number",
    "bool": "boolean", "string": "string", "void": "void",
    "u8[]": "Uint8Array", "bytes": "Uint8Array",
}

CTYPES_MAP = {
    "f32": "ctypes.c_float", "f64": "ctypes.c_double",
    "u8": "ctypes.c_uint8", "u16": "ctypes.c_uint16",
    "u32": "ctypes.c_uint32", "u64": "ctypes.c_uint64",
    "i8": "ctypes.c_int8", "i16": "ctypes.c_int16",
    "i32": "ctypes.c_int32", "i64": "ctypes.c_int64",
    "usize": "ctypes.c_size_t",
    "ptr": "ctypes.c_void_p",
    "bool": "ctypes.c_bool",
    "*const c_char": "ctypes.c_char_p",
    "*const u8": "ctypes.POINTER(ctypes.c_uint8)",
    "*mut u8": "ctypes.POINTER(ctypes.c_uint8)",
    "*mut f32": "ctypes.POINTER(ctypes.c_float)",
    "*mut i64": "ctypes.POINTER(ctypes.c_int64)",
    "*mut i32": "ctypes.POINTER(ctypes.c_int32)",
    "*mut u32": "ctypes.POINTER(ctypes.c_uint32)",
    "*mut u64": "ctypes.POINTER(ctypes.c_uint64)",
    "*const u64": "ctypes.POINTER(ctypes.c_uint64)",
    "*mut *const u8": "ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8))",
    "*mut GoudContact": "ctypes.POINTER(GoudContact)",
    "*mut GoudRenderStats": "ctypes.POINTER(GoudRenderStats)",
    "*mut FpsStats": "ctypes.POINTER(GoudFpsStats)",
    "*mut FfiTransform2D": "ctypes.POINTER(FfiTransform2D)",
    "*const FfiTransform2D": "ctypes.POINTER(FfiTransform2D)",
    "*mut FfiSprite": "ctypes.POINTER(FfiSprite)",
    "*const FfiSprite": "ctypes.POINTER(FfiSprite)",
    "*mut FfiTransform2DBuilder": "ctypes.c_void_p",
    "*mut FfiSpriteBuilder": "ctypes.c_void_p",
    "*mut FfiAnimationClipBuilder": "ctypes.c_void_p",
    "*mut c_void": "ctypes.c_void_p",
    "Option<CollisionCallback>": "ctypes.c_void_p",
    "FfiTransform2D": "FfiTransform2D",
    "FfiVec2": "FfiVec2",
    "FfiColor": "FfiColor",
    "FfiRect": "FfiRect",
    "FfiSprite": "FfiSprite",
    "FfiText": "FfiText",
    "*mut FfiText": "ctypes.POINTER(FfiText)",
    "*const FfiText": "ctypes.POINTER(FfiText)",
    "FfiMat3x3": "FfiMat3x3",
    "NetworkSimulationConfig": "FfiNetworkSimulationConfig",
    "GoudContextId": "GoudContextId",
    "GoudResult": "GoudResult",
}


def resolve_ctypes_type(
    ffi_type: str,
    enums: dict | None = None,
    default: str = "ctypes.c_uint64",
) -> str:
    """Resolve an FFI type string into a ctypes declaration type string."""
    if ffi_type == "void":
        return "None"

    direct = CTYPES_MAP.get(ffi_type)
    if direct:
        return direct

    if enums and ffi_type.startswith("Ffi"):
        enum_name = ffi_type[3:]
        if enum_name in enums:
            underlying = enums[enum_name].get("underlying", "i32")
            return CTYPES_MAP.get(underlying, "ctypes.c_int32")

    if ffi_type.startswith("Option<") and ffi_type.endswith(">"):
        inner = ffi_type[7:-1]
        if "Callback" in inner:
            return "ctypes.c_void_p"
        inner_direct = CTYPES_MAP.get(inner)
        if inner_direct:
            return inner_direct

    if ffi_type.startswith("*const ") or ffi_type.startswith("*mut "):
        inner = ffi_type.split(" ", 1)[1].strip()
        if inner == "c_void":
            return "ctypes.c_void_p"
        if inner == "c_char" and ffi_type.startswith("*const "):
            return "ctypes.c_char_p"
        inner_direct = CTYPES_MAP.get(inner)
        if inner_direct:
            return f"ctypes.POINTER({inner_direct})"
        if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", inner):
            return f"ctypes.POINTER({inner})"
        return "ctypes.c_void_p"

    return default

CSHARP_FFI_TYPES = {
    "f32": "float", "f64": "double",
    "u8": "byte", "u16": "ushort", "u32": "uint", "u64": "ulong",
    "i8": "sbyte", "i16": "short", "i32": "int", "i64": "long",
    "bool": "[MarshalAs(UnmanagedType.U1)] bool",
    "*const c_char": "[MarshalAs(UnmanagedType.LPStr)] string",
    "*mut f32": "ref float", "*mut i64": "ref long", "*mut i32": "ref int", "*mut u32": "ref uint",
    "*mut u64": "ref ulong", "*const u64": "IntPtr",
    "*mut *const u8": "ref IntPtr",
    "*mut GoudContact": "ref GoudContact",
    "*mut GoudRenderStats": "ref GoudRenderStats",
    "*mut FpsStats": "ref GoudFpsStats",
    "Option<CollisionCallback>": "IntPtr",
    "GoudContextId": "GoudContextId",
    "GoudResult": "GoudResult",
    "void": "void",
}


def map_type(schema_type: str, lang_map: dict) -> str:
    """Map a schema type to language-specific type, handling nullable."""
    nullable = schema_type.endswith("?")
    base = schema_type.rstrip("?")
    mapped = lang_map.get(base, base)
    if nullable and lang_map is TYPESCRIPT_TYPES:
        return f"{mapped} | null"
    if nullable and lang_map is CSHARP_TYPES:
        return f"{mapped}?"
    return mapped


def load_errors(schema: dict) -> tuple[list[dict], list[dict]]:
    """Extract error categories and codes from the schema.

    Returns (categories, codes) where each is a list of dicts
    as defined in the schema's ``errors`` section.  Returns empty
    lists if the section is absent.
    """
    errors = schema.get("errors", {})
    return errors.get("categories", []), errors.get("codes", [])


def write_generated(path: Path, content: str):
    """Write a generated file, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix == ".cs":
        lines = content.splitlines()
        header = "\n".join(lines[:5])
        if "#nullable" not in header:
            insert_at = 1 if lines and lines[0].startswith("//") else 0
            lines.insert(insert_at, "#nullable enable")
            content = "\n".join(lines)
    path.write_text(content)
    print(f"  Generated: {path.relative_to(ROOT_DIR)}")


def indent(text: str, n: int = 4) -> str:
    """Indent each line by n spaces."""
    return textwrap.indent(text, " " * n)
