// This file is AUTO-GENERATED by codegen/gen_lua.py. DO NOT EDIT.

use mlua::prelude::*;

pub(crate) fn register_enum_constants(lua: &Lua) {
    let globals = lua.globals();
    // Key
    let tbl = lua.create_table().unwrap();
    tbl.set("unknown", -1_i64).unwrap();
    tbl.set("space", 32_i64).unwrap();
    tbl.set("apostrophe", 39_i64).unwrap();
    tbl.set("comma", 44_i64).unwrap();
    tbl.set("minus", 45_i64).unwrap();
    tbl.set("period", 46_i64).unwrap();
    tbl.set("slash", 47_i64).unwrap();
    tbl.set("digit0", 48_i64).unwrap();
    tbl.set("digit1", 49_i64).unwrap();
    tbl.set("digit2", 50_i64).unwrap();
    tbl.set("digit3", 51_i64).unwrap();
    tbl.set("digit4", 52_i64).unwrap();
    tbl.set("digit5", 53_i64).unwrap();
    tbl.set("digit6", 54_i64).unwrap();
    tbl.set("digit7", 55_i64).unwrap();
    tbl.set("digit8", 56_i64).unwrap();
    tbl.set("digit9", 57_i64).unwrap();
    tbl.set("semicolon", 59_i64).unwrap();
    tbl.set("equal", 61_i64).unwrap();
    tbl.set("a", 65_i64).unwrap();
    tbl.set("b", 66_i64).unwrap();
    tbl.set("c", 67_i64).unwrap();
    tbl.set("d", 68_i64).unwrap();
    tbl.set("e", 69_i64).unwrap();
    tbl.set("f", 70_i64).unwrap();
    tbl.set("g", 71_i64).unwrap();
    tbl.set("h", 72_i64).unwrap();
    tbl.set("i", 73_i64).unwrap();
    tbl.set("j", 74_i64).unwrap();
    tbl.set("k", 75_i64).unwrap();
    tbl.set("l", 76_i64).unwrap();
    tbl.set("m", 77_i64).unwrap();
    tbl.set("n", 78_i64).unwrap();
    tbl.set("o", 79_i64).unwrap();
    tbl.set("p", 80_i64).unwrap();
    tbl.set("q", 81_i64).unwrap();
    tbl.set("r", 82_i64).unwrap();
    tbl.set("s", 83_i64).unwrap();
    tbl.set("t", 84_i64).unwrap();
    tbl.set("u", 85_i64).unwrap();
    tbl.set("v", 86_i64).unwrap();
    tbl.set("w", 87_i64).unwrap();
    tbl.set("x", 88_i64).unwrap();
    tbl.set("y", 89_i64).unwrap();
    tbl.set("z", 90_i64).unwrap();
    tbl.set("left_bracket", 91_i64).unwrap();
    tbl.set("backslash", 92_i64).unwrap();
    tbl.set("right_bracket", 93_i64).unwrap();
    tbl.set("grave_accent", 96_i64).unwrap();
    tbl.set("escape", 256_i64).unwrap();
    tbl.set("enter", 257_i64).unwrap();
    tbl.set("tab", 258_i64).unwrap();
    tbl.set("backspace", 259_i64).unwrap();
    tbl.set("insert", 260_i64).unwrap();
    tbl.set("delete", 261_i64).unwrap();
    tbl.set("right", 262_i64).unwrap();
    tbl.set("left", 263_i64).unwrap();
    tbl.set("down", 264_i64).unwrap();
    tbl.set("up", 265_i64).unwrap();
    tbl.set("page_up", 266_i64).unwrap();
    tbl.set("page_down", 267_i64).unwrap();
    tbl.set("home", 268_i64).unwrap();
    tbl.set("end", 269_i64).unwrap();
    tbl.set("caps_lock", 280_i64).unwrap();
    tbl.set("scroll_lock", 281_i64).unwrap();
    tbl.set("num_lock", 282_i64).unwrap();
    tbl.set("print_screen", 283_i64).unwrap();
    tbl.set("pause", 284_i64).unwrap();
    tbl.set("f1", 290_i64).unwrap();
    tbl.set("f2", 291_i64).unwrap();
    tbl.set("f3", 292_i64).unwrap();
    tbl.set("f4", 293_i64).unwrap();
    tbl.set("f5", 294_i64).unwrap();
    tbl.set("f6", 295_i64).unwrap();
    tbl.set("f7", 296_i64).unwrap();
    tbl.set("f8", 297_i64).unwrap();
    tbl.set("f9", 298_i64).unwrap();
    tbl.set("f10", 299_i64).unwrap();
    tbl.set("f11", 300_i64).unwrap();
    tbl.set("f12", 301_i64).unwrap();
    tbl.set("numpad0", 320_i64).unwrap();
    tbl.set("numpad1", 321_i64).unwrap();
    tbl.set("numpad2", 322_i64).unwrap();
    tbl.set("numpad3", 323_i64).unwrap();
    tbl.set("numpad4", 324_i64).unwrap();
    tbl.set("numpad5", 325_i64).unwrap();
    tbl.set("numpad6", 326_i64).unwrap();
    tbl.set("numpad7", 327_i64).unwrap();
    tbl.set("numpad8", 328_i64).unwrap();
    tbl.set("numpad9", 329_i64).unwrap();
    tbl.set("numpad_decimal", 330_i64).unwrap();
    tbl.set("numpad_divide", 331_i64).unwrap();
    tbl.set("numpad_multiply", 332_i64).unwrap();
    tbl.set("numpad_subtract", 333_i64).unwrap();
    tbl.set("numpad_add", 334_i64).unwrap();
    tbl.set("numpad_enter", 335_i64).unwrap();
    tbl.set("left_shift", 340_i64).unwrap();
    tbl.set("left_control", 341_i64).unwrap();
    tbl.set("left_alt", 342_i64).unwrap();
    tbl.set("left_super", 343_i64).unwrap();
    tbl.set("right_shift", 344_i64).unwrap();
    tbl.set("right_control", 345_i64).unwrap();
    tbl.set("right_alt", 346_i64).unwrap();
    tbl.set("right_super", 347_i64).unwrap();
    globals.set("key", tbl).unwrap();
    // MouseButton
    let tbl = lua.create_table().unwrap();
    tbl.set("left", 0_i64).unwrap();
    tbl.set("right", 1_i64).unwrap();
    tbl.set("middle", 2_i64).unwrap();
    tbl.set("button4", 3_i64).unwrap();
    tbl.set("button5", 4_i64).unwrap();
    tbl.set("button6", 5_i64).unwrap();
    tbl.set("button7", 6_i64).unwrap();
    tbl.set("button8", 7_i64).unwrap();
    globals.set("mouse_button", tbl).unwrap();
    // RendererType
    let tbl = lua.create_table().unwrap();
    tbl.set("renderer2_d", 0_i64).unwrap();
    tbl.set("renderer3_d", 1_i64).unwrap();
    globals.set("renderer_type", tbl).unwrap();
    // OverlayCorner
    let tbl = lua.create_table().unwrap();
    tbl.set("top_left", 0_i64).unwrap();
    tbl.set("top_right", 1_i64).unwrap();
    tbl.set("bottom_left", 2_i64).unwrap();
    tbl.set("bottom_right", 3_i64).unwrap();
    globals.set("overlay_corner", tbl).unwrap();
    // DebuggerStepKind
    let tbl = lua.create_table().unwrap();
    tbl.set("frame", 0_i64).unwrap();
    tbl.set("tick", 1_i64).unwrap();
    globals.set("debugger_step_kind", tbl).unwrap();
    // PlaybackMode
    let tbl = lua.create_table().unwrap();
    tbl.set("loop", 0_i64).unwrap();
    tbl.set("one_shot", 1_i64).unwrap();
    globals.set("playback_mode", tbl).unwrap();
    // BodyType
    let tbl = lua.create_table().unwrap();
    tbl.set("dynamic", 0_i64).unwrap();
    tbl.set("static", 1_i64).unwrap();
    tbl.set("kinematic", 2_i64).unwrap();
    globals.set("body_type", tbl).unwrap();
    // ShapeType
    let tbl = lua.create_table().unwrap();
    tbl.set("box", 0_i64).unwrap();
    tbl.set("circle", 1_i64).unwrap();
    globals.set("shape_type", tbl).unwrap();
    // PhysicsBackend2D
    let tbl = lua.create_table().unwrap();
    tbl.set("default", 0_i64).unwrap();
    tbl.set("rapier", 1_i64).unwrap();
    tbl.set("simple", 2_i64).unwrap();
    globals.set("physics_backend2_d", tbl).unwrap();
    // RenderBackendKind
    let tbl = lua.create_table().unwrap();
    tbl.set("wgpu", 0_i64).unwrap();
    tbl.set("open_gl_legacy", 1_i64).unwrap();
    globals.set("render_backend_kind", tbl).unwrap();
    // WindowBackendKind
    let tbl = lua.create_table().unwrap();
    tbl.set("winit", 0_i64).unwrap();
    tbl.set("glfw_legacy", 1_i64).unwrap();
    globals.set("window_backend_kind", tbl).unwrap();
    // EasingType
    let tbl = lua.create_table().unwrap();
    tbl.set("linear", 0_i64).unwrap();
    tbl.set("ease_in_quad", 1_i64).unwrap();
    tbl.set("ease_out_quad", 2_i64).unwrap();
    tbl.set("ease_in_out_quad", 3_i64).unwrap();
    globals.set("easing_type", tbl).unwrap();
    // NetworkProtocol
    let tbl = lua.create_table().unwrap();
    tbl.set("udp", 0_i64).unwrap();
    tbl.set("web_socket", 1_i64).unwrap();
    tbl.set("tcp", 2_i64).unwrap();
    globals.set("network_protocol", tbl).unwrap();
    // TransitionType
    let tbl = lua.create_table().unwrap();
    tbl.set("instant", 0_i64).unwrap();
    tbl.set("fade", 1_i64).unwrap();
    tbl.set("custom", 2_i64).unwrap();
    globals.set("transition_type", tbl).unwrap();
    // TextAlignment
    let tbl = lua.create_table().unwrap();
    tbl.set("left", 0_i64).unwrap();
    tbl.set("center", 1_i64).unwrap();
    tbl.set("right", 2_i64).unwrap();
    globals.set("text_alignment", tbl).unwrap();
    // TextDirection
    let tbl = lua.create_table().unwrap();
    tbl.set("auto", 0_i64).unwrap();
    tbl.set("ltr", 1_i64).unwrap();
    tbl.set("rtl", 2_i64).unwrap();
    globals.set("text_direction", tbl).unwrap();
    // BlendMode
    let tbl = lua.create_table().unwrap();
    tbl.set("override", 0_i64).unwrap();
    tbl.set("additive", 1_i64).unwrap();
    globals.set("blend_mode", tbl).unwrap();
    // EventPayloadType
    let tbl = lua.create_table().unwrap();
    tbl.set("none", 0_i64).unwrap();
    tbl.set("int", 1_i64).unwrap();
    tbl.set("float", 2_i64).unwrap();
    tbl.set("string", 3_i64).unwrap();
    globals.set("event_payload_type", tbl).unwrap();
}
