//! Auto-generated Lua bindings for GoudEngine.
//!
//! The `.g.rs` files are generated by `codegen/gen_lua.py` and should
//! not be edited by hand.

#[allow(
    unused_imports,
    unused_variables,
    dead_code,
    clippy::redundant_closure_call,
    clippy::needless_pass_by_value,
    clippy::too_many_arguments
)]
mod types {
    include!("types.g.rs");
}

#[allow(
    unused_imports,
    unused_variables,
    dead_code,
    clippy::redundant_closure_call,
    clippy::needless_pass_by_value,
    clippy::too_many_arguments
)]
mod enums {
    include!("enums.g.rs");
}

#[cfg(all(feature = "lua", feature = "native"))]
#[allow(
    unused_imports,
    unused_variables,
    dead_code,
    clippy::redundant_closure_call,
    clippy::needless_pass_by_value,
    clippy::too_many_arguments,
    clippy::missing_safety_doc
)]
mod tools {
    include!("tools.g.rs");
}

#[allow(
    unused_imports,
    unused_variables,
    dead_code,
    clippy::redundant_closure_call,
    clippy::needless_pass_by_value,
    clippy::too_many_arguments
)]
mod register {
    include!("register.g.rs");
}

pub(super) use register::register_lua_bindings;
