// This file is AUTO-GENERATED by codegen/gen_lua.py. DO NOT EDIT.

use mlua::prelude::*;
use crate::core::types::GoudResult;

use crate::core::context_id::GoudContextId;

use crate::ffi::animation::goud_animation_controller_create;
use crate::ffi::animation::goud_animation_controller_update;
use crate::ffi::animation::goud_animation_events_count;
use crate::ffi::animation::goud_animation_layer_add_frame;
use crate::ffi::animation::goud_animation_layer_play;
use crate::ffi::animation::goud_animation_layer_reset;
use crate::ffi::animation::goud_animation_layer_set_clip;
use crate::ffi::animation::goud_animation_layer_set_weight;
use crate::ffi::animation::goud_animation_layer_stack_create;
use crate::ffi::animation::goud_animation_play;
use crate::ffi::animation::goud_animation_stop;
use crate::ffi::audio::controls::goud_audio_activate;
use crate::ffi::audio::controls::goud_audio_active_count;
use crate::ffi::audio::spatial::goud_audio_active_crossfade_count;
use crate::ffi::audio::controls::goud_audio_cleanup_finished;
use crate::ffi::audio::spatial::goud_audio_crossfade;
use crate::ffi::audio::controls::goud_audio_get_channel_volume;
use crate::ffi::audio::controls::goud_audio_get_global_volume;
use crate::ffi::audio::controls::goud_audio_is_playing;
use crate::ffi::audio::controls::goud_audio_pause;
use crate::ffi::audio::controls::goud_audio_resume;
use crate::ffi::audio::controls::goud_audio_set_channel_volume;
use crate::ffi::audio::controls::goud_audio_set_global_volume;
use crate::ffi::audio::spatial::goud_audio_set_listener_position_3d;
use crate::ffi::audio::spatial::goud_audio_set_player_speed;
use crate::ffi::audio::spatial::goud_audio_set_player_volume;
use crate::ffi::audio::spatial::goud_audio_set_source_position_3d;
use crate::ffi::audio::controls::goud_audio_stop;
use crate::ffi::audio::controls::goud_audio_stop_all;
use crate::ffi::audio::spatial::goud_audio_update_crossfades;
use crate::ffi::audio::spatial::goud_audio_update_spatial_volume_3d;
use crate::ffi::collision::goud_collision_aabb_overlap;
use crate::ffi::collision::goud_collision_circle_overlap;
use crate::ffi::collision::goud_collision_distance;
use crate::ffi::collision::goud_collision_distance_squared;
use crate::ffi::collision::goud_collision_point_in_circle;
use crate::ffi::collision::goud_collision_point_in_rect;
use crate::ffi::component::goud_component_count;
use crate::ffi::context::goud_context_destroy;
use crate::ffi::context::goud_context_is_valid;
use crate::ffi::debug::goud_debug_set_fps_overlay_corner;
use crate::ffi::debug::goud_debug_set_fps_overlay_enabled;
use crate::ffi::debug::goud_debug_set_fps_update_interval;
use crate::ffi::debug::goud_debugger_clear_selected_entity;
use crate::ffi::debug::goud_debugger_set_debug_draw_enabled;
use crate::ffi::debug::goud_debugger_set_paused;
use crate::ffi::debug::goud_debugger_set_profiling_enabled;
use crate::ffi::debug::goud_debugger_set_selected_entity;
use crate::ffi::debug::goud_debugger_set_time_scale;
use crate::ffi::debug::goud_debugger_start_recording;
use crate::ffi::debug::goud_debugger_stop_replay;
use crate::ffi::entity::goud_entity_clone;
use crate::ffi::entity::goud_entity_clone_recursive;
use crate::ffi::entity::goud_entity_count;
use crate::ffi::entity::goud_entity_despawn;
use crate::ffi::entity::goud_entity_is_alive;
use crate::ffi::pool::goud_entity_pool_acquire;
use crate::ffi::pool::goud_entity_pool_destroy;
use crate::ffi::pool::goud_entity_pool_release;
use crate::ffi::entity::goud_entity_spawn_empty;
use crate::ffi::window::goud_fixed_timestep_begin;
use crate::ffi::window::goud_fixed_timestep_set;
use crate::ffi::window::goud_fixed_timestep_set_max_steps;
use crate::ffi::arena::goud_frame_arena_reset;
use crate::ffi::network::goud_network_clear_overlay_handle;
use crate::ffi::network::goud_network_clear_simulation;
use crate::ffi::network::goud_network_disconnect;
use crate::ffi::network::goud_network_host;
use crate::ffi::network::goud_network_peer_count;
use crate::ffi::network::goud_network_poll;
use crate::ffi::network::goud_network_set_overlay_handle;
use crate::ffi::network::goud_p2p_get_host;
use crate::ffi::network::goud_p2p_get_peers;
use crate::ffi::network::goud_p2p_leave_mesh;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_add_collider;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_add_rigid_body;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_add_rigid_body_ex;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_apply_force;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_apply_impulse;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_create;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_destroy;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_remove_body;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_remove_joint;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_body_gravity_scale;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_collider_friction;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_collider_restitution;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_gravity;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_timestep;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_set_velocity;
#[cfg(feature = "rapier3d")]
use crate::ffi::physics::goud_physics3d_step;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_add_collider;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_add_collider_ex;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_add_rigid_body;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_add_rigid_body_ex;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_apply_force;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_apply_impulse;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_collision_event_count;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_collision_events_count;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_create;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_create_with_backend;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_destroy;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_remove_body;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_remove_joint;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_body_gravity_scale;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_collider_friction;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_collider_restitution;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_gravity;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_timestep;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_set_velocity;
#[cfg(feature = "rapier2d")]
use crate::ffi::physics::goud_physics_step;
use crate::ffi::providers::goud_provider_check_hot_swap_shortcut;
use crate::ffi::renderer3d::goud_renderer3d_add_bloom_pass;
use crate::ffi::renderer3d::goud_renderer3d_add_blur_pass;
use crate::ffi::renderer3d::goud_renderer3d_add_color_grade_pass;
use crate::ffi::renderer3d::goud_renderer3d_configure_fog;
use crate::ffi::renderer3d::goud_renderer3d_configure_grid;
use crate::ffi::renderer3d::goud_renderer3d_configure_skybox;
use crate::ffi::renderer3d::goud_renderer3d_create_cube;
use crate::ffi::renderer3d::goud_renderer3d_create_cylinder;
use crate::ffi::renderer3d::goud_renderer3d_create_material;
use crate::ffi::renderer3d::goud_renderer3d_create_plane;
use crate::ffi::renderer3d::goud_renderer3d_create_sphere;
use crate::ffi::renderer3d::goud_renderer3d_destroy_object;
use crate::ffi::renderer3d::goud_renderer3d_get_object_material;
use crate::ffi::renderer3d::goud_renderer3d_postprocess_pass_count;
use crate::ffi::renderer3d::goud_renderer3d_remove_light;
use crate::ffi::renderer3d::goud_renderer3d_remove_material;
use crate::ffi::renderer3d::goud_renderer3d_remove_postprocess_pass;
use crate::ffi::renderer3d::goud_renderer3d_remove_skinned_mesh;
use crate::ffi::renderer3d::goud_renderer3d_render;
use crate::ffi::renderer3d::goud_renderer3d_set_camera_position;
use crate::ffi::renderer3d::goud_renderer3d_set_camera_rotation;
use crate::ffi::renderer3d::goud_renderer3d_set_fog_enabled;
use crate::ffi::renderer3d::goud_renderer3d_set_grid_enabled;
use crate::ffi::renderer3d::goud_renderer3d_set_object_material;
use crate::ffi::renderer3d::goud_renderer3d_set_object_position;
use crate::ffi::renderer3d::goud_renderer3d_set_object_rotation;
use crate::ffi::renderer3d::goud_renderer3d_set_object_scale;
use crate::ffi::renderer3d::goud_renderer3d_set_skinned_mesh_position;
use crate::ffi::renderer3d::goud_renderer3d_set_skinned_mesh_rotation;
use crate::ffi::renderer3d::goud_renderer3d_set_skinned_mesh_scale;
use crate::ffi::renderer3d::goud_renderer3d_update_material;
use crate::ffi::renderer::goud_renderer_clear_depth;
use crate::ffi::renderer::goud_renderer_disable_blending;
use crate::ffi::renderer::goud_renderer_disable_depth_test;
use crate::ffi::renderer::goud_renderer_enable_depth_test;
use crate::ffi::renderer::goud_renderer_get_coordinate_origin;
use crate::ffi::renderer::goud_renderer_set_coordinate_origin;
use crate::ffi::renderer::goud_renderer_set_viewport;
use crate::ffi::network::goud_rollback_check_desync;
use crate::ffi::network::goud_rollback_confirmed_frame;
use crate::ffi::network::goud_rollback_current_frame;
use crate::ffi::network::goud_rollback_destroy;
use crate::ffi::network::goud_rollback_resimulate;
use crate::ffi::network::goud_rollback_should_rollback;
use crate::ffi::network::goud_rpc_create;
use crate::ffi::network::goud_rpc_destroy;
use crate::ffi::network::goud_rpc_poll;
use crate::ffi::scene::goud_scene_count;
use crate::ffi::scene::goud_scene_destroy;
use crate::ffi::scene::goud_scene_get_current;
use crate::ffi::scene::goud_scene_is_active;
use crate::ffi::scene::goud_scene_set_active;
use crate::ffi::scene::goud_scene_set_current;
use crate::ffi::scene_transition::goud_scene_transition_is_active;
use crate::ffi::scene_transition::goud_scene_transition_progress;
use crate::ffi::scene_transition::goud_scene_transition_tick;
use crate::ffi::scene_transition::goud_scene_transition_to;
use crate::ffi::animation::goud_skeleton_create;
use crate::ffi::animation::goud_skeleton_set_bone_transform;
use crate::ffi::animation::goud_tween_create;
use crate::ffi::animation::goud_tween_destroy;
use crate::ffi::animation::goud_tween_is_complete;
use crate::ffi::animation::goud_tween_reset;
use crate::ffi::animation::goud_tween_update;
use crate::ffi::window::goud_window_destroy;
use crate::ffi::window::goud_window_set_size;
use crate::ffi::window::goud_window_should_close;

pub(crate) fn register_goud_game_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("goud_game").or_else(|_| lua.create_table())?;
    // GoudGame.shouldClose
    let f_should_close = lua.create_function(move |_, _: ()| {
        Ok(goud_window_should_close(ctx))
    })?;
    tbl.set("should_close", f_should_close)?;
    // GoudGame.setWindowSize
    let f_set_window_size = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_window_set_size(ctx, arg0 as u32, arg1 as u32))
    })?;
    tbl.set("set_window_size", f_set_window_size)?;
    // GoudGame.destroy
    let f_destroy = lua.create_function(move |_, _: ()| {
        Ok(goud_window_destroy(ctx))
    })?;
    tbl.set("destroy", f_destroy)?;
    // GoudGame.spawnEmpty
    let f_spawn_empty = lua.create_function(move |_, _: ()| {
        Ok(goud_entity_spawn_empty(ctx) as i64)
    })?;
    tbl.set("spawn_empty", f_spawn_empty)?;
    // GoudGame.despawn
    let f_despawn = lua.create_function(move |_, arg0: i64| {
        let r = goud_entity_despawn(ctx, arg0 as u64);
        Ok(r.code as i64)
    })?;
    tbl.set("despawn", f_despawn)?;
    // GoudGame.cloneEntity
    let f_clone_entity = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_clone(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("clone_entity", f_clone_entity)?;
    // GoudGame.cloneEntityRecursive
    let f_clone_entity_recursive = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_clone_recursive(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("clone_entity_recursive", f_clone_entity_recursive)?;
    // GoudGame.entityCount
    let f_entity_count = lua.create_function(move |_, _: ()| {
        Ok(goud_entity_count(ctx) as i64)
    })?;
    tbl.set("entity_count", f_entity_count)?;
    // GoudGame.isAlive
    let f_is_alive = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_is_alive(ctx, arg0 as u64))
    })?;
    tbl.set("is_alive", f_is_alive)?;
    // GoudGame.play
    let f_play = lua.create_function(move |_, arg0: i64| {
        Ok(goud_animation_play(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("play", f_play)?;
    // GoudGame.stop
    let f_stop = lua.create_function(move |_, arg0: i64| {
        Ok(goud_animation_stop(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("stop", f_stop)?;
    // GoudGame.createCube
    let f_create_cube = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_create_cube(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32) as i64)
    })?;
    tbl.set("create_cube", f_create_cube)?;
    // GoudGame.createPlane
    let f_create_plane = lua.create_function(move |_, (arg0, arg1, arg2): (i64, f64, f64)| {
        Ok(goud_renderer3d_create_plane(ctx, arg0 as u32, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("create_plane", f_create_plane)?;
    // GoudGame.createSphere
    let f_create_sphere = lua.create_function(move |_, (arg0, arg1, arg2): (i64, f64, i64)| {
        Ok(goud_renderer3d_create_sphere(ctx, arg0 as u32, arg1 as f32, arg2 as u32) as i64)
    })?;
    tbl.set("create_sphere", f_create_sphere)?;
    // GoudGame.createCylinder
    let f_create_cylinder = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, i64)| {
        Ok(goud_renderer3d_create_cylinder(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as u32) as i64)
    })?;
    tbl.set("create_cylinder", f_create_cylinder)?;
    // GoudGame.setObjectPosition
    let f_set_object_position = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_object_position(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_object_position", f_set_object_position)?;
    // GoudGame.setObjectRotation
    let f_set_object_rotation = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_object_rotation(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_object_rotation", f_set_object_rotation)?;
    // GoudGame.setObjectScale
    let f_set_object_scale = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_object_scale(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_object_scale", f_set_object_scale)?;
    // GoudGame.destroyObject
    let f_destroy_object = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_destroy_object(ctx, arg0 as u32))
    })?;
    tbl.set("destroy_object", f_destroy_object)?;
    // GoudGame.removeLight
    let f_remove_light = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_remove_light(ctx, arg0 as u32))
    })?;
    tbl.set("remove_light", f_remove_light)?;
    // GoudGame.setCameraPosition3D
    let f_set_camera_position3_d = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_renderer3d_set_camera_position(ctx, arg0 as f32, arg1 as f32, arg2 as f32))
    })?;
    tbl.set("set_camera_position3_d", f_set_camera_position3_d)?;
    // GoudGame.setCameraRotation3D
    let f_set_camera_rotation3_d = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_renderer3d_set_camera_rotation(ctx, arg0 as f32, arg1 as f32, arg2 as f32))
    })?;
    tbl.set("set_camera_rotation3_d", f_set_camera_rotation3_d)?;
    // GoudGame.configureGrid
    let f_configure_grid = lua.create_function(move |_, (arg0, arg1, arg2): (bool, f64, i64)| {
        Ok(goud_renderer3d_configure_grid(ctx, arg0, arg1 as f32, arg2 as u32))
    })?;
    tbl.set("configure_grid", f_configure_grid)?;
    // GoudGame.setGridEnabled
    let f_set_grid_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_renderer3d_set_grid_enabled(ctx, arg0))
    })?;
    tbl.set("set_grid_enabled", f_set_grid_enabled)?;
    // GoudGame.configureSkybox
    let f_configure_skybox = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (bool, f64, f64, f64, f64)| {
        Ok(goud_renderer3d_configure_skybox(ctx, arg0, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32))
    })?;
    tbl.set("configure_skybox", f_configure_skybox)?;
    // GoudGame.configureFog
    let f_configure_fog = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (bool, f64, f64, f64, f64)| {
        Ok(goud_renderer3d_configure_fog(ctx, arg0, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32))
    })?;
    tbl.set("configure_fog", f_configure_fog)?;
    // GoudGame.setFogEnabled
    let f_set_fog_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_renderer3d_set_fog_enabled(ctx, arg0))
    })?;
    tbl.set("set_fog_enabled", f_set_fog_enabled)?;
    // GoudGame.render3D
    let f_render3_d = lua.create_function(move |_, _: ()| {
        Ok(goud_renderer3d_render(ctx))
    })?;
    tbl.set("render3_d", f_render3_d)?;
    // GoudGame.createMaterial
    let f_create_material = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8): (i64, f64, f64, f64, f64, f64, f64, f64, f64)| {
        Ok(goud_renderer3d_create_material(ctx, arg0 as i32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7 as f32, arg8 as f32) as i64)
    })?;
    tbl.set("create_material", f_create_material)?;
    // GoudGame.updateMaterial
    let f_update_material = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9): (i64, i64, f64, f64, f64, f64, f64, f64, f64, f64)| {
        Ok(goud_renderer3d_update_material(ctx, arg0 as u32, arg1 as i32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7 as f32, arg8 as f32, arg9 as f32))
    })?;
    tbl.set("update_material", f_update_material)?;
    // GoudGame.removeMaterial
    let f_remove_material = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_remove_material(ctx, arg0 as u32))
    })?;
    tbl.set("remove_material", f_remove_material)?;
    // GoudGame.setObjectMaterial
    let f_set_object_material = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_renderer3d_set_object_material(ctx, arg0 as u32, arg1 as u32))
    })?;
    tbl.set("set_object_material", f_set_object_material)?;
    // GoudGame.getObjectMaterial
    let f_get_object_material = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_get_object_material(ctx, arg0 as u32) as i64)
    })?;
    tbl.set("get_object_material", f_get_object_material)?;
    // GoudGame.removeSkinnedMesh
    let f_remove_skinned_mesh = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_remove_skinned_mesh(ctx, arg0 as u32))
    })?;
    tbl.set("remove_skinned_mesh", f_remove_skinned_mesh)?;
    // GoudGame.setSkinnedMeshPosition
    let f_set_skinned_mesh_position = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_skinned_mesh_position(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_skinned_mesh_position", f_set_skinned_mesh_position)?;
    // GoudGame.setSkinnedMeshRotation
    let f_set_skinned_mesh_rotation = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_skinned_mesh_rotation(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_skinned_mesh_rotation", f_set_skinned_mesh_rotation)?;
    // GoudGame.setSkinnedMeshScale
    let f_set_skinned_mesh_scale = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_renderer3d_set_skinned_mesh_scale(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32))
    })?;
    tbl.set("set_skinned_mesh_scale", f_set_skinned_mesh_scale)?;
    // GoudGame.addBloomPass
    let f_add_bloom_pass = lua.create_function(move |_, (arg0, arg1): (f64, f64)| {
        Ok(goud_renderer3d_add_bloom_pass(ctx, arg0 as f32, arg1 as f32) as i64)
    })?;
    tbl.set("add_bloom_pass", f_add_bloom_pass)?;
    // GoudGame.addBlurPass
    let f_add_blur_pass = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_add_blur_pass(ctx, arg0 as u32) as i64)
    })?;
    tbl.set("add_blur_pass", f_add_blur_pass)?;
    // GoudGame.addColorGradePass
    let f_add_color_grade_pass = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_renderer3d_add_color_grade_pass(ctx, arg0 as f32, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("add_color_grade_pass", f_add_color_grade_pass)?;
    // GoudGame.removePostprocessPass
    let f_remove_postprocess_pass = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer3d_remove_postprocess_pass(ctx, arg0 as u32))
    })?;
    tbl.set("remove_postprocess_pass", f_remove_postprocess_pass)?;
    // GoudGame.postprocessPassCount
    let f_postprocess_pass_count = lua.create_function(move |_, _: ()| {
        Ok(goud_renderer3d_postprocess_pass_count(ctx) as i64)
    })?;
    tbl.set("postprocess_pass_count", f_postprocess_pass_count)?;
    // GoudGame.setViewport
    let f_set_viewport = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, i64, i64, i64)| {
        goud_renderer_set_viewport(ctx, arg0 as i32, arg1 as i32, arg2 as u32, arg3 as u32);
        Ok(())
    })?;
    tbl.set("set_viewport", f_set_viewport)?;
    // GoudGame.enableDepthTest
    let f_enable_depth_test = lua.create_function(move |_, _: ()| {
        goud_renderer_enable_depth_test(ctx);
        Ok(())
    })?;
    tbl.set("enable_depth_test", f_enable_depth_test)?;
    // GoudGame.disableDepthTest
    let f_disable_depth_test = lua.create_function(move |_, _: ()| {
        goud_renderer_disable_depth_test(ctx);
        Ok(())
    })?;
    tbl.set("disable_depth_test", f_disable_depth_test)?;
    // GoudGame.clearDepth
    let f_clear_depth = lua.create_function(move |_, _: ()| {
        goud_renderer_clear_depth(ctx);
        Ok(())
    })?;
    tbl.set("clear_depth", f_clear_depth)?;
    // GoudGame.disableBlending
    let f_disable_blending = lua.create_function(move |_, _: ()| {
        goud_renderer_disable_blending(ctx);
        Ok(())
    })?;
    tbl.set("disable_blending", f_disable_blending)?;
    // GoudGame.setCoordinateOrigin
    let f_set_coordinate_origin = lua.create_function(move |_, arg0: i64| {
        Ok(goud_renderer_set_coordinate_origin(ctx, arg0 as u32))
    })?;
    tbl.set("set_coordinate_origin", f_set_coordinate_origin)?;
    // GoudGame.getCoordinateOrigin
    let f_get_coordinate_origin = lua.create_function(move |_, _: ()| {
        Ok(goud_renderer_get_coordinate_origin(ctx) as i64)
    })?;
    tbl.set("get_coordinate_origin", f_get_coordinate_origin)?;
    // GoudGame.setFpsOverlayEnabled
    let f_set_fps_overlay_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debug_set_fps_overlay_enabled(ctx, arg0) as i64)
    })?;
    tbl.set("set_fps_overlay_enabled", f_set_fps_overlay_enabled)?;
    // GoudGame.setFpsUpdateInterval
    let f_set_fps_update_interval = lua.create_function(move |_, arg0: f64| {
        Ok(goud_debug_set_fps_update_interval(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_fps_update_interval", f_set_fps_update_interval)?;
    // GoudGame.setFpsOverlayCorner
    let f_set_fps_overlay_corner = lua.create_function(move |_, arg0: i64| {
        Ok(goud_debug_set_fps_overlay_corner(ctx, arg0 as i32) as i64)
    })?;
    tbl.set("set_fps_overlay_corner", f_set_fps_overlay_corner)?;
    // GoudGame.setDebuggerPaused
    let f_set_debugger_paused = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_paused(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_paused", f_set_debugger_paused)?;
    // GoudGame.setDebuggerTimeScale
    let f_set_debugger_time_scale = lua.create_function(move |_, arg0: f64| {
        Ok(goud_debugger_set_time_scale(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_debugger_time_scale", f_set_debugger_time_scale)?;
    // GoudGame.setDebuggerDebugDrawEnabled
    let f_set_debugger_debug_draw_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_debug_draw_enabled(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_debug_draw_enabled", f_set_debugger_debug_draw_enabled)?;
    // GoudGame.setDebuggerProfilingEnabled
    let f_set_debugger_profiling_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_profiling_enabled(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_profiling_enabled", f_set_debugger_profiling_enabled)?;
    // GoudGame.setDebuggerSelectedEntity
    let f_set_debugger_selected_entity = lua.create_function(move |_, arg0: i64| {
        Ok(goud_debugger_set_selected_entity(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("set_debugger_selected_entity", f_set_debugger_selected_entity)?;
    // GoudGame.clearDebuggerSelectedEntity
    let f_clear_debugger_selected_entity = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_clear_selected_entity(ctx) as i64)
    })?;
    tbl.set("clear_debugger_selected_entity", f_clear_debugger_selected_entity)?;
    // GoudGame.startDebuggerRecording
    let f_start_debugger_recording = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_start_recording(ctx) as i64)
    })?;
    tbl.set("start_debugger_recording", f_start_debugger_recording)?;
    // GoudGame.stopDebuggerReplay
    let f_stop_debugger_replay = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_stop_replay(ctx) as i64)
    })?;
    tbl.set("stop_debugger_replay", f_stop_debugger_replay)?;
    #[cfg(feature = "rapier2d")]
    {
        // GoudGame.physicsCollisionEventsCount
        let f_physics_collision_events_count = lua.create_function(move |_, _: ()| {
            Ok(goud_physics_collision_events_count(ctx) as i64)
        })?;
        tbl.set("physics_collision_events_count", f_physics_collision_events_count)?;
    }
    // GoudGame.pointInRect
    let f_point_in_rect = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5): (f64, f64, f64, f64, f64, f64)| {
        Ok(goud_collision_point_in_rect(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32))
    })?;
    tbl.set("point_in_rect", f_point_in_rect)?;
    // GoudGame.pointInCircle
    let f_point_in_circle = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (f64, f64, f64, f64, f64)| {
        Ok(goud_collision_point_in_circle(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32))
    })?;
    tbl.set("point_in_circle", f_point_in_circle)?;
    // GoudGame.aabbOverlap
    let f_aabb_overlap = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7): (f64, f64, f64, f64, f64, f64, f64, f64)| {
        Ok(goud_collision_aabb_overlap(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7 as f32))
    })?;
    tbl.set("aabb_overlap", f_aabb_overlap)?;
    // GoudGame.circleOverlap
    let f_circle_overlap = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5): (f64, f64, f64, f64, f64, f64)| {
        Ok(goud_collision_circle_overlap(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32))
    })?;
    tbl.set("circle_overlap", f_circle_overlap)?;
    // GoudGame.distance
    let f_distance = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (f64, f64, f64, f64)| {
        Ok(goud_collision_distance(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32) as f64)
    })?;
    tbl.set("distance", f_distance)?;
    // GoudGame.distanceSquared
    let f_distance_squared = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (f64, f64, f64, f64)| {
        Ok(goud_collision_distance_squared(arg0 as f32, arg1 as f32, arg2 as f32, arg3 as f32) as f64)
    })?;
    tbl.set("distance_squared", f_distance_squared)?;
    // GoudGame.componentCount
    let f_component_count = lua.create_function(move |_, arg0: i64| {
        Ok(goud_component_count(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("component_count", f_component_count)?;
    // GoudGame.networkHost
    let f_network_host = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_network_host(ctx, arg0 as i32, arg1 as u16) as i64)
    })?;
    tbl.set("network_host", f_network_host)?;
    // GoudGame.networkDisconnect
    let f_network_disconnect = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_disconnect(ctx, arg0) as i64)
    })?;
    tbl.set("network_disconnect", f_network_disconnect)?;
    // GoudGame.networkPoll
    let f_network_poll = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_poll(ctx, arg0) as i64)
    })?;
    tbl.set("network_poll", f_network_poll)?;
    // GoudGame.networkPeerCount
    let f_network_peer_count = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_peer_count(ctx, arg0) as i64)
    })?;
    tbl.set("network_peer_count", f_network_peer_count)?;
    // GoudGame.clearNetworkSimulation
    let f_clear_network_simulation = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_clear_simulation(ctx, arg0) as i64)
    })?;
    tbl.set("clear_network_simulation", f_clear_network_simulation)?;
    // GoudGame.setNetworkOverlayHandle
    let f_set_network_overlay_handle = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_set_overlay_handle(ctx, arg0) as i64)
    })?;
    tbl.set("set_network_overlay_handle", f_set_network_overlay_handle)?;
    // GoudGame.clearNetworkOverlayHandle
    let f_clear_network_overlay_handle = lua.create_function(move |_, _: ()| {
        Ok(goud_network_clear_overlay_handle(ctx) as i64)
    })?;
    tbl.set("clear_network_overlay_handle", f_clear_network_overlay_handle)?;
    // GoudGame.audioStop
    let f_audio_stop = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_stop(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("audio_stop", f_audio_stop)?;
    // GoudGame.audioPause
    let f_audio_pause = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_pause(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("audio_pause", f_audio_pause)?;
    // GoudGame.audioResume
    let f_audio_resume = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_resume(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("audio_resume", f_audio_resume)?;
    // GoudGame.audioStopAll
    let f_audio_stop_all = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_stop_all(ctx) as i64)
    })?;
    tbl.set("audio_stop_all", f_audio_stop_all)?;
    // GoudGame.audioSetGlobalVolume
    let f_audio_set_global_volume = lua.create_function(move |_, arg0: f64| {
        Ok(goud_audio_set_global_volume(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("audio_set_global_volume", f_audio_set_global_volume)?;
    // GoudGame.audioGetGlobalVolume
    let f_audio_get_global_volume = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_get_global_volume(ctx) as f64)
    })?;
    tbl.set("audio_get_global_volume", f_audio_get_global_volume)?;
    // GoudGame.audioSetChannelVolume
    let f_audio_set_channel_volume = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_audio_set_channel_volume(ctx, arg0 as u8, arg1 as f32) as i64)
    })?;
    tbl.set("audio_set_channel_volume", f_audio_set_channel_volume)?;
    // GoudGame.audioGetChannelVolume
    let f_audio_get_channel_volume = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_get_channel_volume(ctx, arg0 as u8) as f64)
    })?;
    tbl.set("audio_get_channel_volume", f_audio_get_channel_volume)?;
    // GoudGame.audioIsPlaying
    let f_audio_is_playing = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_is_playing(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("audio_is_playing", f_audio_is_playing)?;
    // GoudGame.audioActiveCount
    let f_audio_active_count = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_active_count(ctx) as i64)
    })?;
    tbl.set("audio_active_count", f_audio_active_count)?;
    // GoudGame.audioCleanupFinished
    let f_audio_cleanup_finished = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_cleanup_finished(ctx) as i64)
    })?;
    tbl.set("audio_cleanup_finished", f_audio_cleanup_finished)?;
    // GoudGame.audioUpdateSpatial3d
    let f_audio_update_spatial3d = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8): (i64, f64, f64, f64, f64, f64, f64, f64, f64)| {
        Ok(goud_audio_update_spatial_volume_3d(ctx, arg0 as u64, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7 as f32, arg8 as f32) as i64)
    })?;
    tbl.set("audio_update_spatial3d", f_audio_update_spatial3d)?;
    // GoudGame.audioSetListenerPosition3d
    let f_audio_set_listener_position3d = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_audio_set_listener_position_3d(ctx, arg0 as f32, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("audio_set_listener_position3d", f_audio_set_listener_position3d)?;
    // GoudGame.audioSetSourcePosition3d
    let f_audio_set_source_position3d = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5): (i64, f64, f64, f64, f64, f64)| {
        Ok(goud_audio_set_source_position_3d(ctx, arg0 as u64, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32) as i64)
    })?;
    tbl.set("audio_set_source_position3d", f_audio_set_source_position3d)?;
    // GoudGame.audioSetPlayerVolume
    let f_audio_set_player_volume = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_audio_set_player_volume(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("audio_set_player_volume", f_audio_set_player_volume)?;
    // GoudGame.audioSetPlayerSpeed
    let f_audio_set_player_speed = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_audio_set_player_speed(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("audio_set_player_speed", f_audio_set_player_speed)?;
    // GoudGame.audioCrossfade
    let f_audio_crossfade = lua.create_function(move |_, (arg0, arg1, arg2): (i64, i64, f64)| {
        Ok(goud_audio_crossfade(ctx, arg0 as u64, arg1 as u64, arg2 as f32) as i64)
    })?;
    tbl.set("audio_crossfade", f_audio_crossfade)?;
    // GoudGame.audioUpdateCrossfades
    let f_audio_update_crossfades = lua.create_function(move |_, arg0: f64| {
        Ok(goud_audio_update_crossfades(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("audio_update_crossfades", f_audio_update_crossfades)?;
    // GoudGame.audioActiveCrossfadeCount
    let f_audio_active_crossfade_count = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_active_crossfade_count(ctx) as i64)
    })?;
    tbl.set("audio_active_crossfade_count", f_audio_active_crossfade_count)?;
    // GoudGame.audioActivate
    let f_audio_activate = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_activate(ctx) as i64)
    })?;
    tbl.set("audio_activate", f_audio_activate)?;
    // GoudGame.checkHotSwapShortcut
    let f_check_hot_swap_shortcut = lua.create_function(move |_, _: ()| {
        Ok(goud_provider_check_hot_swap_shortcut(ctx) as i64)
    })?;
    tbl.set("check_hot_swap_shortcut", f_check_hot_swap_shortcut)?;
    // GoudGame.p2pLeaveMesh
    let f_p2p_leave_mesh = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_leave_mesh(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_leave_mesh", f_p2p_leave_mesh)?;
    // GoudGame.p2pGetPeers
    let f_p2p_get_peers = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_get_peers(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_get_peers", f_p2p_get_peers)?;
    // GoudGame.p2pGetHost
    let f_p2p_get_host = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_get_host(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_get_host", f_p2p_get_host)?;
    // GoudGame.rollbackDestroy
    let f_rollback_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_destroy(arg0) as i64)
    })?;
    tbl.set("rollback_destroy", f_rollback_destroy)?;
    // GoudGame.rollbackShouldRollback
    let f_rollback_should_rollback = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_should_rollback(arg0) as i64)
    })?;
    tbl.set("rollback_should_rollback", f_rollback_should_rollback)?;
    // GoudGame.rollbackResimulate
    let f_rollback_resimulate = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_resimulate(arg0) as i64)
    })?;
    tbl.set("rollback_resimulate", f_rollback_resimulate)?;
    // GoudGame.rollbackConfirmedFrame
    let f_rollback_confirmed_frame = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_confirmed_frame(arg0) as i64)
    })?;
    tbl.set("rollback_confirmed_frame", f_rollback_confirmed_frame)?;
    // GoudGame.rollbackCurrentFrame
    let f_rollback_current_frame = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_current_frame(arg0) as i64)
    })?;
    tbl.set("rollback_current_frame", f_rollback_current_frame)?;
    // GoudGame.rollbackCheckDesync
    let f_rollback_check_desync = lua.create_function(move |_, (arg0, arg1, arg2): (i64, i64, i64)| {
        Ok(goud_rollback_check_desync(arg0, arg1 as u64, arg2 as u64) as i64)
    })?;
    tbl.set("rollback_check_desync", f_rollback_check_desync)?;
    // GoudGame.rpcCreate
    let f_rpc_create = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_rpc_create(arg0 as u64, arg1 as u32) as i64)
    })?;
    tbl.set("rpc_create", f_rpc_create)?;
    // GoudGame.rpcDestroy
    let f_rpc_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rpc_destroy(arg0) as i64)
    })?;
    tbl.set("rpc_destroy", f_rpc_destroy)?;
    // GoudGame.rpcPoll
    let f_rpc_poll = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_rpc_poll(arg0, arg1 as f32) as i64)
    })?;
    tbl.set("rpc_poll", f_rpc_poll)?;
    // GoudGame.runWithFixedUpdate
    let f_run_with_fixed_update = lua.create_function(move |_, _: ()| {
        Ok(goud_fixed_timestep_begin(ctx))
    })?;
    tbl.set("run_with_fixed_update", f_run_with_fixed_update)?;
    // GoudGame.setFixedTimestep
    let f_set_fixed_timestep = lua.create_function(move |_, arg0: f64| {
        Ok(goud_fixed_timestep_set(ctx, arg0 as f32))
    })?;
    tbl.set("set_fixed_timestep", f_set_fixed_timestep)?;
    // GoudGame.setMaxFixedSteps
    let f_set_max_fixed_steps = lua.create_function(move |_, arg0: i64| {
        Ok(goud_fixed_timestep_set_max_steps(ctx, arg0 as u32))
    })?;
    tbl.set("set_max_fixed_steps", f_set_max_fixed_steps)?;
    globals.set("goud_game", tbl)?;
    Ok(())
}

pub(crate) fn register_goud_context_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("goud_context").or_else(|_| lua.create_table())?;
    // GoudContext.destroy
    let f_destroy = lua.create_function(move |_, _: ()| {
        Ok(goud_context_destroy(ctx))
    })?;
    tbl.set("destroy", f_destroy)?;
    // GoudContext.isValid
    let f_is_valid = lua.create_function(move |_, _: ()| {
        Ok(goud_context_is_valid(ctx))
    })?;
    tbl.set("is_valid", f_is_valid)?;
    // GoudContext.networkHost
    let f_network_host = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_network_host(ctx, arg0 as i32, arg1 as u16) as i64)
    })?;
    tbl.set("network_host", f_network_host)?;
    // GoudContext.networkDisconnect
    let f_network_disconnect = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_disconnect(ctx, arg0) as i64)
    })?;
    tbl.set("network_disconnect", f_network_disconnect)?;
    // GoudContext.networkPoll
    let f_network_poll = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_poll(ctx, arg0) as i64)
    })?;
    tbl.set("network_poll", f_network_poll)?;
    // GoudContext.networkPeerCount
    let f_network_peer_count = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_peer_count(ctx, arg0) as i64)
    })?;
    tbl.set("network_peer_count", f_network_peer_count)?;
    // GoudContext.clearNetworkSimulation
    let f_clear_network_simulation = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_clear_simulation(ctx, arg0) as i64)
    })?;
    tbl.set("clear_network_simulation", f_clear_network_simulation)?;
    // GoudContext.setNetworkOverlayHandle
    let f_set_network_overlay_handle = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_set_overlay_handle(ctx, arg0) as i64)
    })?;
    tbl.set("set_network_overlay_handle", f_set_network_overlay_handle)?;
    // GoudContext.clearNetworkOverlayHandle
    let f_clear_network_overlay_handle = lua.create_function(move |_, _: ()| {
        Ok(goud_network_clear_overlay_handle(ctx) as i64)
    })?;
    tbl.set("clear_network_overlay_handle", f_clear_network_overlay_handle)?;
    // GoudContext.setDebuggerPaused
    let f_set_debugger_paused = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_paused(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_paused", f_set_debugger_paused)?;
    // GoudContext.setDebuggerTimeScale
    let f_set_debugger_time_scale = lua.create_function(move |_, arg0: f64| {
        Ok(goud_debugger_set_time_scale(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_debugger_time_scale", f_set_debugger_time_scale)?;
    // GoudContext.setDebuggerDebugDrawEnabled
    let f_set_debugger_debug_draw_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_debug_draw_enabled(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_debug_draw_enabled", f_set_debugger_debug_draw_enabled)?;
    // GoudContext.setDebuggerProfilingEnabled
    let f_set_debugger_profiling_enabled = lua.create_function(move |_, arg0: bool| {
        Ok(goud_debugger_set_profiling_enabled(ctx, arg0) as i64)
    })?;
    tbl.set("set_debugger_profiling_enabled", f_set_debugger_profiling_enabled)?;
    // GoudContext.setDebuggerSelectedEntity
    let f_set_debugger_selected_entity = lua.create_function(move |_, arg0: i64| {
        Ok(goud_debugger_set_selected_entity(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("set_debugger_selected_entity", f_set_debugger_selected_entity)?;
    // GoudContext.clearDebuggerSelectedEntity
    let f_clear_debugger_selected_entity = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_clear_selected_entity(ctx) as i64)
    })?;
    tbl.set("clear_debugger_selected_entity", f_clear_debugger_selected_entity)?;
    // GoudContext.startDebuggerRecording
    let f_start_debugger_recording = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_start_recording(ctx) as i64)
    })?;
    tbl.set("start_debugger_recording", f_start_debugger_recording)?;
    // GoudContext.stopDebuggerReplay
    let f_stop_debugger_replay = lua.create_function(move |_, _: ()| {
        Ok(goud_debugger_stop_replay(ctx) as i64)
    })?;
    tbl.set("stop_debugger_replay", f_stop_debugger_replay)?;
    // GoudContext.spawnEmpty
    let f_spawn_empty = lua.create_function(move |_, _: ()| {
        Ok(goud_entity_spawn_empty(ctx) as i64)
    })?;
    tbl.set("spawn_empty", f_spawn_empty)?;
    // GoudContext.despawn
    let f_despawn = lua.create_function(move |_, arg0: i64| {
        let r = goud_entity_despawn(ctx, arg0 as u64);
        Ok(r.code as i64)
    })?;
    tbl.set("despawn", f_despawn)?;
    // GoudContext.cloneEntity
    let f_clone_entity = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_clone(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("clone_entity", f_clone_entity)?;
    // GoudContext.cloneEntityRecursive
    let f_clone_entity_recursive = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_clone_recursive(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("clone_entity_recursive", f_clone_entity_recursive)?;
    // GoudContext.isAlive
    let f_is_alive = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_is_alive(ctx, arg0 as u64))
    })?;
    tbl.set("is_alive", f_is_alive)?;
    // GoudContext.entityCount
    let f_entity_count = lua.create_function(move |_, _: ()| {
        Ok(goud_entity_count(ctx) as i64)
    })?;
    tbl.set("entity_count", f_entity_count)?;
    // GoudContext.componentCount
    let f_component_count = lua.create_function(move |_, arg0: i64| {
        Ok(goud_component_count(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("component_count", f_component_count)?;
    // GoudContext.sceneDestroy
    let f_scene_destroy = lua.create_function(move |_, arg0: i64| {
        let r = goud_scene_destroy(ctx, arg0 as u32);
        Ok(r.code as i64)
    })?;
    tbl.set("scene_destroy", f_scene_destroy)?;
    // GoudContext.setActiveScene
    let f_set_active_scene = lua.create_function(move |_, (arg0, arg1): (i64, bool)| {
        let r = goud_scene_set_active(ctx, arg0 as u32, arg1);
        Ok(r.code as i64)
    })?;
    tbl.set("set_active_scene", f_set_active_scene)?;
    // GoudContext.sceneSetActive
    let f_scene_set_active = lua.create_function(move |_, (arg0, arg1): (i64, bool)| {
        let r = goud_scene_set_active(ctx, arg0 as u32, arg1);
        Ok(r.code as i64)
    })?;
    tbl.set("scene_set_active", f_scene_set_active)?;
    // GoudContext.sceneIsActive
    let f_scene_is_active = lua.create_function(move |_, arg0: i64| {
        Ok(goud_scene_is_active(ctx, arg0 as u32))
    })?;
    tbl.set("scene_is_active", f_scene_is_active)?;
    // GoudContext.sceneCount
    let f_scene_count = lua.create_function(move |_, _: ()| {
        Ok(goud_scene_count(ctx) as i64)
    })?;
    tbl.set("scene_count", f_scene_count)?;
    // GoudContext.sceneSetCurrent
    let f_scene_set_current = lua.create_function(move |_, arg0: i64| {
        let r = goud_scene_set_current(ctx, arg0 as u32);
        Ok(r.code as i64)
    })?;
    tbl.set("scene_set_current", f_scene_set_current)?;
    // GoudContext.sceneGetCurrent
    let f_scene_get_current = lua.create_function(move |_, _: ()| {
        Ok(goud_scene_get_current(ctx) as i64)
    })?;
    tbl.set("scene_get_current", f_scene_get_current)?;
    // GoudContext.sceneTransitionTo
    let f_scene_transition_to = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, i64, i64, f64)| {
        let r = goud_scene_transition_to(ctx, arg0 as u32, arg1 as u32, arg2 as u8, arg3 as f32);
        Ok(r.code as i64)
    })?;
    tbl.set("scene_transition_to", f_scene_transition_to)?;
    // GoudContext.sceneTransitionProgress
    let f_scene_transition_progress = lua.create_function(move |_, _: ()| {
        Ok(goud_scene_transition_progress(ctx) as f64)
    })?;
    tbl.set("scene_transition_progress", f_scene_transition_progress)?;
    // GoudContext.sceneTransitionIsActive
    let f_scene_transition_is_active = lua.create_function(move |_, _: ()| {
        Ok(goud_scene_transition_is_active(ctx))
    })?;
    tbl.set("scene_transition_is_active", f_scene_transition_is_active)?;
    // GoudContext.sceneTransitionTick
    let f_scene_transition_tick = lua.create_function(move |_, arg0: f64| {
        let r = goud_scene_transition_tick(ctx, arg0 as f32);
        Ok(r.code as i64)
    })?;
    tbl.set("scene_transition_tick", f_scene_transition_tick)?;
    globals.set("goud_context", tbl)?;
    Ok(())
}

#[cfg(feature = "rapier2d")]
pub(crate) fn register_physics_world2_d_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("physics_world2_d").or_else(|_| lua.create_table())?;
    // PhysicsWorld2D.create
    let f_create = lua.create_function(move |_, (arg0, arg1): (f64, f64)| {
        Ok(goud_physics_create(ctx, arg0 as f32, arg1 as f32) as i64)
    })?;
    tbl.set("create", f_create)?;
    // PhysicsWorld2D.createWithBackend
    let f_create_with_backend = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, i64)| {
        Ok(goud_physics_create_with_backend(ctx, arg0 as f32, arg1 as f32, arg2 as u32) as i64)
    })?;
    tbl.set("create_with_backend", f_create_with_backend)?;
    // PhysicsWorld2D.destroy
    let f_destroy = lua.create_function(move |_, _: ()| {
        Ok(goud_physics_destroy(ctx) as i64)
    })?;
    tbl.set("destroy", f_destroy)?;
    // PhysicsWorld2D.setGravity
    let f_set_gravity = lua.create_function(move |_, (arg0, arg1): (f64, f64)| {
        Ok(goud_physics_set_gravity(ctx, arg0 as f32, arg1 as f32) as i64)
    })?;
    tbl.set("set_gravity", f_set_gravity)?;
    // PhysicsWorld2D.addRigidBody
    let f_add_rigid_body = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_physics_add_rigid_body(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32) as i64)
    })?;
    tbl.set("add_rigid_body", f_add_rigid_body)?;
    // PhysicsWorld2D.addRigidBodyEx
    let f_add_rigid_body_ex = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (i64, f64, f64, f64, bool)| {
        Ok(goud_physics_add_rigid_body_ex(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32, arg4) as i64)
    })?;
    tbl.set("add_rigid_body_ex", f_add_rigid_body_ex)?;
    // PhysicsWorld2D.addCollider
    let f_add_collider = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6): (i64, i64, f64, f64, f64, f64, f64)| {
        Ok(goud_physics_add_collider(ctx, arg0 as u64, arg1 as u32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32) as i64)
    })?;
    tbl.set("add_collider", f_add_collider)?;
    // PhysicsWorld2D.addColliderEx
    let f_add_collider_ex = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9): (i64, i64, f64, f64, f64, f64, f64, bool, i64, i64)| {
        Ok(goud_physics_add_collider_ex(ctx, arg0 as u64, arg1 as u32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7, arg8 as u32, arg9 as u32) as i64)
    })?;
    tbl.set("add_collider_ex", f_add_collider_ex)?;
    // PhysicsWorld2D.removeBody
    let f_remove_body = lua.create_function(move |_, arg0: i64| {
        Ok(goud_physics_remove_body(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("remove_body", f_remove_body)?;
    // PhysicsWorld2D.removeJoint
    let f_remove_joint = lua.create_function(move |_, arg0: i64| {
        Ok(goud_physics_remove_joint(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("remove_joint", f_remove_joint)?;
    // PhysicsWorld2D.step
    let f_step = lua.create_function(move |_, arg0: f64| {
        Ok(goud_physics_step(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("step", f_step)?;
    // PhysicsWorld2D.setVelocity
    let f_set_velocity = lua.create_function(move |_, (arg0, arg1, arg2): (i64, f64, f64)| {
        Ok(goud_physics_set_velocity(ctx, arg0 as u64, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("set_velocity", f_set_velocity)?;
    // PhysicsWorld2D.applyForce
    let f_apply_force = lua.create_function(move |_, (arg0, arg1, arg2): (i64, f64, f64)| {
        Ok(goud_physics_apply_force(ctx, arg0 as u64, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("apply_force", f_apply_force)?;
    // PhysicsWorld2D.applyImpulse
    let f_apply_impulse = lua.create_function(move |_, (arg0, arg1, arg2): (i64, f64, f64)| {
        Ok(goud_physics_apply_impulse(ctx, arg0 as u64, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("apply_impulse", f_apply_impulse)?;
    // PhysicsWorld2D.collisionEventsCount
    let f_collision_events_count = lua.create_function(move |_, _: ()| {
        Ok(goud_physics_collision_events_count(ctx) as i64)
    })?;
    tbl.set("collision_events_count", f_collision_events_count)?;
    // PhysicsWorld2D.collisionEventCount
    let f_collision_event_count = lua.create_function(move |_, _: ()| {
        Ok(goud_physics_collision_event_count(ctx) as i64)
    })?;
    tbl.set("collision_event_count", f_collision_event_count)?;
    // PhysicsWorld2D.setBodyGravityScale
    let f_set_body_gravity_scale = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics_set_body_gravity_scale(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_body_gravity_scale", f_set_body_gravity_scale)?;
    // PhysicsWorld2D.setColliderFriction
    let f_set_collider_friction = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics_set_collider_friction(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_collider_friction", f_set_collider_friction)?;
    // PhysicsWorld2D.setColliderRestitution
    let f_set_collider_restitution = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics_set_collider_restitution(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_collider_restitution", f_set_collider_restitution)?;
    // PhysicsWorld2D.setTimestep
    let f_set_timestep = lua.create_function(move |_, arg0: f64| {
        Ok(goud_physics_set_timestep(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_timestep", f_set_timestep)?;
    globals.set("physics_world2_d", tbl)?;
    Ok(())
}

#[cfg(feature = "rapier3d")]
pub(crate) fn register_physics_world3_d_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("physics_world3_d").or_else(|_| lua.create_table())?;
    // PhysicsWorld3D.create
    let f_create = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_physics3d_create(ctx, arg0 as f32, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("create", f_create)?;
    // PhysicsWorld3D.destroy
    let f_destroy = lua.create_function(move |_, _: ()| {
        Ok(goud_physics3d_destroy(ctx) as i64)
    })?;
    tbl.set("destroy", f_destroy)?;
    // PhysicsWorld3D.setGravity
    let f_set_gravity = lua.create_function(move |_, (arg0, arg1, arg2): (f64, f64, f64)| {
        Ok(goud_physics3d_set_gravity(ctx, arg0 as f32, arg1 as f32, arg2 as f32) as i64)
    })?;
    tbl.set("set_gravity", f_set_gravity)?;
    // PhysicsWorld3D.addRigidBody
    let f_add_rigid_body = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (i64, f64, f64, f64, f64)| {
        Ok(goud_physics3d_add_rigid_body(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32) as i64)
    })?;
    tbl.set("add_rigid_body", f_add_rigid_body)?;
    // PhysicsWorld3D.addRigidBodyEx
    let f_add_rigid_body_ex = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5): (i64, f64, f64, f64, f64, bool)| {
        Ok(goud_physics3d_add_rigid_body_ex(ctx, arg0 as u32, arg1 as f32, arg2 as f32, arg3 as f32, arg4 as f32, arg5) as i64)
    })?;
    tbl.set("add_rigid_body_ex", f_add_rigid_body_ex)?;
    // PhysicsWorld3D.addCollider
    let f_add_collider = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7): (i64, i64, f64, f64, f64, f64, f64, f64)| {
        Ok(goud_physics3d_add_collider(ctx, arg0 as u64, arg1 as u32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32, arg6 as f32, arg7 as f32) as i64)
    })?;
    tbl.set("add_collider", f_add_collider)?;
    // PhysicsWorld3D.removeBody
    let f_remove_body = lua.create_function(move |_, arg0: i64| {
        Ok(goud_physics3d_remove_body(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("remove_body", f_remove_body)?;
    // PhysicsWorld3D.removeJoint
    let f_remove_joint = lua.create_function(move |_, arg0: i64| {
        Ok(goud_physics3d_remove_joint(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("remove_joint", f_remove_joint)?;
    // PhysicsWorld3D.step
    let f_step = lua.create_function(move |_, arg0: f64| {
        Ok(goud_physics3d_step(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("step", f_step)?;
    // PhysicsWorld3D.setVelocity
    let f_set_velocity = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_physics3d_set_velocity(ctx, arg0 as u64, arg1 as f32, arg2 as f32, arg3 as f32) as i64)
    })?;
    tbl.set("set_velocity", f_set_velocity)?;
    // PhysicsWorld3D.applyForce
    let f_apply_force = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_physics3d_apply_force(ctx, arg0 as u64, arg1 as f32, arg2 as f32, arg3 as f32) as i64)
    })?;
    tbl.set("apply_force", f_apply_force)?;
    // PhysicsWorld3D.applyImpulse
    let f_apply_impulse = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (i64, f64, f64, f64)| {
        Ok(goud_physics3d_apply_impulse(ctx, arg0 as u64, arg1 as f32, arg2 as f32, arg3 as f32) as i64)
    })?;
    tbl.set("apply_impulse", f_apply_impulse)?;
    // PhysicsWorld3D.setBodyGravityScale
    let f_set_body_gravity_scale = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics3d_set_body_gravity_scale(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_body_gravity_scale", f_set_body_gravity_scale)?;
    // PhysicsWorld3D.setColliderFriction
    let f_set_collider_friction = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics3d_set_collider_friction(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_collider_friction", f_set_collider_friction)?;
    // PhysicsWorld3D.setColliderRestitution
    let f_set_collider_restitution = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_physics3d_set_collider_restitution(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("set_collider_restitution", f_set_collider_restitution)?;
    // PhysicsWorld3D.setTimestep
    let f_set_timestep = lua.create_function(move |_, arg0: f64| {
        Ok(goud_physics3d_set_timestep(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_timestep", f_set_timestep)?;
    globals.set("physics_world3_d", tbl)?;
    Ok(())
}

pub(crate) fn register_animation_controller_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("animation_controller").or_else(|_| lua.create_table())?;
    // AnimationController.create
    let f_create = lua.create_function(move |_, arg0: i64| {
        Ok(goud_animation_controller_create(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("create", f_create)?;
    // AnimationController.update
    let f_update = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_animation_controller_update(ctx, arg0 as u64, arg1 as f32) as i64)
    })?;
    tbl.set("update", f_update)?;
    globals.set("animation_controller", tbl)?;
    Ok(())
}

pub(crate) fn register_animation_events_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("animation_events").or_else(|_| lua.create_table())?;
    // AnimationEvents.count
    let f_count = lua.create_function(move |_, _: ()| {
        Ok(goud_animation_events_count(ctx) as i64)
    })?;
    tbl.set("count", f_count)?;
    globals.set("animation_events", tbl)?;
    Ok(())
}

pub(crate) fn register_tween_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("tween").or_else(|_| lua.create_table())?;
    // Tween.create
    let f_create = lua.create_function(move |_, (arg0, arg1, arg2, arg3): (f64, f64, f64, i64)| {
        Ok(goud_tween_create(ctx, arg0 as f32, arg1 as f32, arg2 as f32, arg3 as i32) as i64)
    })?;
    tbl.set("create", f_create)?;
    // Tween.update
    let f_update = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_tween_update(ctx, arg0, arg1 as f32) as i64)
    })?;
    tbl.set("update", f_update)?;
    // Tween.isComplete
    let f_is_complete = lua.create_function(move |_, arg0: i64| {
        Ok(goud_tween_is_complete(ctx, arg0) as i64)
    })?;
    tbl.set("is_complete", f_is_complete)?;
    // Tween.reset
    let f_reset = lua.create_function(move |_, arg0: i64| {
        Ok(goud_tween_reset(ctx, arg0) as i64)
    })?;
    tbl.set("reset", f_reset)?;
    // Tween.destroy
    let f_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_tween_destroy(ctx, arg0) as i64)
    })?;
    tbl.set("destroy", f_destroy)?;
    globals.set("tween", tbl)?;
    Ok(())
}

pub(crate) fn register_skeleton_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("skeleton").or_else(|_| lua.create_table())?;
    // Skeleton.create
    let f_create = lua.create_function(move |_, arg0: i64| {
        Ok(goud_skeleton_create(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("create", f_create)?;
    // Skeleton.setBoneTransform
    let f_set_bone_transform = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (i64, i64, f64, f64, f64)| {
        Ok(goud_skeleton_set_bone_transform(ctx, arg0 as u64, arg1 as i32, arg2 as f32, arg3 as f32, arg4 as f32) as i64)
    })?;
    tbl.set("set_bone_transform", f_set_bone_transform)?;
    globals.set("skeleton", tbl)?;
    Ok(())
}

pub(crate) fn register_animation_layer_stack_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("animation_layer_stack").or_else(|_| lua.create_table())?;
    // AnimationLayerStack.create
    let f_create = lua.create_function(move |_, arg0: i64| {
        Ok(goud_animation_layer_stack_create(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("create", f_create)?;
    // AnimationLayerStack.setLayerWeight
    let f_set_layer_weight = lua.create_function(move |_, (arg0, arg1, arg2): (i64, i64, f64)| {
        Ok(goud_animation_layer_set_weight(ctx, arg0 as u64, arg1 as u32, arg2 as f32) as i64)
    })?;
    tbl.set("set_layer_weight", f_set_layer_weight)?;
    // AnimationLayerStack.play
    let f_play = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_animation_layer_play(ctx, arg0 as u64, arg1 as u32) as i64)
    })?;
    tbl.set("play", f_play)?;
    // AnimationLayerStack.setClip
    let f_set_clip = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4): (i64, i64, i64, f64, i64)| {
        Ok(goud_animation_layer_set_clip(ctx, arg0 as u64, arg1 as u32, arg2 as u32, arg3 as f32, arg4 as u32) as i64)
    })?;
    tbl.set("set_clip", f_set_clip)?;
    // AnimationLayerStack.addFrame
    let f_add_frame = lua.create_function(move |_, (arg0, arg1, arg2, arg3, arg4, arg5): (i64, i64, f64, f64, f64, f64)| {
        Ok(goud_animation_layer_add_frame(ctx, arg0 as u64, arg1 as u32, arg2 as f32, arg3 as f32, arg4 as f32, arg5 as f32) as i64)
    })?;
    tbl.set("add_frame", f_add_frame)?;
    // AnimationLayerStack.resetLayer
    let f_reset_layer = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_animation_layer_reset(ctx, arg0 as u64, arg1 as u32) as i64)
    })?;
    tbl.set("reset_layer", f_reset_layer)?;
    globals.set("animation_layer_stack", tbl)?;
    Ok(())
}

pub(crate) fn register_network_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("network").or_else(|_| lua.create_table())?;
    // Network.host
    let f_host = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_network_host(ctx, arg0 as i32, arg1 as u16) as i64)
    })?;
    tbl.set("host", f_host)?;
    // Network.disconnect
    let f_disconnect = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_disconnect(ctx, arg0) as i64)
    })?;
    tbl.set("disconnect", f_disconnect)?;
    // Network.poll
    let f_poll = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_poll(ctx, arg0) as i64)
    })?;
    tbl.set("poll", f_poll)?;
    // Network.peerCount
    let f_peer_count = lua.create_function(move |_, arg0: i64| {
        Ok(goud_network_peer_count(ctx, arg0) as i64)
    })?;
    tbl.set("peer_count", f_peer_count)?;
    // Network.p2pLeaveMesh
    let f_p2p_leave_mesh = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_leave_mesh(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_leave_mesh", f_p2p_leave_mesh)?;
    // Network.p2pGetPeers
    let f_p2p_get_peers = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_get_peers(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_get_peers", f_p2p_get_peers)?;
    // Network.p2pGetHost
    let f_p2p_get_host = lua.create_function(move |_, arg0: i64| {
        Ok(goud_p2p_get_host(ctx, arg0) as i64)
    })?;
    tbl.set("p2p_get_host", f_p2p_get_host)?;
    // Network.rollbackDestroy
    let f_rollback_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_destroy(arg0) as i64)
    })?;
    tbl.set("rollback_destroy", f_rollback_destroy)?;
    // Network.rollbackShouldRollback
    let f_rollback_should_rollback = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_should_rollback(arg0) as i64)
    })?;
    tbl.set("rollback_should_rollback", f_rollback_should_rollback)?;
    // Network.rollbackResimulate
    let f_rollback_resimulate = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_resimulate(arg0) as i64)
    })?;
    tbl.set("rollback_resimulate", f_rollback_resimulate)?;
    // Network.rollbackConfirmedFrame
    let f_rollback_confirmed_frame = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_confirmed_frame(arg0) as i64)
    })?;
    tbl.set("rollback_confirmed_frame", f_rollback_confirmed_frame)?;
    // Network.rollbackCurrentFrame
    let f_rollback_current_frame = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rollback_current_frame(arg0) as i64)
    })?;
    tbl.set("rollback_current_frame", f_rollback_current_frame)?;
    // Network.rollbackCheckDesync
    let f_rollback_check_desync = lua.create_function(move |_, (arg0, arg1, arg2): (i64, i64, i64)| {
        Ok(goud_rollback_check_desync(arg0, arg1 as u64, arg2 as u64) as i64)
    })?;
    tbl.set("rollback_check_desync", f_rollback_check_desync)?;
    // Network.rpcCreate
    let f_rpc_create = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_rpc_create(arg0 as u64, arg1 as u32) as i64)
    })?;
    tbl.set("rpc_create", f_rpc_create)?;
    // Network.rpcDestroy
    let f_rpc_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_rpc_destroy(arg0) as i64)
    })?;
    tbl.set("rpc_destroy", f_rpc_destroy)?;
    // Network.rpcPoll
    let f_rpc_poll = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_rpc_poll(arg0, arg1 as f32) as i64)
    })?;
    tbl.set("rpc_poll", f_rpc_poll)?;
    globals.set("network", tbl)?;
    Ok(())
}

pub(crate) fn register_audio_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("audio").or_else(|_| lua.create_table())?;
    // Audio.stop
    let f_stop = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_stop(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("stop", f_stop)?;
    // Audio.pause
    let f_pause = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_pause(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("pause", f_pause)?;
    // Audio.resume
    let f_resume = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_resume(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("resume", f_resume)?;
    // Audio.stopAll
    let f_stop_all = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_stop_all(ctx) as i64)
    })?;
    tbl.set("stop_all", f_stop_all)?;
    // Audio.setGlobalVolume
    let f_set_global_volume = lua.create_function(move |_, arg0: f64| {
        Ok(goud_audio_set_global_volume(ctx, arg0 as f32) as i64)
    })?;
    tbl.set("set_global_volume", f_set_global_volume)?;
    // Audio.getGlobalVolume
    let f_get_global_volume = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_get_global_volume(ctx) as f64)
    })?;
    tbl.set("get_global_volume", f_get_global_volume)?;
    // Audio.setChannelVolume
    let f_set_channel_volume = lua.create_function(move |_, (arg0, arg1): (i64, f64)| {
        Ok(goud_audio_set_channel_volume(ctx, arg0 as u8, arg1 as f32) as i64)
    })?;
    tbl.set("set_channel_volume", f_set_channel_volume)?;
    // Audio.getChannelVolume
    let f_get_channel_volume = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_get_channel_volume(ctx, arg0 as u8) as f64)
    })?;
    tbl.set("get_channel_volume", f_get_channel_volume)?;
    // Audio.isPlaying
    let f_is_playing = lua.create_function(move |_, arg0: i64| {
        Ok(goud_audio_is_playing(ctx, arg0 as u64) as i64)
    })?;
    tbl.set("is_playing", f_is_playing)?;
    // Audio.activeCount
    let f_active_count = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_active_count(ctx) as i64)
    })?;
    tbl.set("active_count", f_active_count)?;
    // Audio.cleanupFinished
    let f_cleanup_finished = lua.create_function(move |_, _: ()| {
        Ok(goud_audio_cleanup_finished(ctx) as i64)
    })?;
    tbl.set("cleanup_finished", f_cleanup_finished)?;
    globals.set("audio", tbl)?;
    Ok(())
}

pub(crate) fn register_entity_pool_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("entity_pool").or_else(|_| lua.create_table())?;
    // EntityPool.destroy
    let f_destroy = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_pool_destroy(arg0 as u32) as i64)
    })?;
    tbl.set("destroy", f_destroy)?;
    // EntityPool.acquire
    let f_acquire = lua.create_function(move |_, arg0: i64| {
        Ok(goud_entity_pool_acquire(arg0 as u32) as i64)
    })?;
    tbl.set("acquire", f_acquire)?;
    // EntityPool.release
    let f_release = lua.create_function(move |_, (arg0, arg1): (i64, i64)| {
        Ok(goud_entity_pool_release(arg0 as u32, arg1 as u32) as i64)
    })?;
    tbl.set("release", f_release)?;
    globals.set("entity_pool", tbl)?;
    Ok(())
}

pub(crate) fn register_frame_arena_tools(lua: &Lua, ctx_id: u64) -> LuaResult<()> {
    let ctx = GoudContextId::from_raw(ctx_id);
    let globals = lua.globals();
    let tbl = globals.get::<LuaTable>("frame_arena").or_else(|_| lua.create_table())?;
    // FrameArena.reset
    let f_reset = lua.create_function(move |_, _: ()| {
        Ok(goud_frame_arena_reset() as i64)
    })?;
    tbl.set("reset", f_reset)?;
    globals.set("frame_arena", tbl)?;
    Ok(())
}
