/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Entity {
  constructor(index: number, generation: number)
  static placeholder(): Entity
  static fromBits(bits: bigint): Entity
  get index(): number
  get generation(): number
  get isPlaceholder(): boolean
  toBits(): bigint
  display(): string
}

export declare class GoudGame {
  constructor(config?: GameConfig | undefined | null)
  shouldClose(): boolean
  close(): void
  destroy(): boolean
  beginFrame(r?: number | undefined | null, g?: number | undefined | null, b?: number | undefined | null, a?: number | undefined | null): void
  endFrame(): void
  loadTexture(path: string): number
  destroyTexture(handle: number): boolean
  drawSprite(texture: number, x: number, y: number, w: number, h: number, rotation?: number | undefined | null, r?: number | undefined | null, g?: number | undefined | null, b?: number | undefined | null, a?: number | undefined | null): boolean
  drawSpriteRect(texture: number, x: number, y: number, w: number, h: number, rotation: number | undefined | null, srcX: number, srcY: number, srcW: number, srcH: number, r?: number | undefined | null, g?: number | undefined | null, b?: number | undefined | null, a?: number | undefined | null): boolean
  drawQuad(x: number, y: number, w: number, h: number, r?: number | undefined | null, g?: number | undefined | null, b?: number | undefined | null, a?: number | undefined | null): boolean
  setViewport(x: number, y: number, width: number, height: number): void
  enableDepthTest(): void
  disableDepthTest(): void
  clearDepth(): void
  disableBlending(): void
  getRenderStats(): NapiRenderStats
  getFpsStats(): NapiFpsStats
  setFpsOverlayEnabled(enabled: boolean): void
  setFpsUpdateInterval(interval: number): void
  setFpsOverlayCorner(corner: number): void
  isKeyPressed(key: number): boolean
  isKeyJustPressed(key: number): boolean
  isKeyJustReleased(key: number): boolean
  isMouseButtonPressed(button: number): boolean
  isMouseButtonJustPressed(button: number): boolean
  isMouseButtonJustReleased(button: number): boolean
  getMousePosition(): Array<number>
  getMouseDelta(): Array<number>
  getScrollDelta(): Array<number>
  mapActionKey(action: string, key: number): boolean
  isActionPressed(action: string): boolean
  isActionJustPressed(action: string): boolean
  isActionJustReleased(action: string): boolean
  spawnEmpty(): Entity
  spawnBatch(count: number): Array<Entity>
  despawn(entity: Entity): boolean
  entityCount(): number
  isAlive(entity: Entity): boolean
  addTransform2D(entity: Entity, data: Transform2DData): void
  getTransform2D(entity: Entity): Transform2DData | null
  setTransform2D(entity: Entity, data: Transform2DData): void
  hasTransform2D(entity: Entity): boolean
  removeTransform2D(entity: Entity): boolean
  addSprite(entity: Entity, data: SpriteData): void
  getSprite(entity: Entity): SpriteData | null
  setSprite(entity: Entity, data: SpriteData): void
  hasSprite(entity: Entity): boolean
  removeSprite(entity: Entity): boolean
  addName(entity: Entity, name: string): void
  getName(entity: Entity): string | null
  hasName(entity: Entity): boolean
  removeName(entity: Entity): boolean
  collisionAabbAabb(caX: number, caY: number, hwA: number, hhA: number, cbX: number, cbY: number, hwB: number, hhB: number): NapiContact | null
  collisionCircleCircle(caX: number, caY: number, ra: number, cbX: number, cbY: number, rb: number): NapiContact | null
  collisionCircleAabb(cx: number, cy: number, cr: number, bx: number, by: number, bhw: number, bhh: number): NapiContact | null
  pointInRect(px: number, py: number, rx: number, ry: number, rw: number, rh: number): boolean
  pointInCircle(px: number, py: number, cx: number, cy: number, cr: number): boolean
  aabbOverlap(ax1: number, ay1: number, ax2: number, ay2: number, bx1: number, by1: number, bx2: number, by2: number): boolean
  circleOverlap(x1: number, y1: number, r1: number, x2: number, y2: number, r2: number): boolean
  distance(x1: number, y1: number, x2: number, y2: number): number
  distanceSquared(x1: number, y1: number, x2: number, y2: number): number
  createCube(textureId: number, width: number, height: number, depth: number): number
  createPlane(textureId: number, width: number, depth: number): number
  createSphere(textureId: number, diameter: number, segments: number): number
  createCylinder(textureId: number, radius: number, height: number, segments: number): number
  setObjectPosition(id: number, x: number, y: number, z: number): boolean
  setObjectRotation(id: number, x: number, y: number, z: number): boolean
  setObjectScale(id: number, x: number, y: number, z: number): boolean
  destroyObject(id: number): boolean
  addLight(lt: number, px: number, py: number, pz: number, dx: number, dy: number, dz: number, r: number, g: number, b: number, intensity: number, range: number, spotAngle: number): number
  updateLight(lid: number, lt: number, px: number, py: number, pz: number, dx: number, dy: number, dz: number, r: number, g: number, b: number, intensity: number, range: number, spotAngle: number): boolean
  removeLight(lid: number): boolean
  setCameraPosition3D(x: number, y: number, z: number): boolean
  setCameraRotation3D(pitch: number, yaw: number, roll: number): boolean
  configureGrid(enabled: boolean, size: number, divisions: number): boolean
  setGridEnabled(enabled: boolean): boolean
  configureSkybox(enabled: boolean, r: number, g: number, b: number, a: number): boolean
  configureFog(enabled: boolean, r: number, g: number, b: number, density: number): boolean
  setFogEnabled(enabled: boolean): boolean
  render3D(): boolean
  get deltaTime(): number
  get fps(): number
  updateFrame(dt: number): void
  get title(): string
  get frameCount(): number
  get totalTime(): number
  get windowWidth(): number
  get windowHeight(): number
  get contextValid(): boolean
  /** Returns the raw FFI delta time from the last poll_events call. */
  get ffiDeltaTime(): number
}

export interface Color {
  r: number
  g: number
  b: number
  a: number
}

export declare function colorBlack(): Color

export declare function colorBlue(): Color

export declare function colorCyan(): Color

export declare function colorFromHex(hex: number): Color

export declare function colorFromU8(r: number, g: number, b: number, a: number): Color

export declare function colorGreen(): Color

export declare function colorMagenta(): Color

export declare function colorRed(): Color

export declare function colorRgb(r: number, g: number, b: number): Color

export declare function colorRgba(r: number, g: number, b: number, a: number): Color

export declare function colorTransparent(): Color

export declare function colorWhite(): Color

export declare function colorYellow(): Color

export interface GameConfig {
  title?: string
  width?: number
  height?: number
}

export interface NapiContact {
  pointX: number
  pointY: number
  normalX: number
  normalY: number
  penetration: number
}

export interface NapiFpsStats {
  currentFps: number
  minFps: number
  maxFps: number
  avgFps: number
  frameTimeMs: number
}

export interface NapiRenderStats {
  drawCalls: number
  triangles: number
  textureBinds: number
  shaderBinds: number
}

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface SpriteData {
  color: Color
  flipX: boolean
  flipY: boolean
  anchorX: number
  anchorY: number
  customWidth?: number
  customHeight?: number
  sourceRectX?: number
  sourceRectY?: number
  sourceRectWidth?: number
  sourceRectHeight?: number
}

export declare function spriteDefault(): SpriteData

export interface Transform2DData {
  positionX: number
  positionY: number
  rotation: number
  scaleX: number
  scaleY: number
}

export declare function transform2DDefault(): Transform2DData

export declare function transform2DFromPosition(x: number, y: number): Transform2DData

export declare function transform2DFromRotation(radians: number): Transform2DData

export declare function transform2DFromScale(x: number, y: number): Transform2DData

export declare function vec2(x: number, y: number): Vec2

export interface Vec2 {
  x: number
  y: number
}

export declare function vec2One(): Vec2

export declare function vec2Zero(): Vec2

export interface Vec3 {
  x: number
  y: number
  z: number
}
