// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Data for a fired animation event read from the event queue */
data class AnimationEventData(val entity: Long, val name: String, val frameIndex: Int, val payloadType: Int, val payloadInt: Int, val payloadFloat: Float, val payloadString: String) {
}
