// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Statistics about a packed texture atlas */
data class AtlasStats(val textureCount: Int, val width: Int, val height: Int, val usedPixels: Long, val totalPixels: Long, val efficiency: Float, val wastedPixels: Long) {
}
