// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class DebuggerConfig(val enabled: Boolean, val publishLocalAttach: Boolean, val routeLabel: String) {
}
