// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class InputCapabilities(val supportsGamepad: Boolean, val supportsTouch: Boolean, val maxGamepads: Int) {
}
