// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Tracked current and peak bytes for one debugger memory category. */
data class MemoryCategoryStats(val currentBytes: Long, val peakBytes: Long) {
}
