// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class NetworkSimulationConfig(val oneWayLatencyMs: Int, val jitterMs: Int, val packetLossPercent: Float) {
}
