// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Capabilities reported by the active network provider */
data class NetworkCapabilities(val supportsHosting: Boolean, val maxConnections: Int, val maxChannels: Int, val maxMessageSize: Int) {
}
