// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class NetworkStats(val bytesSent: Long, val bytesReceived: Long, val packetsSent: Long, val packetsReceived: Long, val packetsLost: Long, val rttMs: Float, val sendBandwidthBytesPerSec: Float, val receiveBandwidthBytesPerSec: Float, val packetLossPercent: Float, val jitterMs: Float) {
}
