// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Peer-preserving connection result returned by networkConnectWithPeer */
data class NetworkConnectResult(val handle: Long, val peerId: Long) {
}
