// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Configuration for P2P mesh networking */
data class P2pMeshConfig(val maxPeers: Int, val hostMigration: Boolean, val topology: Int) {
}
