// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class PhysicsCapabilities(val supportsContinuousCollision: Boolean, val supportsJoints: Boolean, val maxBodies: Int) {
}
