// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Diagnostic statistics snapshot for an entity pool */
data class PoolStats(val capacity: Int, val active: Int, val available: Int, val highWaterMark: Int, val totalAcquires: Long, val totalReleases: Long) {
}
