// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

import com.goudengine.internal.Rect as JavaRect

data class Rect(val x: Float, val y: Float, val width: Float, val height: Float) {

    fun contains(p: Vec2): Boolean = p.x >= x && p.x <= x + width && p.y >= y && p.y <= y + height
    fun intersects(o: Rect): Boolean = x < o.x + o.width && x + width > o.x && y < o.y + o.height && y + height > o.y

    fun toNative(): JavaRect = JavaRect(x, y, width, height)

    companion object {
        fun fromNative(n: JavaRect): Rect = Rect(n.x, n.y, n.width, n.height)
    }
}
