// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

data class RenderCapabilities(val maxTextureUnits: Int, val maxTextureSize: Int, val supportsInstancing: Boolean, val supportsCompute: Boolean, val supportsMsaa: Boolean) {
}
