// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

import com.goudengine.internal.RollbackConfig as JavaRollbackConfig

/** Configuration for rollback netcode session */
data class RollbackConfig(val maxRollbackFrames: Int, val inputDelayFrames: Int, val desyncDetection: Int) {

    fun toNative(): JavaRollbackConfig = JavaRollbackConfig(maxRollbackFrames, inputDelayFrames, desyncDetection)

    companion object {
        fun fromNative(n: JavaRollbackConfig): RollbackConfig = RollbackConfig(n.maxRollbackFrames, n.inputDelayFrames, n.desyncDetection)
    }
}
