// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Describes a single sprite for batched rendering via DrawSpriteBatch */
data class SpriteCmd(val texture: Long, val x: Float, val y: Float, val width: Float, val height: Float, val rotation: Float, val srcX: Float, val srcY: Float, val srcW: Float, val srcH: Float, val r: Float, val g: Float, val b: Float, val a: Float, val zLayer: Int) {
}
