// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** Describes a single text draw command for batched rendering via DrawTextBatch */
data class TextCmd(val fontHandle: Long, val x: Float, val y: Float, val fontSize: Float, val maxWidth: Float, val lineSpacing: Float, val r: Float, val g: Float, val b: Float, val a: Float) {
}
