// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

/** UI event payload returned by deterministic polling APIs. */
data class UiEvent(val eventKind: Int, val nodeId: Long, val previousNodeId: Long, val currentNodeId: Long) {
}
