// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

import com.goudengine.internal.Vec2 as JavaVec2

/** 2D floating-point vector */
data class Vec2(val x: Float, val y: Float) {

    fun add(other: Vec2): Vec2 = Vec2(x + other.x, y + other.y)
    fun sub(other: Vec2): Vec2 = Vec2(x - other.x, y - other.y)
    fun scale(s: Float): Vec2 = Vec2(x * s, y * s)
    fun length(): Float = kotlin.math.sqrt(x * x + y * y)
    fun normalize(): Vec2 { val l = length(); return if (l == 0f) zero() else Vec2(x / l, y / l) }
    fun dot(other: Vec2): Float = x * other.x + y * other.y
    fun distance(other: Vec2): Float = sub(other).length()
    fun lerp(other: Vec2, t: Float): Vec2 = Vec2(x + (other.x - x) * t, y + (other.y - y) * t)

    fun toNative(): JavaVec2 = JavaVec2(x, y)

    companion object {
        fun zero(): Vec2 = Vec2(0f, 0f)
        fun one(): Vec2 = Vec2(1f, 1f)
        fun up(): Vec2 = Vec2(0f, -1f)
        fun down(): Vec2 = Vec2(0f, 1f)
        fun left(): Vec2 = Vec2(-1f, 0f)
        fun right(): Vec2 = Vec2(1f, 0f)
        fun fromNative(n: JavaVec2): Vec2 = Vec2(n.x, n.y)
    }
}
