// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.types

import com.goudengine.internal.Vec3 as JavaVec3

data class Vec3(val x: Float, val y: Float, val z: Float) {

    fun toNative(): JavaVec3 = JavaVec3(x, y, z)

    companion object {
        fun zero(): Vec3 = Vec3(0f, 0f, 0f)
        fun one(): Vec3 = Vec3(1f, 1f, 1f)
        fun up(): Vec3 = Vec3(0f, 1f, 0f)
        fun fromNative(n: JavaVec3): Vec3 = Vec3(n.x, n.y, n.z)
    }
}
