// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.components

import com.goudengine.internal.SpriteAnimatorBuilderNative
import com.goudengine.internal.SpriteAnimator as JavaSpriteAnimator

class SpriteAnimatorBuilder private constructor(private var handle: Long) : AutoCloseable {

    fun addFrame(x: Float, y: Float, w: Float, h: Float): SpriteAnimatorBuilder {
        handle = SpriteAnimatorBuilderNative.addFrame(handle, x, y, w, h)
        return this
    }

    fun build(): SpriteAnimator {
        val result = SpriteAnimatorBuilderNative.build(handle)
        handle = 0L
        return SpriteAnimator(result)
    }

    fun free() {
        if (handle != 0L) { SpriteAnimatorBuilderNative.free(handle); handle = 0L }
    }

    override fun close() = free()

    companion object {
        fun new(frameDuration: Float, mode: PlaybackMode): SpriteAnimatorBuilder =
            SpriteAnimatorBuilder(SpriteAnimatorBuilderNative.create(frameDuration, mode))

    }
}
