// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.components

import com.goudengine.internal.SpriteAnimator
import com.goudengine.internal.SpriteAnimatorNative
import com.goudengine.types.Vec2 as KtVec2
import com.goudengine.types.Color as KtColor

class SpriteAnimator(internal var native: com.goudengine.internal.SpriteAnimator) {

    var currentFrame: Int
        get() = native.currentFrame
        set(value) { native.currentFrame = value }

    var elapsed: Float
        get() = native.elapsed
        set(value) { native.elapsed = value }

    var playing: Boolean
        get() = native.playing
        set(value) { native.playing = value }

    var finished: Boolean
        get() = native.finished
        set(value) { native.finished = value }

    var frameDuration: Float
        get() = native.frameDuration
        set(value) { native.frameDuration = value }

    var mode: PlaybackMode
        get() = native.mode
        set(value) { native.mode = value }

    var frameCount: Int
        get() = native.frameCount
        set(value) { native.frameCount = value }

    fun getCurrentFrame(): Int {
        return SpriteAnimatorNative.getCurrentFrame(native)
    }

    fun isPlaying(): Boolean {
        return SpriteAnimatorNative.isPlaying(native)
    }

    fun isFinished(): Boolean {
        return SpriteAnimatorNative.isFinished(native)
    }

    override fun toString(): String =
        "SpriteAnimator(${currentFrame}, ${elapsed}, ${playing}, ${finished}, ${frameDuration}, ${mode}, ${frameCount})"
}
