// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.components

import com.goudengine.internal.Text
import com.goudengine.internal.TextNative
import com.goudengine.types.Vec2 as KtVec2
import com.goudengine.types.Color as KtColor

class Text(internal var native: com.goudengine.internal.Text) {

    var fontHandle: Long
        get() = native.fontHandle
        set(value) { native.fontHandle = value }

    var fontSize: Float
        get() = native.fontSize
        set(value) { native.fontSize = value }

    var colorR: Float
        get() = native.colorR
        set(value) { native.colorR = value }

    var colorG: Float
        get() = native.colorG
        set(value) { native.colorG = value }

    var colorB: Float
        get() = native.colorB
        set(value) { native.colorB = value }

    var colorA: Float
        get() = native.colorA
        set(value) { native.colorA = value }

    var alignment: Int
        get() = native.alignment
        set(value) { native.alignment = value }

    var maxWidth: Float
        get() = native.maxWidth
        set(value) { native.maxWidth = value }

    var hasMaxWidth: Boolean
        get() = native.hasMaxWidth
        set(value) { native.hasMaxWidth = value }

    var lineSpacing: Float
        get() = native.lineSpacing
        set(value) { native.lineSpacing = value }

    companion object {
        fun new(fontHandle: Long): Text =
            Text(TextNative.create(fontHandle))

        fun default(): Text =
            Text(TextNative.defaultValue())

    }

    fun setFontSize(size: Float) {
        TextNative.setFontSize(native, size)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun getFontSize(): Float {
        return TextNative.getFontSize(native)
    }

    fun setColor(r: Float, g: Float, b: Float, a: Float) {
        TextNative.setColor(native, r, g, b, a)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun getColorR(): Float {
        return TextNative.getColorR(native)
    }

    fun getColorG(): Float {
        return TextNative.getColorG(native)
    }

    fun getColorB(): Float {
        return TextNative.getColorB(native)
    }

    fun getColorA(): Float {
        return TextNative.getColorA(native)
    }

    fun setAlignment(alignment: Int) {
        TextNative.setAlignment(native, alignment)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun getAlignment(): Int {
        return TextNative.getAlignment(native)
    }

    fun setMaxWidth(width: Float) {
        TextNative.setMaxWidth(native, width)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun clearMaxWidth() {
        TextNative.clearMaxWidth(native)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun getMaxWidth(): Float {
        return TextNative.getMaxWidth(native)
    }

    fun hasMaxWidth(): Boolean {
        return TextNative.hasMaxWidth(native)
    }

    fun setLineSpacing(spacing: Float) {
        TextNative.setLineSpacing(native, spacing)
        val n = native
        this.fontHandle = n.fontHandle
        this.fontSize = n.fontSize
        this.colorR = n.colorR
        this.colorG = n.colorG
        this.colorB = n.colorB
        this.colorA = n.colorA
        this.alignment = n.alignment
        this.maxWidth = n.maxWidth
        this.hasMaxWidth = n.hasMaxWidth
        this.lineSpacing = n.lineSpacing
    }

    fun getLineSpacing(): Float {
        return TextNative.getLineSpacing(native)
    }

    override fun toString(): String =
        "Text(${fontHandle}, ${fontSize}, ${colorR}, ${colorG}, ${colorB}, ${colorA}, ${alignment}, ${maxWidth}, ${hasMaxWidth}, ${lineSpacing})"
}
