// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.components

import com.goudengine.internal.Transform2DBuilderNative
import com.goudengine.internal.Transform2D as JavaTransform2D

class Transform2DBuilder private constructor(private var handle: Long) : AutoCloseable {

    fun withPosition(x: Float, y: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.withPosition(handle, x, y)
        return this
    }

    fun withRotation(rotation: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.withRotation(handle, rotation)
        return this
    }

    fun withRotationDegrees(degrees: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.withRotationDegrees(handle, degrees)
        return this
    }

    fun withScale(scaleX: Float, scaleY: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.withScale(handle, scaleX, scaleY)
        return this
    }

    fun withScaleUniform(scale: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.withScaleUniform(handle, scale)
        return this
    }

    fun lookingAt(targetX: Float, targetY: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.lookingAt(handle, targetX, targetY)
        return this
    }

    fun translate(dx: Float, dy: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.translate(handle, dx, dy)
        return this
    }

    fun rotate(angle: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.rotate(handle, angle)
        return this
    }

    fun scaleBy(factorX: Float, factorY: Float): Transform2DBuilder {
        handle = Transform2DBuilderNative.scaleBy(handle, factorX, factorY)
        return this
    }

    fun build(): Transform2D {
        val result = Transform2DBuilderNative.build(handle)
        handle = 0L
        return Transform2D(result)
    }

    fun free() {
        if (handle != 0L) { Transform2DBuilderNative.free(handle); handle = 0L }
    }

    override fun close() = free()

    companion object {
        fun new(): Transform2DBuilder =
            Transform2DBuilder(Transform2DBuilderNative.create())

        fun atPosition(x: Float, y: Float): Transform2DBuilder =
            Transform2DBuilder(Transform2DBuilderNative.atPosition(x, y))

    }
}
