// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.components

import com.goudengine.internal.Mat3x3
import com.goudengine.internal.Transform2D as JavaTransform2D
import com.goudengine.internal.Transform2DNative
import com.goudengine.internal.Vec2
import com.goudengine.types.Vec2 as KtVec2
import com.goudengine.types.Color as KtColor

/** 2D transform: position, rotation (radians), and scale */
class Transform2D(internal var native: JavaTransform2D) {

    var positionX: Float
        get() = native.positionX
        set(value) { native.positionX = value }

    var positionY: Float
        get() = native.positionY
        set(value) { native.positionY = value }

    var rotation: Float
        get() = native.rotation
        set(value) { native.rotation = value }

    var scaleX: Float
        get() = native.scaleX
        set(value) { native.scaleX = value }

    var scaleY: Float
        get() = native.scaleY
        set(value) { native.scaleY = value }

    companion object {
        fun default(): Transform2D =
            Transform2D(Transform2DNative.defaultValue())

        fun fromPosition(x: Float, y: Float): Transform2D =
            Transform2D(Transform2DNative.fromPosition(x, y))

        fun fromRotation(radians: Float): Transform2D =
            Transform2D(Transform2DNative.fromRotation(radians))

        fun fromRotationDegrees(degrees: Float): Transform2D =
            Transform2D(Transform2DNative.fromRotationDegrees(degrees))

        fun fromScale(x: Float, y: Float): Transform2D =
            Transform2D(Transform2DNative.fromScale(x, y))

        fun fromScaleUniform(scale: Float): Transform2D =
            Transform2D(Transform2DNative.fromScaleUniform(scale))

        fun fromPositionRotation(x: Float, y: Float, rotation: Float): Transform2D =
            Transform2D(Transform2DNative.fromPositionRotation(x, y, rotation))

        fun new(posX: Float, posY: Float, rotation: Float, scaleX: Float, scaleY: Float): Transform2D =
            Transform2D(Transform2DNative.create(posX, posY, rotation, scaleX, scaleY))

        fun lookAt(posX: Float, posY: Float, targetX: Float, targetY: Float): Transform2D =
            Transform2D(Transform2DNative.lookAt(posX, posY, targetX, targetY))

    }

    fun translate(dx: Float, dy: Float) {
        Transform2DNative.translate(native, dx, dy)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun translateLocal(dx: Float, dy: Float) {
        Transform2DNative.translateLocal(native, dx, dy)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun setPosition(x: Float, y: Float) {
        Transform2DNative.setPosition(native, x, y)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun getPosition(): KtVec2 {
        val r = Transform2DNative.getPosition(native)
        return KtVec2(r.x, r.y)
    }

    fun rotate(angle: Float) {
        Transform2DNative.rotate(native, angle)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun rotateDegrees(degrees: Float) {
        Transform2DNative.rotateDegrees(native, degrees)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun setRotationDegrees(degrees: Float) {
        Transform2DNative.setRotationDegrees(native, degrees)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun getRotationDegrees(): Float {
        return Transform2DNative.getRotationDegrees(native)
    }

    fun lookAtTarget(targetX: Float, targetY: Float) {
        Transform2DNative.lookAtTarget(native, targetX, targetY)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun setScale(scaleX: Float, scaleY: Float) {
        Transform2DNative.setScale(native, scaleX, scaleY)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun setScaleUniform(scale: Float) {
        Transform2DNative.setScaleUniform(native, scale)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun getScale(): KtVec2 {
        val r = Transform2DNative.getScale(native)
        return KtVec2(r.x, r.y)
    }

    fun scaleBy(factorX: Float, factorY: Float) {
        Transform2DNative.scaleBy(native, factorX, factorY)
        val n = native
        this.positionX = n.positionX
        this.positionY = n.positionY
        this.rotation = n.rotation
        this.scaleX = n.scaleX
        this.scaleY = n.scaleY
    }

    fun forward(): KtVec2 {
        val r = Transform2DNative.forward(native)
        return KtVec2(r.x, r.y)
    }

    fun right(): KtVec2 {
        val r = Transform2DNative.right(native)
        return KtVec2(r.x, r.y)
    }

    fun backward(): KtVec2 {
        val r = Transform2DNative.backward(native)
        return KtVec2(r.x, r.y)
    }

    fun left(): KtVec2 {
        val r = Transform2DNative.left(native)
        return KtVec2(r.x, r.y)
    }

    fun matrix(): com.goudengine.internal.Mat3x3 {
        return Transform2DNative.matrix(native)
    }

    fun matrixInverse(): com.goudengine.internal.Mat3x3 {
        return Transform2DNative.matrixInverse(native)
    }

    fun transformPoint(pointX: Float, pointY: Float): KtVec2 {
        val r = Transform2DNative.transformPoint(native, pointX, pointY)
        return KtVec2(r.x, r.y)
    }

    fun transformDirection(dirX: Float, dirY: Float): KtVec2 {
        val r = Transform2DNative.transformDirection(native, dirX, dirY)
        return KtVec2(r.x, r.y)
    }

    fun inverseTransformPoint(pointX: Float, pointY: Float): KtVec2 {
        val r = Transform2DNative.inverseTransformPoint(native, pointX, pointY)
        return KtVec2(r.x, r.y)
    }

    fun inverseTransformDirection(dirX: Float, dirY: Float): KtVec2 {
        val r = Transform2DNative.inverseTransformDirection(native, dirX, dirY)
        return KtVec2(r.x, r.y)
    }

    fun lerp(to: Transform2D, t: Float): Transform2D {
        return Transform2D(Transform2DNative.lerp(native, to.native, t))
    }


    fun normalizeAngle(angle: Float): Float =
        Transform2DNative.normalizeAngle(angle)

    override fun toString(): String =
        "Transform2D(${positionX}, ${positionY}, ${rotation}, ${scaleX}, ${scaleY})"
}
