"""Generator for `internal/ffi/helpers.go` -- Go-native bridge functions.

The goud wrapper package cannot use C.* types because cgo types are
package-scoped. This file generates bridge functions that accept/return
only Go-native types and handle C type conversions internally.
"""

from .context import GO_HEADER, HELPERS_OUT, schema, mapping, write_generated



def gen_helpers() -> None:
    lines = [
        GO_HEADER,
        "",
        "package ffi",
        "",
        "// #include \"goud_engine.h\"",
        "// #include <stdlib.h>",
        'import "C"',
        'import "unsafe"',
        "",
        "// ---- Context helpers ----",
        "",
        "// ContextBits is the raw uint64 representation of a context ID.",
        "type ContextBits uint64",
        "",
        "// InvalidContext is the sentinel value for an invalid context.",
        "const InvalidContext ContextBits = 0xFFFFFFFFFFFFFFFF",
        "",
        "// ctxFromBits converts uint64 bits to C.GoudContextId.",
        "func ctxFromBits(bits ContextBits) C.GoudContextId {",
        "\treturn C.GoudContextId{_0: C.uint64_t(bits)}",
        "}",
        "",
        "// ctxToBits converts C.GoudContextId to uint64 bits.",
        "func ctxToBits(ctx C.GoudContextId) ContextBits {",
        "\treturn ContextBits(ctx._0)",
        "}",
        "",
        "// ---- Byte/buffer helpers ----",
        "",
        "// ReadErrorBuffer calls a buffer-writing FFI error function and returns string.",
        "func ReadErrorBuffer(fn func(*C.uint8_t, C.size_t) C.int32_t) string {",
        "\tvar buf [256]C.uint8_t",
        "\twritten := fn(&buf[0], 256)",
        "\tif written <= 0 {",
        '\t\treturn ""',
        "\t}",
        "\treturn C.GoStringN((*C.char)(unsafe.Pointer(&buf[0])), written)",
        "}",
        "",
    ]

    # Now generate Go-native bridge functions for commonly used FFI calls.
    # These wrap the raw cgo calls with Go types.
    _gen_window_bridges(lines)
    _gen_renderer_bridges(lines)
    _gen_input_bridges(lines)
    _gen_texture_bridges(lines)
    _gen_font_bridges(lines)
    _gen_entity_bridges(lines)
    _gen_audio_bridges(lines)
    _gen_error_bridges(lines)
    _gen_component_bridges(lines)

    write_generated(HELPERS_OUT / "helpers.go", "\n".join(lines))


def _gen_window_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Window bridges ----",
        "",
        "// WindowCreate creates a new window and returns context bits.",
        "func WindowCreate(width, height uint32, title string) ContextBits {",
        "\tcs := C.CString(title)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\tctx := C.goud_window_create(C.uint32_t(width), C.uint32_t(height), cs)",
        "\treturn ctxToBits(ctx)",
        "}",
        "",
        "// WindowDestroy destroys a window.",
        "func WindowDestroy(bits ContextBits) bool {",
        "\treturn bool(C.goud_window_destroy(ctxFromBits(bits)))",
        "}",
        "",
        "// WindowShouldClose returns true if the window should close.",
        "func WindowShouldClose(bits ContextBits) bool {",
        "\treturn bool(C.goud_window_should_close(ctxFromBits(bits)))",
        "}",
        "",
        "// WindowSetShouldClose sets whether the window should close.",
        "func WindowSetShouldClose(bits ContextBits, shouldClose bool) {",
        "\tC.goud_window_set_should_close(ctxFromBits(bits), C.bool(shouldClose))",
        "}",
        "",
        "// WindowPollEvents polls input events and returns delta time.",
        "func WindowPollEvents(bits ContextBits) float32 {",
        "\treturn float32(C.goud_window_poll_events(ctxFromBits(bits)))",
        "}",
        "",
        "// WindowClear clears the window with a color.",
        "func WindowClear(bits ContextBits, r, g, b, a float32) {",
        "\tC.goud_window_clear(ctxFromBits(bits), C.float(r), C.float(g), C.float(b), C.float(a))",
        "}",
        "",
        "// WindowSwapBuffers swaps the front and back buffers.",
        "func WindowSwapBuffers(bits ContextBits) {",
        "\tC.goud_window_swap_buffers(ctxFromBits(bits))",
        "}",
        "",
        "// WindowSetSize sets the window size.",
        "func WindowSetSize(bits ContextBits, width, height uint32) bool {",
        "\treturn bool(C.goud_window_set_size(ctxFromBits(bits), C.uint32_t(width), C.uint32_t(height)))",
        "}",
        "",
        "// WindowGetSize gets the window size.",
        "func WindowGetSize(bits ContextBits) (uint32, uint32) {",
        "\tvar w, h C.uint32_t",
        "\tC.goud_window_get_size(ctxFromBits(bits), &w, &h)",
        "\treturn uint32(w), uint32(h)",
        "}",
        "",
    ])


def _gen_renderer_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Renderer bridges ----",
        "",
        "// RendererBegin begins a render pass.",
        "func RendererBegin(bits ContextBits) bool {",
        "\treturn bool(C.goud_renderer_begin(ctxFromBits(bits)))",
        "}",
        "",
        "// RendererEnd ends a render pass.",
        "func RendererEnd(bits ContextBits) bool {",
        "\treturn bool(C.goud_renderer_end(ctxFromBits(bits)))",
        "}",
        "",
        "// RendererEnableBlending enables alpha blending.",
        "func RendererEnableBlending(bits ContextBits) {",
        "\tC.goud_renderer_enable_blending(ctxFromBits(bits))",
        "}",
        "",
        "// RendererDisableBlending disables alpha blending.",
        "func RendererDisableBlending(bits ContextBits) {",
        "\tC.goud_renderer_disable_blending(ctxFromBits(bits))",
        "}",
        "",
        "// RendererDrawSprite draws a textured sprite.",
        "func RendererDrawSprite(bits ContextBits, texture uint64, x, y, width, height, rotation, r, g, b, a float32) bool {",
        "\treturn bool(C.goud_renderer_draw_sprite(ctxFromBits(bits), C.GoudTextureHandle(texture), C.float(x), C.float(y), C.float(width), C.float(height), C.float(rotation), C.float(r), C.float(g), C.float(b), C.float(a)))",
        "}",
        "",
        "// RendererDrawSpriteRect draws a sprite with a source rectangle.",
        "func RendererDrawSpriteRect(bits ContextBits, texture uint64, x, y, width, height, rotation, srcX, srcY, srcW, srcH, r, g, b, a float32) bool {",
        "\treturn bool(C.goud_renderer_draw_sprite_rect(ctxFromBits(bits), C.GoudTextureHandle(texture), C.float(x), C.float(y), C.float(width), C.float(height), C.float(rotation), C.float(srcX), C.float(srcY), C.float(srcW), C.float(srcH), C.float(r), C.float(g), C.float(b), C.float(a)))",
        "}",
        "",
        "// RendererDrawQuad draws a colored rectangle.",
        "func RendererDrawQuad(bits ContextBits, x, y, width, height, r, g, b, a float32) bool {",
        "\treturn bool(C.goud_renderer_draw_quad(ctxFromBits(bits), C.float(x), C.float(y), C.float(width), C.float(height), C.float(r), C.float(g), C.float(b), C.float(a)))",
        "}",
        "",
        "// RendererDrawText draws text.",
        "func RendererDrawText(bits ContextBits, fontHandle uint64, text string, x, y, fontSize float32, alignment uint8, maxWidth, lineSpacing float32, direction uint8, r, g, b, a float32) bool {",
        "\tcs := C.CString(text)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn bool(C.goud_renderer_draw_text(ctxFromBits(bits), C.GoudFontHandle(fontHandle), cs, C.float(x), C.float(y), C.float(fontSize), C.uint8_t(alignment), C.float(maxWidth), C.float(lineSpacing), C.uint8_t(direction), C.float(r), C.float(g), C.float(b), C.float(a)))",
        "}",
        "",
        "// RendererSetViewport sets the rendering viewport.",
        "func RendererSetViewport(bits ContextBits, x, y int32, width, height uint32) {",
        "\tC.goud_renderer_set_viewport(ctxFromBits(bits), C.int32_t(x), C.int32_t(y), C.uint32_t(width), C.uint32_t(height))",
        "}",
        "",
        "// RendererEnableDepthTest enables depth testing.",
        "func RendererEnableDepthTest(bits ContextBits) {",
        "\tC.goud_renderer_enable_depth_test(ctxFromBits(bits))",
        "}",
        "",
        "// RendererDisableDepthTest disables depth testing.",
        "func RendererDisableDepthTest(bits ContextBits) {",
        "\tC.goud_renderer_disable_depth_test(ctxFromBits(bits))",
        "}",
        "",
        "// RendererClearDepth clears the depth buffer.",
        "func RendererClearDepth(bits ContextBits) {",
        "\tC.goud_renderer_clear_depth(ctxFromBits(bits))",
        "}",
        "",
    ])


def _gen_input_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Input bridges ----",
        "",
        "// InputKeyPressed returns true if a key is currently held down.",
        "func InputKeyPressed(bits ContextBits, key int32) bool {",
        "\treturn bool(C.goud_input_key_pressed(ctxFromBits(bits), C.GoudKeyCode(key)))",
        "}",
        "",
        "// InputKeyJustPressed returns true if a key was pressed this frame.",
        "func InputKeyJustPressed(bits ContextBits, key int32) bool {",
        "\treturn bool(C.goud_input_key_just_pressed(ctxFromBits(bits), C.GoudKeyCode(key)))",
        "}",
        "",
        "// InputKeyJustReleased returns true if a key was released this frame.",
        "func InputKeyJustReleased(bits ContextBits, key int32) bool {",
        "\treturn bool(C.goud_input_key_just_released(ctxFromBits(bits), C.GoudKeyCode(key)))",
        "}",
        "",
        "// InputMouseButtonPressed returns true if a mouse button is held.",
        "func InputMouseButtonPressed(bits ContextBits, button int32) bool {",
        "\treturn bool(C.goud_input_mouse_button_pressed(ctxFromBits(bits), C.GoudMouseButton(button)))",
        "}",
        "",
        "// InputMouseButtonJustPressed returns true if a mouse button was pressed this frame.",
        "func InputMouseButtonJustPressed(bits ContextBits, button int32) bool {",
        "\treturn bool(C.goud_input_mouse_button_just_pressed(ctxFromBits(bits), C.GoudMouseButton(button)))",
        "}",
        "",
        "// InputMouseButtonJustReleased returns true if a mouse button was released this frame.",
        "func InputMouseButtonJustReleased(bits ContextBits, button int32) bool {",
        "\treturn bool(C.goud_input_mouse_button_just_released(ctxFromBits(bits), C.GoudMouseButton(button)))",
        "}",
        "",
        "// InputGetMousePosition returns the current mouse position.",
        "func InputGetMousePosition(bits ContextBits) (float32, float32) {",
        "\tvar x, y C.float",
        "\tC.goud_input_get_mouse_position(ctxFromBits(bits), &x, &y)",
        "\treturn float32(x), float32(y)",
        "}",
        "",
        "// InputGetMouseDelta returns the mouse movement delta.",
        "func InputGetMouseDelta(bits ContextBits) (float32, float32) {",
        "\tvar dx, dy C.float",
        "\tC.goud_input_get_mouse_delta(ctxFromBits(bits), &dx, &dy)",
        "\treturn float32(dx), float32(dy)",
        "}",
        "",
        "// InputGetScrollDelta returns the scroll delta.",
        "func InputGetScrollDelta(bits ContextBits) (float32, float32) {",
        "\tvar dx, dy C.float",
        "\tC.goud_input_get_scroll_delta(ctxFromBits(bits), &dx, &dy)",
        "\treturn float32(dx), float32(dy)",
        "}",
        "",
        "// InputMapActionKey maps an action name to a key code.",
        "func InputMapActionKey(bits ContextBits, actionName string, key int32) bool {",
        "\tcs := C.CString(actionName)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn bool(C.goud_input_map_action_key(ctxFromBits(bits), cs, C.GoudKeyCode(key)))",
        "}",
        "",
        "// InputActionPressed returns true if a named action is held.",
        "func InputActionPressed(bits ContextBits, actionName string) bool {",
        "\tcs := C.CString(actionName)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn bool(C.goud_input_action_pressed(ctxFromBits(bits), cs))",
        "}",
        "",
        "// InputActionJustPressed returns true if a named action was pressed this frame.",
        "func InputActionJustPressed(bits ContextBits, actionName string) bool {",
        "\tcs := C.CString(actionName)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn bool(C.goud_input_action_just_pressed(ctxFromBits(bits), cs))",
        "}",
        "",
        "// InputActionJustReleased returns true if a named action was released this frame.",
        "func InputActionJustReleased(bits ContextBits, actionName string) bool {",
        "\tcs := C.CString(actionName)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn bool(C.goud_input_action_just_released(ctxFromBits(bits), cs))",
        "}",
        "",
    ])


def _gen_texture_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Texture bridges ----",
        "",
        "// TextureLoad loads a texture from a file path and returns its handle.",
        "func TextureLoad(bits ContextBits, path string) uint64 {",
        "\tcs := C.CString(path)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn uint64(C.goud_texture_load(ctxFromBits(bits), cs))",
        "}",
        "",
        "// TextureDestroy destroys a texture.",
        "func TextureDestroy(bits ContextBits, handle uint64) bool {",
        "\treturn bool(C.goud_texture_destroy(ctxFromBits(bits), C.GoudTextureHandle(handle)))",
        "}",
        "",
    ])


def _gen_font_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Font bridges ----",
        "",
        "// FontLoad loads a font from a file path and returns its handle.",
        "func FontLoad(bits ContextBits, path string) uint64 {",
        "\tcs := C.CString(path)",
        "\tdefer C.free(unsafe.Pointer(cs))",
        "\treturn uint64(C.goud_font_load(ctxFromBits(bits), cs))",
        "}",
        "",
        "// FontDestroy destroys a font.",
        "func FontDestroy(bits ContextBits, handle uint64) bool {",
        "\treturn bool(C.goud_font_destroy(ctxFromBits(bits), C.GoudFontHandle(handle)))",
        "}",
        "",
    ])


def _gen_entity_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Entity bridges ----",
        "",
        "// EntitySpawnEmpty creates a new empty entity.",
        "func EntitySpawnEmpty(bits ContextBits) uint64 {",
        "\treturn uint64(C.goud_entity_spawn_empty(ctxFromBits(bits)))",
        "}",
        "",
        "// EntityDespawn destroys an entity.",
        "func EntityDespawn(bits ContextBits, entityID uint64) int32 {",
        "\tresult := C.goud_entity_despawn(ctxFromBits(bits), C.uint64_t(entityID))",
        "\tif result.success {",
        "\t\treturn 0",
        "\t}",
        "\treturn -1",
        "}",
        "",
        "// EntityIsAlive returns true if an entity is alive.",
        "func EntityIsAlive(bits ContextBits, entityID uint64) bool {",
        "\treturn bool(C.goud_entity_is_alive(ctxFromBits(bits), C.uint64_t(entityID)))",
        "}",
        "",
        "// EntityCount returns the number of alive entities.",
        "func EntityCount(bits ContextBits) uint32 {",
        "\treturn uint32(C.goud_entity_count(ctxFromBits(bits)))",
        "}",
        "",
        "// EntityClone clones an entity.",
        "func EntityClone(bits ContextBits, entityID uint64) uint64 {",
        "\treturn uint64(C.goud_entity_clone(ctxFromBits(bits), C.uint64_t(entityID)))",
        "}",
        "",
        "// EntityCloneRecursive clones an entity and its children.",
        "func EntityCloneRecursive(bits ContextBits, entityID uint64) uint64 {",
        "\treturn uint64(C.goud_entity_clone_recursive(ctxFromBits(bits), C.uint64_t(entityID)))",
        "}",
        "",
    ])


def _gen_audio_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Audio bridges ----",
        "",
        "// AudioPlay plays audio from raw bytes and returns a player ID.",
        "func AudioPlay(bits ContextBits, data []byte) int64 {",
        "\tif len(data) == 0 {",
        "\t\treturn -1",
        "\t}",
        "\treturn int64(C.goud_audio_play(ctxFromBits(bits), (*C.uint8_t)(unsafe.Pointer(&data[0])), C.size_t(len(data))))",
        "}",
        "",
        "// AudioPlayOnChannel plays audio on a specific channel.",
        "func AudioPlayOnChannel(bits ContextBits, data []byte, channel uint8) int64 {",
        "\tif len(data) == 0 {",
        "\t\treturn -1",
        "\t}",
        "\treturn int64(C.goud_audio_play_on_channel(ctxFromBits(bits), (*C.uint8_t)(unsafe.Pointer(&data[0])), C.size_t(len(data)), C.uint8_t(channel)))",
        "}",
        "",
        "// AudioStop stops a playing audio source.",
        "func AudioStop(bits ContextBits, playerID uint64) int32 {",
        "\treturn int32(C.goud_audio_stop(ctxFromBits(bits), C.uint64_t(playerID)))",
        "}",
        "",
        "// AudioStopAll stops all playing audio.",
        "func AudioStopAll(bits ContextBits) int32 {",
        "\treturn int32(C.goud_audio_stop_all(ctxFromBits(bits)))",
        "}",
        "",
        "// AudioPause pauses a playing audio source.",
        "func AudioPause(bits ContextBits, playerID uint64) int32 {",
        "\treturn int32(C.goud_audio_pause(ctxFromBits(bits), C.uint64_t(playerID)))",
        "}",
        "",
        "// AudioResume resumes a paused audio source.",
        "func AudioResume(bits ContextBits, playerID uint64) int32 {",
        "\treturn int32(C.goud_audio_resume(ctxFromBits(bits), C.uint64_t(playerID)))",
        "}",
        "",
        "// AudioSetGlobalVolume sets the global audio volume.",
        "func AudioSetGlobalVolume(bits ContextBits, volume float32) int32 {",
        "\treturn int32(C.goud_audio_set_global_volume(ctxFromBits(bits), C.float(volume)))",
        "}",
        "",
        "// AudioSetPlayerVolume sets the volume for a specific player.",
        "func AudioSetPlayerVolume(bits ContextBits, playerID uint64, volume float32) int32 {",
        "\treturn int32(C.goud_audio_set_player_volume(ctxFromBits(bits), C.uint64_t(playerID), C.float(volume)))",
        "}",
        "",
        "// AudioIsPlaying returns whether an audio source is playing.",
        "func AudioIsPlaying(bits ContextBits, playerID uint64) int32 {",
        "\treturn int32(C.goud_audio_is_playing(ctxFromBits(bits), C.uint64_t(playerID)))",
        "}",
        "",
        "// AudioActivate activates the audio subsystem.",
        "func AudioActivate(bits ContextBits) int32 {",
        "\treturn int32(C.goud_audio_activate(ctxFromBits(bits)))",
        "}",
        "",
    ])


def _gen_error_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Error bridges ----",
        "",
        "// LastErrorCode returns the last error code.",
        "func LastErrorCode() int32 {",
        "\treturn int32(C.goud_last_error_code())",
        "}",
        "",
        "// LastErrorMessage reads the last error message.",
        "func LastErrorMessage() string {",
        "\treturn ReadErrorBuffer(func(buf *C.uint8_t, bufLen C.size_t) C.int32_t {",
        "\t\treturn C.goud_last_error_message(buf, bufLen)",
        "\t})",
        "}",
        "",
        "// LastErrorSubsystem reads the last error subsystem.",
        "func LastErrorSubsystem() string {",
        "\treturn ReadErrorBuffer(func(buf *C.uint8_t, bufLen C.size_t) C.int32_t {",
        "\t\treturn C.goud_last_error_subsystem(buf, bufLen)",
        "\t})",
        "}",
        "",
        "// LastErrorOperation reads the last error operation.",
        "func LastErrorOperation() string {",
        "\treturn ReadErrorBuffer(func(buf *C.uint8_t, bufLen C.size_t) C.int32_t {",
        "\t\treturn C.goud_last_error_operation(buf, bufLen)",
        "\t})",
        "}",
        "",
        "// ErrorRecoveryClass returns the recovery class for an error code.",
        "func ErrorRecoveryClass(code int32) int32 {",
        "\treturn int32(C.goud_error_recovery_class(C.GoudErrorCode(code)))",
        "}",
        "",
    ])


def _gen_component_bridges(lines: list[str]) -> None:
    lines.extend([
        "// ---- Component bridges ----",
        "",
        "// ComponentAdd adds a component to an entity.",
        "func ComponentAdd(bits ContextBits, entityID uint64, typeIDHash uint64, data []byte) bool {",
        "\tif len(data) == 0 {",
        "\t\treturn false",
        "\t}",
        "\t// SAFETY: data is non-empty; &data[0] is valid for len(data) bytes.",
        "\tresult := C.goud_component_add(ctxFromBits(bits), C.GoudEntityId(entityID), C.uint64_t(typeIDHash), (*C.uint8_t)(unsafe.Pointer(&data[0])), C.size_t(len(data)))",
        "\treturn bool(result.success)",
        "}",
        "",
        "// ComponentGet returns a pointer to component data, or nil.",
        "// SAFETY: The returned pointer is valid only until the next engine mutation on",
        "// this context (entity despawn, component removal, scene transition). Do not",
        "// store it beyond the immediate call frame.",
        "func ComponentGet(bits ContextBits, entityID uint64, typeIDHash uint64) unsafe.Pointer {",
        "\tptr := C.goud_component_get(ctxFromBits(bits), C.GoudEntityId(entityID), C.uint64_t(typeIDHash))",
        "\tif ptr == nil {",
        "\t\treturn nil",
        "\t}",
        "\treturn unsafe.Pointer(ptr)",
        "}",
        "",
        "// ComponentGetMut returns a mutable pointer to component data, or nil.",
        "// SAFETY: The returned pointer is valid only until the next engine mutation on",
        "// this context. Do not store it beyond the immediate call frame.",
        "func ComponentGetMut(bits ContextBits, entityID uint64, typeIDHash uint64) unsafe.Pointer {",
        "\tptr := C.goud_component_get_mut(ctxFromBits(bits), C.GoudEntityId(entityID), C.uint64_t(typeIDHash))",
        "\tif ptr == nil {",
        "\t\treturn nil",
        "\t}",
        "\treturn unsafe.Pointer(ptr)",
        "}",
        "",
        "// ComponentHas returns true if an entity has a component.",
        "func ComponentHas(bits ContextBits, entityID uint64, typeIDHash uint64) bool {",
        "\treturn bool(C.goud_component_has(ctxFromBits(bits), C.GoudEntityId(entityID), C.uint64_t(typeIDHash)))",
        "}",
        "",
        "// ComponentRemove removes a component from an entity.",
        "func ComponentRemove(bits ContextBits, entityID uint64, typeIDHash uint64) bool {",
        "\tresult := C.goud_component_remove(ctxFromBits(bits), C.GoudEntityId(entityID), C.uint64_t(typeIDHash))",
        "\treturn bool(result.success)",
        "}",
        "",
        "// SizeOfFfiTransform2D returns the size of FfiTransform2D.",
        "func SizeOfFfiTransform2D() int {",
        "\treturn int(C.sizeof_FfiTransform2D)",
        "}",
        "",
        "// SizeOfFfiSprite returns the size of FfiSprite.",
        "func SizeOfFfiSprite() int {",
        "\treturn int(C.sizeof_FfiSprite)",
        "}",
        "",
        "// Transform2DToBytes serializes Transform2D fields into a byte slice",
        "// matching the C FfiTransform2D layout.",
        "func Transform2DToBytes(posX, posY, rotation, scaleX, scaleY float32) []byte {",
        "\tvar ffiT C.FfiTransform2D",
        "\tffiT.position_x = C.float(posX)",
        "\tffiT.position_y = C.float(posY)",
        "\tffiT.rotation = C.float(rotation)",
        "\tffiT.scale_x = C.float(scaleX)",
        "\tffiT.scale_y = C.float(scaleY)",
        "\tsize := C.sizeof_FfiTransform2D",
        "\tbuf := C.GoBytes(unsafe.Pointer(&ffiT), C.int(size))",
        "\treturn buf",
        "}",
        "",
        "// Transform2DFromPtr reads a Transform2D from a raw pointer.",
        "func Transform2DFromPtr(ptr unsafe.Pointer) (posX, posY, rotation, scaleX, scaleY float32) {",
        "\tif ptr == nil {",
        "\t\treturn 0, 0, 0, 1, 1",
        "\t}",
        "\tffiT := (*C.FfiTransform2D)(ptr)",
        "\treturn float32(ffiT.position_x), float32(ffiT.position_y), float32(ffiT.rotation), float32(ffiT.scale_x), float32(ffiT.scale_y)",
        "}",
        "",
        "// SpriteToBytes serializes Sprite fields into a byte slice",
        "// matching the C FfiSprite layout.",
        "func SpriteToBytes(textureHandle uint64, colorR, colorG, colorB, colorA float32,",
        "\tsrcRectX, srcRectY, srcRectW, srcRectH float32, hasSrcRect bool,",
        "\tflipX, flipY bool, zLayer int32, anchorX, anchorY float32,",
        "\tcustomSizeX, customSizeY float32, hasCustomSize bool) []byte {",
        "\tvar ffiS C.FfiSprite",
        "\tffiS.texture_handle = C.uint64_t(textureHandle)",
        "\tffiS.color_r = C.float(colorR)",
        "\tffiS.color_g = C.float(colorG)",
        "\tffiS.color_b = C.float(colorB)",
        "\tffiS.color_a = C.float(colorA)",
        "\tffiS.source_rect_x = C.float(srcRectX)",
        "\tffiS.source_rect_y = C.float(srcRectY)",
        "\tffiS.source_rect_width = C.float(srcRectW)",
        "\tffiS.source_rect_height = C.float(srcRectH)",
        "\tffiS.has_source_rect = C.bool(hasSrcRect)",
        "\tffiS.flip_x = C.bool(flipX)",
        "\tffiS.flip_y = C.bool(flipY)",
        "\tffiS.z_layer = C.int32_t(zLayer)",
        "\tffiS.anchor_x = C.float(anchorX)",
        "\tffiS.anchor_y = C.float(anchorY)",
        "\tffiS.custom_size_x = C.float(customSizeX)",
        "\tffiS.custom_size_y = C.float(customSizeY)",
        "\tffiS.has_custom_size = C.bool(hasCustomSize)",
        "\tsize := C.sizeof_FfiSprite",
        "\tbuf := C.GoBytes(unsafe.Pointer(&ffiS), C.int(size))",
        "\treturn buf",
        "}",
        "",
        "// SpriteFromPtr reads Sprite fields from a raw pointer.",
        "func SpriteFromPtr(ptr unsafe.Pointer) (textureHandle uint64, colorR, colorG, colorB, colorA float32,",
        "\tsrcRectX, srcRectY, srcRectW, srcRectH float32, hasSrcRect bool,",
        "\tflipX, flipY bool, zLayer int32, anchorX, anchorY float32,",
        "\tcustomSizeX, customSizeY float32, hasCustomSize bool) {",
        "\tif ptr == nil {",
        "\t\treturn 0, 1, 1, 1, 1, 0, 0, 0, 0, false, false, false, 0, 0, 0, 0, 0, false",
        "\t}",
        "\tffiS := (*C.FfiSprite)(ptr)",
        "\treturn uint64(ffiS.texture_handle),",
        "\t\tfloat32(ffiS.color_r), float32(ffiS.color_g), float32(ffiS.color_b), float32(ffiS.color_a),",
        "\t\tfloat32(ffiS.source_rect_x), float32(ffiS.source_rect_y), float32(ffiS.source_rect_width), float32(ffiS.source_rect_height),",
        "\t\tbool(ffiS.has_source_rect),",
        "\t\tbool(ffiS.flip_x), bool(ffiS.flip_y), int32(ffiS.z_layer),",
        "\t\tfloat32(ffiS.anchor_x), float32(ffiS.anchor_y),",
        "\t\tfloat32(ffiS.custom_size_x), float32(ffiS.custom_size_y),",
        "\t\tbool(ffiS.has_custom_size)",
        "}",
        "",
    ])
