// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.animation

enum class TransitionType(val value: Int) {
    Instant(0),
    Fade(1),
    Custom(2);

    companion object {
        fun fromValue(value: Int): TransitionType? =
            entries.firstOrNull { it.value == value }
    }
}
