// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class AnimationEventsNative {
    private AnimationEventsNative() {}

    public static native int addClipEvent(long contextId, long entity, int frameIndex, String name, int payloadType, int payloadInt, float payloadFloat, String payloadString);
    public static native int count(long contextId);
    public static native AnimationEventData read(long contextId, int index);
}
