// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class DebuggerReplayArtifact {
    public String manifestJson;
    public byte[] data;

    public DebuggerReplayArtifact() {}

    public DebuggerReplayArtifact(String manifestJson, byte[] data) {
        this.manifestJson = manifestJson;
        this.data = data;
    }
}
