// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class DebuggerConfig {
    public boolean enabled;
    public boolean publishLocalAttach;
    public String routeLabel;

    public DebuggerConfig() {}

    public DebuggerConfig(boolean enabled, boolean publishLocalAttach, String routeLabel) {
        this.enabled = enabled;
        this.publishLocalAttach = publishLocalAttach;
        this.routeLabel = routeLabel;
    }
}
