// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class Mat3x3 {
    public float[] m;

    public Mat3x3() {}

    public Mat3x3(float[] m) {
        this.m = m;
    }
}
