// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class MemorySummary {
    public MemoryCategoryStats rendering;
    public MemoryCategoryStats assets;
    public MemoryCategoryStats ecs;
    public MemoryCategoryStats ui;
    public MemoryCategoryStats audio;
    public MemoryCategoryStats network;
    public MemoryCategoryStats debugger;
    public MemoryCategoryStats other;
    public long totalCurrentBytes;
    public long totalPeakBytes;

    public MemorySummary() {}

    public MemorySummary(MemoryCategoryStats rendering, MemoryCategoryStats assets, MemoryCategoryStats ecs, MemoryCategoryStats ui, MemoryCategoryStats audio, MemoryCategoryStats network, MemoryCategoryStats debugger, MemoryCategoryStats other, long totalCurrentBytes, long totalPeakBytes) {
        this.rendering = rendering;
        this.assets = assets;
        this.ecs = ecs;
        this.ui = ui;
        this.audio = audio;
        this.network = network;
        this.debugger = debugger;
        this.other = other;
        this.totalCurrentBytes = totalCurrentBytes;
        this.totalPeakBytes = totalPeakBytes;
    }
}
