// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class NetworkPacket {
    public long peerId;
    public byte[] data;

    public NetworkPacket() {}

    public NetworkPacket(long peerId, byte[] data) {
        this.peerId = peerId;
        this.data = data;
    }
}
