// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class PhysicsWorld3DNative {
    private PhysicsWorld3DNative() {}

    public static native int create(long contextId, float gravityX, float gravityY, float gravityZ);
    public static native int destroy(long contextId);
    public static native int setGravity(long contextId, float x, float y, float z);
    public static native long addRigidBody(long contextId, int bodyType, float x, float y, float z, float gravityScale);
    public static native long addRigidBodyEx(long contextId, int bodyType, float x, float y, float z, float gravityScale, boolean ccdEnabled);
    public static native long addCollider(long contextId, long bodyHandle, int shapeType, float hx, float hy, float hz, float radius, float friction, float restitution);
    public static native int removeBody(long contextId, long handle);
    public static native long createJoint(long contextId, long bodyA, long bodyB, int kind, float anchorAx, float anchorAy, float anchorAz, float anchorBx, float anchorBy, float anchorBz, float axisX, float axisY, float axisZ, boolean hasLimits, float limitMin, float limitMax, boolean hasMotor, float motorTargetVelocity, float motorMaxForce);
    public static native int removeJoint(long contextId, long handle);
    public static native int step(long contextId, float dt);
    public static native Vec3 getPosition(long contextId, long handle);
    public static native int setVelocity(long contextId, long handle, float vx, float vy, float vz);
    public static native int applyForce(long contextId, long handle, float fx, float fy, float fz);
    public static native int applyImpulse(long contextId, long handle, float ix, float iy, float iz);
    public static native Vec3 getGravity(long contextId);
    public static native int setBodyGravityScale(long contextId, long handle, float scale);
    public static native float getBodyGravityScale(long contextId, long handle);
    public static native int setColliderFriction(long contextId, long handle, float friction);
    public static native float getColliderFriction(long contextId, long handle);
    public static native int setColliderRestitution(long contextId, long handle, float restitution);
    public static native float getColliderRestitution(long contextId, long handle);
    public static native int setTimestep(long contextId, float dt);
    public static native float getTimestep(long contextId);
}
