// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class SpriteAnimatorBuilderNative {
    private SpriteAnimatorBuilderNative() {}

    public static native long create(float frameDuration, int mode);
    public static native long addFrame(long selfHandle, float x, float y, float w, float h);
    public static native SpriteAnimator build(long selfHandle);
    public static native void free(long selfHandle);
}
