// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class TextCmd {
    public long fontHandle;
    public String text;
    public float x;
    public float y;
    public float fontSize;
    public int alignment;
    public int direction;
    public float maxWidth;
    public float lineSpacing;
    public float r;
    public float g;
    public float b;
    public float a;

    public TextCmd() {}
}
