// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class Text {
    public long fontHandle;
    public float fontSize;
    public float colorR;
    public float colorG;
    public float colorB;
    public float colorA;
    public int alignment;
    public float maxWidth;
    public boolean hasMaxWidth;
    public float lineSpacing;

    public Text() {}

    public Text(long fontHandle, float fontSize, float colorR, float colorG, float colorB, float colorA, int alignment, float maxWidth, boolean hasMaxWidth, float lineSpacing) {
        this.fontHandle = fontHandle;
        this.fontSize = fontSize;
        this.colorR = colorR;
        this.colorG = colorG;
        this.colorB = colorB;
        this.colorA = colorA;
        this.alignment = alignment;
        this.maxWidth = maxWidth;
        this.hasMaxWidth = hasMaxWidth;
        this.lineSpacing = lineSpacing;
    }
}
