// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class Transform2D {
    public float positionX;
    public float positionY;
    public float rotation;
    public float scaleX;
    public float scaleY;

    public Transform2D() {}

    public Transform2D(float positionX, float positionY, float rotation, float scaleX, float scaleY) {
        this.positionX = positionX;
        this.positionY = positionY;
        this.rotation = rotation;
        this.scaleX = scaleX;
        this.scaleY = scaleY;
    }
}
