// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.internal;

public final class UiManagerNative {
    private UiManagerNative() {}

    public static native long create();
    public static native void update(long managerHandle);
    public static native void render(long managerHandle);
    public static native int nodeCount(long managerHandle);
    public static native long createNode(long managerHandle, int componentType);
    public static native int removeNode(long managerHandle, long nodeId);
    public static native int setParent(long managerHandle, long childId, long parentId);
    public static native long getParent(long managerHandle, long nodeId);
    public static native int getChildCount(long managerHandle, long nodeId);
    public static native long getChildAt(long managerHandle, long nodeId, int index);
    public static native int setWidget(long managerHandle, long nodeId, int widgetKind);
    public static native int setStyle(long managerHandle, long nodeId, UiStyle style);
    public static native int setLabelText(long managerHandle, long nodeId, String text);
    public static native int setButtonEnabled(long managerHandle, long nodeId, boolean enabled);
    public static native int setImageTexturePath(long managerHandle, long nodeId, String path);
    public static native int setSlider(long managerHandle, long nodeId, float min, float max, float value, boolean enabled);
    public static native int eventCount(long managerHandle);
    public static native UiEvent eventRead(long managerHandle, int index);
}
