// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.physics

/** Collider shape type */
enum class ShapeType(val value: Int) {
    Box(0),
    Circle(1);

    companion object {
        fun fromValue(value: Int): ShapeType? =
            entries.firstOrNull { it.value == value }
    }
}
