"""Extra class generators for `_game.py` (EngineConfig, UiManager)."""

from .context import mapping, schema, to_snake
from .shared_helpers import py_value_param_ffi_setup


def gen_engine_config(lines: list[str]) -> None:
    """Generate EngineConfig builder class for Python."""
    tool = schema["tools"]["EngineConfig"]
    tm = mapping["tools"]["EngineConfig"]

    lines.append("class EngineConfig:")
    lines.append(f'    """{tool["doc"]}"""')
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        lib = get_lib()")
    lines.append("        self._lib = lib")
    lines.append(f"        self._handle = lib.{tm['constructor']['ffi']}()")
    lines.append("")
    lines.append("    def __del__(self):")
    lines.append("        self.destroy()")
    lines.append("")

    for method in tool.get("methods", []):
        mn = method["name"]
        mm = tm.get("methods", {}).get(mn, {})
        ffi_fn = mm.get("ffi", "")
        params = method.get("params", [])
        mname = to_snake(mn)

        if mname == "destroy":
            lines.append("    def destroy(self):")
            if method.get("doc"):
                lines.append(f'        """{method["doc"]}"""')
            lines.append("        if hasattr(self, '_handle') and self._handle:")
            lines.append(f"            self._lib.{ffi_fn}(self._handle)")
            lines.append("            self._handle = None")
            lines.append("")
        elif mname == "build":
            lines.append("    def build(self):")
            if method.get("doc"):
                lines.append(f'        """{method["doc"]}"""')
            lines.append("        if not self._handle:")
            lines.append("            raise RuntimeError('EngineConfig already consumed')")
            lines.append(f"        ctx = self._lib.{ffi_fn}(self._handle)")
            lines.append("        self._handle = None")
            lines.append("        if ctx._bits == 0xFFFFFFFFFFFFFFFF:")
            lines.append("            raise RuntimeError('Failed to create engine context from EngineConfig')")
            lines.append("        game = GoudGame.__new__(GoudGame)")
            lines.append("        game._lib = self._lib")
            lines.append("        game._ctx = ctx")
            lines.append("        game._delta_time = 0.0")
            lines.append("        game._title = ''")
            lines.append("        game._frame_count = 0")
            lines.append("        game._total_time = 0.0")
            lines.append("        return game")
            lines.append("")
        elif mname == "set_title":
            lines.append(f"    def {mname}(self, title):")
            if method.get("doc"):
                lines.append(f'        """{method["doc"]}"""')
            lines.append("        if not self._handle:")
            lines.append("            raise RuntimeError('EngineConfig already consumed or destroyed')")
            lines.append(f"        self._lib.{ffi_fn}(self._handle, title.encode('utf-8'))")
            lines.append("        return self")
            lines.append("")
        else:
            sig = ", ".join(["self"] + [to_snake(p["name"]) for p in params])
            lines.append(f"    def {mname}({sig}):")
            if method.get("doc"):
                lines.append(f'        """{method["doc"]}"""')
            lines.append("        if not self._handle:")
            lines.append("            raise RuntimeError('EngineConfig already consumed or destroyed')")
            ffi_call_args = []
            for p in params:
                pn = to_snake(p["name"])
                if p["type"] in schema.get("enums", {}):
                    ffi_call_args.append(f"int({pn})")
                    continue
                value_setup = py_value_param_ffi_setup(p)
                if value_setup:
                    value_lines, value_arg = value_setup
                    lines.extend(value_lines)
                    ffi_call_args.append(value_arg)
                else:
                    ffi_call_args.append(pn)
            ffi_args = ", ".join(["self._handle"] + ffi_call_args)
            lines.append(f"        self._lib.{ffi_fn}({ffi_args})")
            lines.append("        return self")
            lines.append("")


def gen_ui_manager(lines: list[str]) -> None:
    """Generate standalone UiManager wrapper for Python."""
    if "UiManager" not in schema.get("tools", {}) or "UiManager" not in mapping.get("tools", {}):
        return

    lines.append("class UiManager:")
    lines.append('    """Immediate-mode UI manager for creating and managing UI node trees"""')
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        lib = get_lib()")
    lines.append("        self._lib = lib")
    lines.append("        self._handle = lib.goud_ui_manager_create()")
    lines.append("        if not self._handle:")
    lines.append("            raise RuntimeError('Failed to create UiManager')")
    lines.append("")
    lines.append("    def __del__(self):")
    lines.append("        self.destroy()")
    lines.append("")
    lines.append("    def destroy(self):")
    lines.append("        if hasattr(self, '_handle') and self._handle:")
    lines.append("            self._lib.goud_ui_manager_destroy(self._handle)")
    lines.append("            self._handle = None")
    lines.append("")
    lines.append("    def update(self):")
    lines.append("        self._lib.goud_ui_manager_update(self._handle)")
    lines.append("")
    lines.append("    def render(self):")
    lines.append("        self._lib.goud_ui_manager_render(self._handle)")
    lines.append("")
    lines.append("    def node_count(self):")
    lines.append("        return self._lib.goud_ui_manager_node_count(self._handle)")
    lines.append("")
    lines.append("    def create_node(self, component_type):")
    lines.append("        return self._lib.goud_ui_create_node(self._handle, component_type)")
    lines.append("")
    lines.append("    def remove_node(self, node_id):")
    lines.append("        return self._lib.goud_ui_remove_node(self._handle, node_id)")
    lines.append("")
    lines.append("    def set_parent(self, child_id, parent_id):")
    lines.append("        return self._lib.goud_ui_set_parent(self._handle, child_id, parent_id)")
    lines.append("")
    lines.append("    def get_parent(self, node_id):")
    lines.append("        return self._lib.goud_ui_get_parent(self._handle, node_id)")
    lines.append("")
    lines.append("    def get_child_count(self, node_id):")
    lines.append("        return self._lib.goud_ui_get_child_count(self._handle, node_id)")
    lines.append("")
    lines.append("    def get_child_at(self, node_id, index):")
    lines.append("        return self._lib.goud_ui_get_child_at(self._handle, node_id, index)")
    lines.append("")
    lines.append("    def set_widget(self, node_id, widget_kind):")
    lines.append("        return self._lib.goud_ui_set_widget(self._handle, node_id, widget_kind)")
    lines.append("")
    lines.append("    def set_style(self, node_id, style):")
    lines.append("        ffi_style = FfiUiStyle()")
    lines.append("        ffi_style.has_background_color = bool(style.has_background_color)")
    lines.append("        ffi_style.background_color = FfiColor(style.background_color.r, style.background_color.g, style.background_color.b, style.background_color.a)")
    lines.append("        ffi_style.has_foreground_color = bool(style.has_foreground_color)")
    lines.append("        ffi_style.foreground_color = FfiColor(style.foreground_color.r, style.foreground_color.g, style.foreground_color.b, style.foreground_color.a)")
    lines.append("        ffi_style.has_border_color = bool(style.has_border_color)")
    lines.append("        ffi_style.border_color = FfiColor(style.border_color.r, style.border_color.g, style.border_color.b, style.border_color.a)")
    lines.append("        ffi_style.has_border_width = bool(style.has_border_width)")
    lines.append("        ffi_style.border_width = style.border_width")
    lines.append("        ffi_style.has_font_family = bool(style.has_font_family)")
    lines.append("        font_family = '' if style.font_family is None else style.font_family")
    lines.append("        font_family_bytes = font_family.encode('utf-8') if style.has_font_family else b''")
    lines.append("        font_family_buf = ctypes.create_string_buffer(font_family_bytes, len(font_family_bytes)) if font_family_bytes else None")
    lines.append("        ffi_style.font_family_ptr = ctypes.cast(font_family_buf, ctypes.c_void_p).value if font_family_bytes else None")
    lines.append("        ffi_style.font_family_len = len(font_family_bytes)")
    lines.append("        ffi_style.has_font_size = bool(style.has_font_size)")
    lines.append("        ffi_style.font_size = style.font_size")
    lines.append("        ffi_style.has_texture_path = bool(style.has_texture_path)")
    lines.append("        texture_path = '' if style.texture_path is None else style.texture_path")
    lines.append("        texture_path_bytes = texture_path.encode('utf-8') if style.has_texture_path else b''")
    lines.append("        texture_path_buf = ctypes.create_string_buffer(texture_path_bytes, len(texture_path_bytes)) if texture_path_bytes else None")
    lines.append("        ffi_style.texture_path_ptr = ctypes.cast(texture_path_buf, ctypes.c_void_p).value if texture_path_bytes else None")
    lines.append("        ffi_style.texture_path_len = len(texture_path_bytes)")
    lines.append("        ffi_style.has_widget_spacing = bool(style.has_widget_spacing)")
    lines.append("        ffi_style.widget_spacing = style.widget_spacing")
    lines.append("        return self._lib.goud_ui_set_style(self._handle, node_id, ctypes.byref(ffi_style))")
    lines.append("")
    lines.append("    def set_label_text(self, node_id, text):")
    lines.append("        text = '' if text is None else text")
    lines.append("        text_bytes = text.encode('utf-8')")
    lines.append("        text_buf = ctypes.create_string_buffer(text_bytes, len(text_bytes)) if text_bytes else None")
    lines.append("        text_ptr = ctypes.cast(text_buf, ctypes.POINTER(ctypes.c_uint8)) if text_bytes else ctypes.POINTER(ctypes.c_uint8)()")
    lines.append("        return self._lib.goud_ui_set_label_text(self._handle, node_id, text_ptr, len(text_bytes))")
    lines.append("")
    lines.append("    def set_button_enabled(self, node_id, enabled):")
    lines.append("        return self._lib.goud_ui_set_button_enabled(self._handle, node_id, enabled)")
    lines.append("")
    lines.append("    def set_image_texture_path(self, node_id, path):")
    lines.append("        path = '' if path is None else path")
    lines.append("        path_bytes = path.encode('utf-8')")
    lines.append("        path_buf = ctypes.create_string_buffer(path_bytes, len(path_bytes)) if path_bytes else None")
    lines.append("        path_ptr = ctypes.cast(path_buf, ctypes.POINTER(ctypes.c_uint8)) if path_bytes else ctypes.POINTER(ctypes.c_uint8)()")
    lines.append("        return self._lib.goud_ui_set_image_texture_path(self._handle, node_id, path_ptr, len(path_bytes))")
    lines.append("")
    lines.append("    def set_slider(self, node_id, min_value, max_value, value, enabled):")
    lines.append("        return self._lib.goud_ui_set_slider(self._handle, node_id, min_value, max_value, value, enabled)")
    lines.append("")
    lines.append("    def event_count(self):")
    lines.append("        return self._lib.goud_ui_event_count(self._handle)")
    lines.append("")
    lines.append("    def event_read(self, index):")
    lines.append("        event = FfiUiEvent()")
    lines.append("        status = self._lib.goud_ui_event_read(self._handle, index, ctypes.byref(event))")
    lines.append("        if status <= 0:")
    lines.append("            return None")
    lines.append("        return UiEvent(event.event_kind, event.node_id, event.previous_node_id, event.current_node_id)")
    lines.append("")
    lines.append("    # Convenience widget helpers")
    lines.append("    def create_panel(self):")
    lines.append("        return self.create_node(0)")
    lines.append("")
    lines.append("    def create_label(self, text):")
    lines.append("        node = self.create_node(2)")
    lines.append("        self.set_label_text(node, text)")
    lines.append("        return node")
    lines.append("")
    lines.append("    def create_button(self, enabled = True):")
    lines.append("        node = self.create_node(1)")
    lines.append("        self.set_button_enabled(node, enabled)")
    lines.append("        return node")
    lines.append("")
    lines.append("    def create_image(self, path):")
    lines.append("        node = self.create_node(3)")
    lines.append("        self.set_image_texture_path(node, path)")
    lines.append("        return node")
    lines.append("")
    lines.append("    def create_slider(self, min_value, max_value, value, enabled = True):")
    lines.append("        node = self.create_node(4)")
    lines.append("        self.set_slider(node, min_value, max_value, value, enabled)")
    lines.append("        return node")
    lines.append("")
