"""Generator for `sdks/python/goudengine/networking.py`."""

from .context import HEADER_COMMENT, OUT, write_generated


def gen_network_wrappers() -> None:
    lines = [
        f'"""{HEADER_COMMENT}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING, Any, Optional",
        "",
        "try:",
        "    from .generated._errors import GoudError",
        'except ImportError:  # pragma: no cover - supports direct module loading in tests',
        "    from goudengine.generated._errors import GoudError",
        "",
        "if TYPE_CHECKING:",
        "    from .generated._types import NetworkPacket, NetworkSimulationConfig",
        "",
        "",
        "def _raise_backend_error_or_runtime(backend: Any, message: str) -> None:",
        "    lib = getattr(backend, '_lib', None)",
        "    if lib is not None:",
        "        error = GoudError.from_last_error(lib)",
        "        if error is not None:",
        "            raise error",
        "    raise RuntimeError(message)",
        "",
        "",
        "class NetworkEndpoint:",
        '    """Thin wrapper around a low-level network handle."""',
        "",
        "    def __init__(self, backend: Any, handle: int, default_peer_id: Optional[int] = None):",
        "        self._backend = backend",
        "        self.handle = handle",
        "        self.default_peer_id = default_peer_id",
        "",
        "    def poll(self):",
        "        return self._backend.network_poll(self.handle)",
        "",
        "    def receive(self):",
        "        return self._backend.network_receive_packet(self.handle)",
        "",
        "    def send(self, data, channel = 0):",
        "        if self.default_peer_id is None:",
        "            raise ValueError(",
        "                \"No default peer ID is set for this endpoint; use send_to(peer_id, data, channel) instead.\"",
        "            )",
        "        return self.send_to(self.default_peer_id, data, channel)",
        "",
        "    def send_to(self, peer_id, data, channel = 0):",
        "        return self._backend.network_send(self.handle, peer_id, data, channel)",
        "",
        "    def disconnect(self):",
        "        return self._backend.network_disconnect(self.handle)",
        "",
        "    def get_stats(self):",
        "        return self._backend.get_network_stats(self.handle)",
        "",
        "    def peer_count(self):",
        "        return self._backend.network_peer_count(self.handle)",
        "",
        "    def set_simulation(self, config):",
        "        return self._backend.set_network_simulation(self.handle, config)",
        "",
        "    def clear_simulation(self):",
        "        return self._backend.clear_network_simulation(self.handle)",
        "",
        "    def set_overlay_target(self):",
        "        return self._backend.set_network_overlay_handle(self.handle)",
        "",
        "    def clear_overlay_target(self):",
        "        return self._backend.clear_network_overlay_handle()",
        "",
        "",
        "class NetworkManager:",
        '    """Factory for creating NetworkEndpoint wrappers from a game/context backend."""',
        "",
        "    def __init__(self, backend: Any):",
        "        self._backend = backend",
        "",
        "    def host(self, protocol, port):",
        "        handle = self._backend.network_host(protocol, port)",
        "        if handle < 0:",
        "            _raise_backend_error_or_runtime(",
        "                self._backend,",
        "                f\"network_host failed with handle {handle}\"",
        "            )",
        "        return NetworkEndpoint(self._backend, handle, None)",
        "",
        "    def connect(self, protocol, address, port):",
        "        result = self._backend.network_connect_with_peer(protocol, address, port)",
        "        return NetworkEndpoint(self._backend, result.handle, result.peer_id)",
    ]

    write_generated(OUT.parent / "networking.py", "\n".join(lines))
