#!/usr/bin/env python3
"""Generate mdBook snippet includes and a reference page from canonical sources."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil
import sys


ROOT = Path(__file__).resolve().parent.parent
SNIPPET_SOURCE_DIR = ROOT / "docs" / "snippets" / "src"
SNIPPET_OUTPUT_DIR = ROOT / "docs" / "src" / "generated" / "snippets"
REFERENCE_OUT = ROOT / "docs" / "src" / "reference" / "snippets.generated.md"
HEADER = "<!-- AUTO-GENERATED by scripts/generate-doc-snippets.py. DO NOT EDIT. -->\n"

LANG_BY_SUFFIX = {
    ".cs": "csharp",
    ".html": "html",
    ".py": "python",
    ".rs": "rust",
    ".ts": "ts",
}


@dataclass(frozen=True)
class SnippetSpec:
    title: str
    source: Path
    language: str
    start_pattern: str
    line_count: int


REFERENCE_SPECS = [
    SnippetSpec(
        title="Rust Sandbox Setup",
        source=ROOT / "examples" / "rust" / "sandbox" / "src" / "main.rs",
        language="rust",
        start_pattern=r"^\s*let mut game = GoudGame::with_platform",
        line_count=8,
    ),
    SnippetSpec(
        title="C# Sandbox Setup",
        source=ROOT / "examples" / "csharp" / "sandbox" / "Program.cs",
        language="csharp",
        start_pattern=r"^\s*using var engineConfig = new EngineConfig",
        line_count=8,
    ),
    SnippetSpec(
        title="Python Sandbox Startup",
        source=ROOT / "examples" / "python" / "sandbox.py",
        language="python",
        start_pattern=r"^\s*config = EngineConfig",
        line_count=8,
    ),
    SnippetSpec(
        title="TypeScript Sandbox Asset Loading",
        source=ROOT / "examples" / "typescript" / "sandbox" / "sandbox.ts",
        language="ts",
        start_pattern=r"^\s*const background = await game\.loadTexture",
        line_count=8,
    ),
    SnippetSpec(
        title="Python Generated Public Exports",
        source=ROOT / "sdks" / "python" / "goud_engine" / "generated" / "__init__.py",
        language="python",
        start_pattern=r'^"""This file is AUTO-GENERATED',
        line_count=10,
    ),
    SnippetSpec(
        title="TypeScript Generated Public Exports",
        source=ROOT / "sdks" / "typescript" / "src" / "generated" / "node" / "index.g.ts",
        language="ts",
        start_pattern=r"^// This file is AUTO-GENERATED",
        line_count=14,
    ),
]


def _render_include_snippets() -> None:
    if not SNIPPET_SOURCE_DIR.exists():
        raise SystemExit(f"Snippet source directory not found: {SNIPPET_SOURCE_DIR}")

    if SNIPPET_OUTPUT_DIR.exists():
        shutil.rmtree(SNIPPET_OUTPUT_DIR)
    SNIPPET_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for source_path in sorted(SNIPPET_SOURCE_DIR.rglob("*")):
        if not source_path.is_file():
            continue

        language = LANG_BY_SUFFIX.get(source_path.suffix)
        if language is None:
            raise SystemExit(f"Unsupported snippet source type: {source_path}")

        relative_path = source_path.relative_to(SNIPPET_SOURCE_DIR).with_suffix(".md")
        output_path = SNIPPET_OUTPUT_DIR / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)

        snippet_body = source_path.read_text(encoding="utf-8").rstrip()
        output_path.write_text(
            f"{HEADER}```{language}\n{snippet_body}\n```\n",
            encoding="utf-8",
        )


def _extract_window(lines: list[str], start_idx: int, line_count: int) -> list[str]:
    return [line.rstrip("\n") for line in lines[start_idx : start_idx + line_count]]


def _extract_reference_snippet(spec: SnippetSpec) -> list[str]:
    lines = spec.source.read_text(encoding="utf-8").splitlines(keepends=True)
    matcher = re.compile(spec.start_pattern)
    for idx, line in enumerate(lines):
        if matcher.search(line.rstrip("\n")):
            return _extract_window(lines, idx, spec.line_count)
    raise ValueError(f"Could not find snippet start in {spec.source}: {spec.start_pattern}")


def _render_reference_page() -> str:
    sections: list[str] = [
        HEADER.rstrip("\n"),
        "# Reusable Snippets (Generated)",
        "",
        "This page is generated from validated sources:",
        "- Sandbox examples exercised by parity checks",
        "- SDK generated entrypoints emitted by codegen",
        "",
    ]

    for spec in REFERENCE_SPECS:
        snippet = _extract_reference_snippet(spec)
        rel = spec.source.relative_to(ROOT)
        sections.extend(
            [
                f"## {spec.title}",
                "",
                f"Source: `{rel}`",
                "",
                f"```{spec.language}",
                *snippet,
                "```",
                "",
            ]
        )

    return "\n".join(sections).rstrip() + "\n"


def main() -> int:
    _render_include_snippets()
    REFERENCE_OUT.parent.mkdir(parents=True, exist_ok=True)
    REFERENCE_OUT.write_text(_render_reference_page(), encoding="utf-8")
    print(f"Generated {SNIPPET_OUTPUT_DIR.relative_to(ROOT)}")
    print(f"Generated {REFERENCE_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
