#!/usr/bin/env python3
"""Generate showcase docs from examples/showcase.manifest.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "examples" / "showcase.manifest.json"
SHOWCASE_OUT = ROOT / "docs" / "src" / "guides" / "showcase.md"
EXAMPLES_OUT = ROOT / "examples" / "README.md"
HEADER = "<!-- AUTO-GENERATED by scripts/generate-showcase-docs.py. DO NOT EDIT. -->\n"


def discover_example_paths() -> set[str]:
    paths: set[str] = set()

    for csproj in (ROOT / "examples" / "csharp").glob("*/*.csproj"):
        paths.add(str(csproj.parent.relative_to(ROOT)).replace("\\", "/"))

    for py_path in (ROOT / "examples" / "python").glob("*.py"):
        if py_path.name.startswith("_"):
            continue
        paths.add(str(py_path.relative_to(ROOT)).replace("\\", "/"))

    for cargo_toml in (ROOT / "examples" / "rust").glob("*/Cargo.toml"):
        paths.add(str(cargo_toml.parent.relative_to(ROOT)).replace("\\", "/"))

    for desktop_ts in (ROOT / "examples" / "typescript").glob("*/desktop.ts"):
        paths.add(str(desktop_ts.relative_to(ROOT)).replace("\\", "/"))

    for web_index in (ROOT / "examples" / "typescript").glob("*/web/index.html"):
        paths.add(str(web_index.parent.relative_to(ROOT)).replace("\\", "/"))

    return paths


def source_url(repo_url: str, relative_path: str) -> str:
    abs_path = ROOT / relative_path
    ref_type = "tree" if abs_path.is_dir() else "blob"
    return f"{repo_url}/{ref_type}/main/{relative_path}"


def validate_manifest(data: dict) -> None:
    if "repo_url" not in data:
        raise SystemExit("Missing required key: repo_url")
    if "sections" not in data or not isinstance(data["sections"], list):
        raise SystemExit("Missing required list key: sections")

    manifest_paths: set[str] = set()
    for section in data["sections"]:
        for entry in section.get("entries", []):
            rel = entry["path"]
            abs_path = ROOT / rel
            if not abs_path.exists():
                raise SystemExit(f"Manifest path does not exist: {rel}")
            if rel in manifest_paths:
                raise SystemExit(f"Duplicate manifest path: {rel}")
            manifest_paths.add(rel)

    discovered = discover_example_paths()
    missing_from_manifest = sorted(discovered - manifest_paths)
    stale_in_manifest = sorted(manifest_paths - discovered)

    if missing_from_manifest:
        lines = "\n".join(f"  - {path}" for path in missing_from_manifest)
        raise SystemExit(
            "Manifest is missing discovered examples:\n"
            f"{lines}\n"
            "Update examples/showcase.manifest.json."
        )

    if stale_in_manifest:
        lines = "\n".join(f"  - {path}" for path in stale_in_manifest)
        raise SystemExit(
            "Manifest has entries no longer discovered from examples/:\n"
            f"{lines}\n"
            "Remove or fix these manifest paths."
        )


def media_cell(entry: dict) -> str:
    media = entry.get("media")
    if not media:
        return "Pending"
    media_path = media.get("path")
    alt = media.get("alt", entry["name"])
    if not media_path:
        return "Pending"
    abs_path = ROOT / media_path
    if not abs_path.exists():
        return f"Missing: `{media_path}`"
    rel_from_guides = Path("..") / Path(media_path).relative_to("docs/src")
    return f"![{alt}]({rel_from_guides.as_posix()})"


def render_showcase(data: dict) -> str:
    lines: list[str] = [
        HEADER.rstrip("\n"),
        "# Example Showcase",
        "",
        "This page and preview media are generated from `examples/showcase.manifest.json` and `scripts/generate-showcase-docs.py`.",
        "Run `python3 scripts/generate-showcase-docs.py` after metadata or media changes.",
        "",
        "Current release status:",
        "- Source links, run commands, and preview media are generated for entries in `examples/`.",
        "",
    ]

    for section in data["sections"]:
        lines.extend([
            f"## {section['title']}",
            "",
            section.get("description", ""),
            "",
            "| Example | SDK | Target | Path | Run command | Description | Media | Source |",
            "|---|---|---|---|---|---|---|---|",
        ])

        for entry in section.get("entries", []):
            rel_path = entry["path"]
            url = source_url(data["repo_url"], rel_path)
            lines.append(
                "| "
                f"{entry['name']} | {entry['sdk']} | {entry['target']} | `{rel_path}` | "
                f"`{entry['run']}` | {entry['description']} | {media_cell(entry)} | "
                f"[GitHub]({url}) |"
            )

        lines.append("")

    lines.extend([
        "## Notes",
        "",
        "- This page is generated. Update `examples/showcase.manifest.json` and rerun the generator.",
        "- Generator validation fails if examples are added or removed without manifest updates.",
        "",
    ])

    return "\n".join(lines)


def render_examples_readme(data: dict) -> str:
    lines: list[str] = [
        HEADER.rstrip("\n"),
        "# GoudEngine Examples",
        "",
        "This file is generated from `examples/showcase.manifest.json`.",
        "Run `python3 scripts/generate-showcase-docs.py` after metadata changes.",
        "",
        "Related docs:",
        "- `docs/src/guides/showcase.md`",
        "- `docs/src/guides/build-your-first-game.md`",
        "",
        "## All examples",
        "",
        "| Example | SDK | Target | Path | Run command |",
        "|---|---|---|---|---|",
    ]

    for section in data["sections"]:
        for entry in section.get("entries", []):
            lines.append(
                "| "
                f"{entry['name']} | {entry['sdk']} | {entry['target']} | `{entry['path']}` | "
                f"`{entry['run']}` |"
            )

    lines.extend([
        "",
        "## Notes",
        "",
        "- Flappy Bird is the parity baseline across C#, Python, TypeScript, and Rust.",
        "- Sandbox is the flagship parity app across all supported SDK targets.",
        "- Feature Lab remains as supplemental smoke coverage.",
        "",
        "## Regeneration",
        "",
        "```bash",
        "python3 scripts/generate-showcase-docs.py",
        "```",
        "",
    ])
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            raise SystemExit(f"Generated file is out of date: {path.relative_to(ROOT)}")
        return
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    validate_manifest(data)

    showcase = render_showcase(data)
    examples = render_examples_readme(data)

    write_or_check(SHOWCASE_OUT, showcase, args.check)
    write_or_check(EXAMPLES_OUT, examples, args.check)

    if not args.check:
        print(f"Generated {SHOWCASE_OUT.relative_to(ROOT)}")
        print(f"Generated {EXAMPLES_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
