#!/usr/bin/env python3
"""Generate Codex and Claude agent wrappers from .agents/agent-catalog.toml."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    import tomllib  # type: ignore[attr-defined]

    TOML_DECODE_ERROR = tomllib.TOMLDecodeError
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11
    import toml as _toml  # type: ignore[no-redef]

    class _TomllibCompat:
        @staticmethod
        def loads(value: str) -> dict[str, Any]:
            return _toml.loads(value)

    tomllib = _TomllibCompat()  # type: ignore[assignment]
    TOML_DECODE_ERROR = ValueError


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / ".agents/agent-catalog.toml"
CODEX_CONFIG_PATH = ROOT / ".codex/config.toml"
CODEX_AGENTS_DIR = ROOT / ".codex/agents"
CLAUDE_AGENTS_DIR = ROOT / ".claude/agents"

GENERATED_HEADER = "# AUTO-GENERATED by scripts/sync-agent-configs.py. DO NOT EDIT DIRECTLY."
GENERATED_MARKER = "AUTO-GENERATED by scripts/sync-agent-configs.py"
EDIT_HINT = "<!-- Edit .agents/agent-catalog.toml and .agents/role-specs/*.md, then rerun the generator. -->"

EXPECTED_TIERS = {
    "default": "high",
    "engine-lead": "high",
    "integration-lead": "high",
    "quality-lead": "high",
    "security-auditor": "high",
    "worker": "standard",
    "implementer": "standard",
    "test-first-implementer": "standard",
    "ffi-implementer": "standard",
    "sdk-implementer": "standard",
    "spec-reviewer": "standard",
    "code-quality-reviewer": "standard",
    "test-runner": "standard",
    "debugger": "standard",
    "documentation-writer": "standard",
    "explorer": "fast",
    "monitor": "fast",
    "quick-fix": "fast",
    "architecture-validator": "fast",
    "graphics-domain-expert": "fast",
    "ecs-domain-expert": "fast",
    "ffi-domain-expert": "fast",
}

ALLOWED_SANDBOX_MODES = {"read-only", "workspace-write", "danger-full-access"}
EDIT_TOOLS = {"Edit", "Write"}
ALLOWED_SHARED_TEAM_MODES = {"single-lead"}
ALLOWED_SHARED_FALLBACK_MODES = {"single-agent"}


class CatalogError(RuntimeError):
    """Raised when the catalog is invalid."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="check whether generated files are up to date without writing",
    )
    return parser.parse_args()


def toml_string(value: str) -> str:
    return json.dumps(value)


def toml_array(values: list[str]) -> str:
    return "[" + ", ".join(toml_string(value) for value in values) + "]"


def bool_literal(value: bool) -> str:
    return "true" if value else "false"


def toml_multiline_basic(value: str) -> str:
    if '"""' in value:
        raise CatalogError('Role spec contains unsupported triple double quote sequence')
    if not value.endswith("\n"):
        value += "\n"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"""\n' + escaped + '"""'


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def ensure_non_empty_string(value: Any, field: str, context: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise CatalogError(f"{context}.{field} must be a non-empty string")
    return value


def ensure_string_list(value: Any, field: str, context: str) -> list[str]:
    if not isinstance(value, list) or not value:
        raise CatalogError(f"{context}.{field} must be a non-empty list")
    if any(not isinstance(item, str) or not item.strip() for item in value):
        raise CatalogError(f"{context}.{field} must contain non-empty strings")
    return value


def role_ids_in_order(catalog: dict[str, Any]) -> list[str]:
    order = catalog["role_order"]
    return [str(role_id) for role_id in order]


def validate_tier_balance(role_id: str, role: dict[str, Any]) -> None:
    expected = EXPECTED_TIERS.get(role_id)
    if expected is None:
        return
    actual = role["tier"]
    if actual != expected:
        raise CatalogError(
            f"roles.{role_id}.tier must be {expected!r} for balanced tiering, got {actual!r}"
        )


def validate_catalog(catalog: dict[str, Any]) -> dict[str, Any]:
    if catalog.get("version") != 1:
        raise CatalogError("version must be 1")

    settings = catalog.get("settings")
    if not isinstance(settings, dict):
        raise CatalogError("missing [settings] table")

    for field in (
        "root_model",
        "root_plan_mode_reasoning_effort",
        "codex_max_threads",
        "codex_max_depth",
        "shared_team_mode",
        "shared_max_specialists_per_lead",
        "shared_fallback_mode",
        "job_max_runtime_seconds",
    ):
        if field not in settings:
            raise CatalogError(f"settings.{field} is required")

    ensure_non_empty_string(settings["root_model"], "root_model", "settings")
    ensure_non_empty_string(
        settings["root_plan_mode_reasoning_effort"],
        "root_plan_mode_reasoning_effort",
        "settings",
    )

    for number_field in (
        "codex_max_threads",
        "codex_max_depth",
        "shared_max_specialists_per_lead",
        "job_max_runtime_seconds",
    ):
        value = settings[number_field]
        if not isinstance(value, int) or value <= 0:
            raise CatalogError(f"settings.{number_field} must be a positive integer")

    shared_team_mode = ensure_non_empty_string(
        settings["shared_team_mode"], "shared_team_mode", "settings"
    )
    if shared_team_mode not in ALLOWED_SHARED_TEAM_MODES:
        raise CatalogError(
            f"settings.shared_team_mode must be one of {sorted(ALLOWED_SHARED_TEAM_MODES)}"
        )

    shared_fallback_mode = ensure_non_empty_string(
        settings["shared_fallback_mode"], "shared_fallback_mode", "settings"
    )
    if shared_fallback_mode not in ALLOWED_SHARED_FALLBACK_MODES:
        raise CatalogError(
            f"settings.shared_fallback_mode must be one of {sorted(ALLOWED_SHARED_FALLBACK_MODES)}"
        )

    role_order = catalog.get("role_order")
    if not isinstance(role_order, list) or not role_order:
        raise CatalogError("role_order must be a non-empty list")
    if any(not isinstance(role_id, str) or not role_id.strip() for role_id in role_order):
        raise CatalogError("role_order must contain non-empty strings")
    if len(set(role_order)) != len(role_order):
        raise CatalogError("role_order must not contain duplicates")

    roles = catalog.get("roles")
    if not isinstance(roles, dict) or not roles:
        raise CatalogError("missing [roles] table or roles table is empty")

    missing_roles = [role_id for role_id in role_order if role_id not in roles]
    if missing_roles:
        raise CatalogError(f"role_order references undefined roles: {', '.join(missing_roles)}")

    extra_roles = sorted(set(roles.keys()) - set(role_order))
    if extra_roles:
        raise CatalogError(f"roles defined but not listed in role_order: {', '.join(extra_roles)}")

    for role_id in role_order:
        role = roles.get(role_id)
        context = f"roles.{role_id}"
        if not isinstance(role, dict):
            raise CatalogError(f"{context} must be a table")

        for field in (
            "description",
            "spec_file",
            "tier",
            "codex_model",
            "codex_model_reasoning_effort",
            "codex_sandbox_mode",
            "nickname_candidates",
            "claude_enabled",
        ):
            if field not in role:
                raise CatalogError(f"{context}.{field} is required")

        ensure_non_empty_string(role["description"], "description", context)
        spec_file = ensure_non_empty_string(role["spec_file"], "spec_file", context)
        tier = ensure_non_empty_string(role["tier"], "tier", context)
        ensure_non_empty_string(role["codex_model"], "codex_model", context)
        ensure_non_empty_string(
            role["codex_model_reasoning_effort"], "codex_model_reasoning_effort", context
        )

        sandbox_mode = ensure_non_empty_string(role["codex_sandbox_mode"], "codex_sandbox_mode", context)
        if sandbox_mode not in ALLOWED_SANDBOX_MODES:
            raise CatalogError(
                f"{context}.codex_sandbox_mode must be one of {sorted(ALLOWED_SANDBOX_MODES)}"
            )

        if tier not in {"high", "standard", "fast"}:
            raise CatalogError(f"{context}.tier must be one of: high, standard, fast")

        nickname_candidates = ensure_string_list(role["nickname_candidates"], "nickname_candidates", context)
        if len(set(nickname_candidates)) != len(nickname_candidates):
            raise CatalogError(f"{context}.nickname_candidates must be unique")

        spec_path = ROOT / spec_file
        if not spec_path.exists():
            raise CatalogError(f"{context}.spec_file does not exist: {spec_file}")

        claude_enabled = role["claude_enabled"]
        if not isinstance(claude_enabled, bool):
            raise CatalogError(f"{context}.claude_enabled must be boolean")

        if claude_enabled:
            claude_cfg = role.get("claude")
            if not isinstance(claude_cfg, dict):
                raise CatalogError(f"{context}.claude table is required when claude_enabled = true")
            ensure_non_empty_string(claude_cfg.get("model"), "model", f"{context}.claude")
            ensure_non_empty_string(
                claude_cfg.get("permission_mode"),
                "permission_mode",
                f"{context}.claude",
            )
            ensure_string_list(claude_cfg.get("tools"), "tools", f"{context}.claude")

        validate_tier_balance(role_id, role)

    return catalog


def load_catalog(path: Path) -> dict[str, Any]:
    try:
        raw = read_text(path)
    except FileNotFoundError as exc:
        raise CatalogError(f"missing catalog file: {path}") from exc

    try:
        parsed = tomllib.loads(raw)
    except TOML_DECODE_ERROR as exc:
        raise CatalogError(f"invalid TOML in {path}: {exc}") from exc

    if not isinstance(parsed, dict):
        raise CatalogError("catalog root must be a TOML table")

    return validate_catalog(parsed)


def infer_codex_shell(role: dict[str, Any]) -> bool:
    override = role.get("codex_allow_shell")
    if isinstance(override, bool):
        return override

    if role.get("claude_enabled"):
        claude_tools = role.get("claude", {}).get("tools", [])
        return "Bash" in claude_tools

    return True


def infer_codex_edits(role: dict[str, Any]) -> bool:
    override = role.get("codex_allow_edits")
    if isinstance(override, bool):
        return override

    if role.get("claude_enabled"):
        claude_tools = role.get("claude", {}).get("tools", [])
        return any(tool in EDIT_TOOLS for tool in claude_tools)

    return role["codex_sandbox_mode"] != "read-only"


def resolve_codex_approval_policy(role: dict[str, Any]) -> str:
    override = role.get("codex_approval_policy")
    if isinstance(override, str) and override.strip():
        return override

    if role["codex_sandbox_mode"] == "read-only":
        return "never"
    return "on-request"


def render_codex_config(catalog: dict[str, Any]) -> str:
    settings = catalog["settings"]
    roles = catalog["roles"]
    role_order = role_ids_in_order(catalog)

    lines = [
        "#:schema https://developers.openai.com/codex/config-schema.json",
        GENERATED_HEADER,
        "",
        f"model = {toml_string(settings['root_model'])}",
    ]

    root_model_effort = settings.get("root_model_reasoning_effort")
    if isinstance(root_model_effort, str) and root_model_effort.strip():
        lines.append(f"model_reasoning_effort = {toml_string(root_model_effort)}")

    lines.extend(
        [
            f"plan_mode_reasoning_effort = {toml_string(settings['root_plan_mode_reasoning_effort'])}",
            "",
            "[features]",
            "multi_agent = true",
            "",
            "[agents]",
            f"max_threads = {settings['codex_max_threads']}",
            f"max_depth = {settings['codex_max_depth']}",
            f"job_max_runtime_seconds = {settings['job_max_runtime_seconds']}",
            "",
            "# Shared orchestration policy (catalog source of truth)",
            f"# shared_team_mode = {toml_string(settings['shared_team_mode'])}",
            f"# shared_max_specialists_per_lead = {settings['shared_max_specialists_per_lead']}",
            f"# shared_fallback_mode = {toml_string(settings['shared_fallback_mode'])}",
        ]
    )

    for role_id in role_order:
        role = roles[role_id]
        lines.extend(
            [
                "",
                f"[agents.{role_id}]",
                f"description = {toml_string(role['description'])}",
                f"config_file = {toml_string(f'agents/{role_id}.toml')}",
                f"nickname_candidates = {toml_array(role['nickname_candidates'])}",
            ]
        )

    return "\n".join(lines) + "\n"


def render_codex_role_config(role: dict[str, Any]) -> str:
    sandbox_mode = role["codex_sandbox_mode"]
    approval_policy = resolve_codex_approval_policy(role)
    spec_text = read_text(ROOT / role["spec_file"]).lstrip("\n")
    developer_instructions = toml_multiline_basic(spec_text)

    lines = [
        GENERATED_HEADER,
        "",
        f"model = {toml_string(role['codex_model'])}",
        f"model_reasoning_effort = {toml_string(role['codex_model_reasoning_effort'])}",
        f"sandbox_mode = {toml_string(sandbox_mode)}",
        f"approval_policy = {toml_string(approval_policy)}",
        f"developer_instructions = {developer_instructions}",
    ]

    return "\n".join(lines) + "\n"


def render_claude_wrapper(role_id: str, role: dict[str, Any]) -> str:
    claude_cfg = role["claude"]

    spec_text = read_text(ROOT / role["spec_file"]).lstrip("\n")
    if not spec_text.endswith("\n"):
        spec_text += "\n"

    lines = [
        "---",
        f"name: {role_id}",
        f"description: {role['description']}",
        f"model: {claude_cfg['model']}",
        "tools:",
    ]
    for tool_name in claude_cfg["tools"]:
        lines.append(f"  - {tool_name}")
    lines.extend(
        [
            f"permissionMode: {claude_cfg['permission_mode']}",
            "---",
            "",
            f"<!-- {GENERATED_MARKER}. -->",
            EDIT_HINT,
            "",
        ]
    )

    return "\n".join(lines) + spec_text


def generate_outputs(catalog: dict[str, Any]) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    roles = catalog["roles"]

    outputs[CODEX_CONFIG_PATH] = render_codex_config(catalog)

    for role_id in role_ids_in_order(catalog):
        role = roles[role_id]
        outputs[CODEX_AGENTS_DIR / f"{role_id}.toml"] = render_codex_role_config(role)
        if role["claude_enabled"]:
            outputs[CLAUDE_AGENTS_DIR / f"{role_id}.md"] = render_claude_wrapper(role_id, role)

    return outputs


def is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    snippet = read_text(path)[:512]
    return GENERATED_MARKER in snippet


def find_stale_files(expected_paths: set[Path]) -> list[Path]:
    stale: list[Path] = []

    for candidate in sorted(CODEX_AGENTS_DIR.glob("*.toml")) if CODEX_AGENTS_DIR.exists() else []:
        if candidate not in expected_paths and is_generated_file(candidate):
            stale.append(candidate)

    for candidate in sorted(CLAUDE_AGENTS_DIR.glob("*.md")) if CLAUDE_AGENTS_DIR.exists() else []:
        if candidate not in expected_paths and is_generated_file(candidate):
            stale.append(candidate)

    return stale


def check_sync(outputs: dict[Path, str], stale_files: list[Path]) -> int:
    mismatches: list[Path] = []
    for path, expected in sorted(outputs.items(), key=lambda item: str(item[0])):
        current = read_text(path) if path.exists() else None
        if current != expected:
            mismatches.append(path)

    if not mismatches and not stale_files:
        print("Agent config files are in sync.")
        return 0

    print("Agent config drift detected:")
    for path in mismatches:
        status = "missing" if not path.exists() else "outdated"
        print(f" - {status}: {path.relative_to(ROOT)}")
    for path in stale_files:
        print(f" - stale: {path.relative_to(ROOT)}")
    print("Run: python3 scripts/sync-agent-configs.py")
    return 1


def write_sync(outputs: dict[Path, str], stale_files: list[Path]) -> int:
    for stale_path in stale_files:
        stale_path.unlink()

    changed = 0
    for path, content in sorted(outputs.items(), key=lambda item: str(item[0])):
        path.parent.mkdir(parents=True, exist_ok=True)
        current = read_text(path) if path.exists() else None
        if current != content:
            write_text(path, content)
            changed += 1

    print(f"Wrote {changed} file(s). Removed {len(stale_files)} stale file(s).")
    return 0


def main() -> int:
    args = parse_args()

    try:
        catalog = load_catalog(CATALOG_PATH)
    except CatalogError as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        return 2

    outputs = generate_outputs(catalog)
    expected_paths = set(outputs.keys())
    stale_files = find_stale_files(expected_paths)

    if args.check:
        return check_sync(outputs, stale_files)
    return write_sync(outputs, stale_files)


if __name__ == "__main__":
    raise SystemExit(main())
