// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.

// Package goud provides the Go SDK wrapper for GoudEngine.
//
// This package is a thin wrapper over the FFI bindings in internal/ffi,
// providing idiomatic Go types and methods. All game logic, rendering,
// physics, and audio processing lives in the Rust engine core; this SDK
// only marshals calls across the FFI boundary.
//
// Basic usage:
//
//	game := goud.NewGame(800, 600, "My Game")
//	defer game.Destroy()
//	for !game.ShouldClose() {
//		game.BeginFrame(0, 0, 0, 1)
//		// draw and update here
//		game.EndFrame()
//	}
package goud
