// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.

package goud

import "fmt"

// EntityID is a generational entity identifier.
// The lower 32 bits are the index, the upper 32 bits are the generation.
type EntityID uint64

// NewEntityID creates an EntityID from raw bits.
func NewEntityID(bits uint64) EntityID {
	return EntityID(bits)
}

// Bits returns the raw uint64 representation.
func (e EntityID) Bits() uint64 {
	return uint64(e)
}

// Index returns the entity index (lower 32 bits).
func (e EntityID) Index() uint32 {
	return uint32(e & 0xFFFFFFFF)
}

// Generation returns the entity generation (upper 32 bits).
func (e EntityID) Generation() uint32 {
	return uint32(e >> 32)
}

// IsPlaceholder returns true if the entity is the placeholder sentinel.
func (e EntityID) IsPlaceholder() bool {
	return uint64(e) == 0xFFFFFFFFFFFFFFFF
}

// String implements fmt.Stringer.
func (e EntityID) String() string {
	return fmt.Sprintf("Entity(%dv%d)", e.Index(), e.Generation())
}
