// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.

package goud

import "math"

// Color RGBA color with float components in 0.0-1.0 range
type Color struct {
	R float32
	G float32
	B float32
	A float32
}

// NewColor creates a new Color.
func NewColor(r float32, g float32, b float32, a float32) Color {
	return Color{
		R: r,
		G: g,
		B: b,
		A: a,
	}
}

// ColorWhite returns a predefined Color.
func ColorWhite() Color {
	return NewColor(1, 1, 1, 1)
}

// ColorBlack returns a predefined Color.
func ColorBlack() Color {
	return NewColor(0, 0, 0, 1)
}

// ColorRed returns a predefined Color.
func ColorRed() Color {
	return NewColor(1, 0, 0, 1)
}

// ColorGreen returns a predefined Color.
func ColorGreen() Color {
	return NewColor(0, 1, 0, 1)
}

// ColorBlue returns a predefined Color.
func ColorBlue() Color {
	return NewColor(0, 0, 1, 1)
}

// ColorYellow returns a predefined Color.
func ColorYellow() Color {
	return NewColor(1, 1, 0, 1)
}

// ColorCyan returns a predefined Color.
func ColorCyan() Color {
	return NewColor(0, 1, 1, 1)
}

// ColorMagenta returns a predefined Color.
func ColorMagenta() Color {
	return NewColor(1, 0, 1, 1)
}

// ColorTransparent returns a predefined Color.
func ColorTransparent() Color {
	return NewColor(0, 0, 0, 0)
}

// ColorRgba creates a Color from the given arguments.
func ColorRgba(r float32, g float32, b float32, a float32) Color {
	return NewColor(r, g, b, a)
}

// ColorRgb creates a Color from the given arguments.
func ColorRgb(r float32, g float32, b float32) Color {
	return NewColor(r, g, b, 1.0)
}

// ColorFromHex creates a Color from the given arguments.
func ColorFromHex(hex uint32) Color {
	return NewColor(
		float32((hex>>16)&0xFF)/255.0,
		float32((hex>>8)&0xFF)/255.0,
		float32(hex&0xFF)/255.0,
		1.0,
	)
}

// ColorFromU8 creates a Color from the given arguments.
func ColorFromU8(r uint8, g uint8, b uint8, a uint8) Color {
	return NewColor(float32(r)/255.0, float32(g)/255.0, float32(b)/255.0, float32(a)/255.0)
}

// WithAlpha returns a new Color with the given alpha.
func (c Color) WithAlpha(a float32) Color {
	return NewColor(c.R, c.G, c.B, a)
}

// Lerp linearly interpolates between two Color values.
func (c Color) Lerp(other Color, t float32) Color {
	return NewColor(
		c.R+(other.R-c.R)*t,
		c.G+(other.G-c.G)*t,
		c.B+(other.B-c.B)*t,
		c.A+(other.A-c.A)*t,
	)
}

// Vec2 2D floating-point vector
type Vec2 struct {
	X float32
	Y float32
}

// NewVec2 creates a new Vec2.
func NewVec2(x float32, y float32) Vec2 {
	return Vec2{
		X: x,
		Y: y,
	}
}

// Vec2Zero returns a predefined Vec2.
func Vec2Zero() Vec2 {
	return NewVec2(0, 0)
}

// Vec2One returns a predefined Vec2.
func Vec2One() Vec2 {
	return NewVec2(1, 1)
}

// Vec2Up returns a predefined Vec2.
func Vec2Up() Vec2 {
	return NewVec2(0, -1)
}

// Vec2Down returns a predefined Vec2.
func Vec2Down() Vec2 {
	return NewVec2(0, 1)
}

// Vec2Left returns a predefined Vec2.
func Vec2Left() Vec2 {
	return NewVec2(-1, 0)
}

// Vec2Right returns a predefined Vec2.
func Vec2Right() Vec2 {
	return NewVec2(1, 0)
}

// Add returns the sum of two Vec2 values.
func (v Vec2) Add(other Vec2) Vec2 {
	return NewVec2(v.X+other.X, v.Y+other.Y)
}

// Sub returns the difference of two Vec2 values.
func (v Vec2) Sub(other Vec2) Vec2 {
	return NewVec2(v.X-other.X, v.Y-other.Y)
}

// Scale returns the Vec2 scaled by s.
func (v Vec2) Scale(s float32) Vec2 {
	return NewVec2(v.X*s, v.Y*s)
}

// Length returns the magnitude of the Vec2.
func (v Vec2) Length() float32 {
	return float32(math.Sqrt(float64(v.X*v.X + v.Y*v.Y)))
}

// Normalize returns a unit-length Vec2.
func (v Vec2) Normalize() Vec2 {
	l := v.Length()
	if l == 0 { return Vec2Zero() }
	return NewVec2(v.X/l, v.Y/l)
}

// Dot returns the dot product of two Vec2 values.
func (v Vec2) Dot(other Vec2) float32 {
	return v.X*other.X + v.Y*other.Y
}

// Distance returns the distance between two Vec2 values.
func (v Vec2) Distance(other Vec2) float32 {
	return v.Sub(other).Length()
}

// Lerp linearly interpolates between two Vec2 values.
func (v Vec2) Lerp(other Vec2, t float32) Vec2 {
	return NewVec2(v.X+(other.X-v.X)*t, v.Y+(other.Y-v.Y)*t)
}

// Rect Axis-aligned rectangle
type Rect struct {
	X float32
	Y float32
	Width float32
	Height float32
}

// NewRect creates a new Rect.
func NewRect(x float32, y float32, width float32, height float32) Rect {
	return Rect{
		X: x,
		Y: y,
		Width: width,
		Height: height,
	}
}

// Contains returns true if the point is inside the Rect.
func (r Rect) Contains(point Vec2) bool {
	return point.X >= r.X && point.X <= r.X+r.Width &&
		point.Y >= r.Y && point.Y <= r.Y+r.Height
}

// Intersects returns true if two Rects overlap.
func (r Rect) Intersects(other Rect) bool {
	return r.X < other.X+other.Width && r.X+r.Width > other.X &&
		r.Y < other.Y+other.Height && r.Y+r.Height > other.Y
}

// Mat3x3 3x3 matrix in column-major order for 2D transforms
type Mat3x3 struct {
	M [9]float32
}

// NewMat3x3 creates a new Mat3x3.
func NewMat3x3(m [9]float32) Mat3x3 {
	return Mat3x3{
		M: m,
	}
}

// AnimationEventData Data for a fired animation event read from the event queue
type AnimationEventData struct {
	Entity uint64
	Name string
	FrameIndex uint32
	PayloadType uint32
	PayloadInt int32
	PayloadFloat float32
	PayloadString string
}

// NewAnimationEventData creates a new AnimationEventData.
func NewAnimationEventData(entity uint64, name string, frameIndex uint32, payloadType uint32, payloadInt int32, payloadFloat float32, payloadString string) AnimationEventData {
	return AnimationEventData{
		Entity: entity,
		Name: name,
		FrameIndex: frameIndex,
		PayloadType: payloadType,
		PayloadInt: payloadInt,
		PayloadFloat: payloadFloat,
		PayloadString: payloadString,
	}
}

// SpriteCmd describes a single sprite for batched rendering via DrawSpriteBatch.
// Position, size, and source-rect values are in screen-space pixels.
// When SrcW and SrcH are both 0 the full texture is used.
type SpriteCmd struct {
	Texture        uint64
	X, Y           float32
	Width, Height  float32
	Rotation       float32
	SrcX, SrcY     float32
	SrcW, SrcH     float32
	R, G, B, A     float32
	ZLayer         int32
}

// NewSpriteCmd creates a new SpriteCmd.
func NewSpriteCmd(texture uint64, x, y, width, height, rotation, srcX, srcY, srcW, srcH, r, g, b, a float32, zLayer int32) SpriteCmd {
	return SpriteCmd{
		Texture: texture, X: x, Y: y, Width: width, Height: height,
		Rotation: rotation, SrcX: srcX, SrcY: srcY, SrcW: srcW, SrcH: srcH,
		R: r, G: g, B: b, A: a, ZLayer: zLayer,
	}
}

// RenderStats Per-frame rendering statistics
type RenderStats struct {
	DrawCalls uint32
	Triangles uint32
	TextureBinds uint32
	ShaderBinds uint32
}

// NewRenderStats creates a new RenderStats.
func NewRenderStats(drawCalls uint32, triangles uint32, textureBinds uint32, shaderBinds uint32) RenderStats {
	return RenderStats{
		DrawCalls: drawCalls,
		Triangles: triangles,
		TextureBinds: textureBinds,
		ShaderBinds: shaderBinds,
	}
}

// Contact Collision contact point information
type Contact struct {
	PointX float32
	PointY float32
	NormalX float32
	NormalY float32
	Penetration float32
}

// NewContact creates a new Contact.
func NewContact(pointX float32, pointY float32, normalX float32, normalY float32, penetration float32) Contact {
	return Contact{
		PointX: pointX,
		PointY: pointY,
		NormalX: normalX,
		NormalY: normalY,
		Penetration: penetration,
	}
}

// PhysicsRaycastHit2D Detailed payload for a 2D physics raycast hit
type PhysicsRaycastHit2D struct {
	BodyHandle uint64
	ColliderHandle uint64
	PointX float32
	PointY float32
	NormalX float32
	NormalY float32
	Distance float32
}

// NewPhysicsRaycastHit2D creates a new PhysicsRaycastHit2D.
func NewPhysicsRaycastHit2D(bodyHandle uint64, colliderHandle uint64, pointX float32, pointY float32, normalX float32, normalY float32, distance float32) PhysicsRaycastHit2D {
	return PhysicsRaycastHit2D{
		BodyHandle: bodyHandle,
		ColliderHandle: colliderHandle,
		PointX: pointX,
		PointY: pointY,
		NormalX: normalX,
		NormalY: normalY,
		Distance: distance,
	}
}

// PhysicsCollisionEvent2D 2D collision event payload from the physics event queue
type PhysicsCollisionEvent2D struct {
	BodyA uint64
	BodyB uint64
	Kind uint32
}

// NewPhysicsCollisionEvent2D creates a new PhysicsCollisionEvent2D.
func NewPhysicsCollisionEvent2D(bodyA uint64, bodyB uint64, kind uint32) PhysicsCollisionEvent2D {
	return PhysicsCollisionEvent2D{
		BodyA: bodyA,
		BodyB: bodyB,
		Kind: kind,
	}
}

// Vec3 3D floating-point vector
type Vec3 struct {
	X float32
	Y float32
	Z float32
}

// NewVec3 creates a new Vec3.
func NewVec3(x float32, y float32, z float32) Vec3 {
	return Vec3{
		X: x,
		Y: y,
		Z: z,
	}
}

// Vec3Zero returns a predefined Vec3.
func Vec3Zero() Vec3 {
	return NewVec3(0, 0, 0)
}

// Vec3One returns a predefined Vec3.
func Vec3One() Vec3 {
	return NewVec3(1, 1, 1)
}

// Vec3Up returns a predefined Vec3.
func Vec3Up() Vec3 {
	return NewVec3(0, 1, 0)
}

// FpsStats Frame timing statistics from the debug overlay rolling window
type FpsStats struct {
	CurrentFps float32
	MinFps float32
	MaxFps float32
	AvgFps float32
	FrameTimeMs float32
}

// NewFpsStats creates a new FpsStats.
func NewFpsStats(currentFps float32, minFps float32, maxFps float32, avgFps float32, frameTimeMs float32) FpsStats {
	return FpsStats{
		CurrentFps: currentFps,
		MinFps: minFps,
		MaxFps: maxFps,
		AvgFps: avgFps,
		FrameTimeMs: frameTimeMs,
	}
}

// RenderMetrics Per-frame render metrics: draw call counts, culling stats, batch efficiency, and per-category timing
type RenderMetrics struct {
	DrawCallCount uint32
	SpritesSubmitted uint32
	SpritesDrawn uint32
	SpritesCulled uint32
	BatchesSubmitted uint32
	AvgSpritesPerBatch float32
	SpriteRenderMs float32
	TextRenderMs float32
	UiRenderMs float32
	TotalRenderMs float32
	TextDrawCalls uint32
	TextGlyphCount uint32
	UiDrawCalls uint32
}

// NewRenderMetrics creates a new RenderMetrics.
func NewRenderMetrics(drawCallCount uint32, spritesSubmitted uint32, spritesDrawn uint32, spritesCulled uint32, batchesSubmitted uint32, avgSpritesPerBatch float32, spriteRenderMs float32, textRenderMs float32, uiRenderMs float32, totalRenderMs float32, textDrawCalls uint32, textGlyphCount uint32, uiDrawCalls uint32) RenderMetrics {
	return RenderMetrics{
		DrawCallCount: drawCallCount,
		SpritesSubmitted: spritesSubmitted,
		SpritesDrawn: spritesDrawn,
		SpritesCulled: spritesCulled,
		BatchesSubmitted: batchesSubmitted,
		AvgSpritesPerBatch: avgSpritesPerBatch,
		SpriteRenderMs: spriteRenderMs,
		TextRenderMs: textRenderMs,
		UiRenderMs: uiRenderMs,
		TotalRenderMs: totalRenderMs,
		TextDrawCalls: textDrawCalls,
		TextGlyphCount: textGlyphCount,
		UiDrawCalls: uiDrawCalls,
	}
}

// DebuggerConfig Pre-init debugger runtime configuration for desktop contexts.
type DebuggerConfig struct {
	Enabled bool
	PublishLocalAttach bool
	RouteLabel string
}

// NewDebuggerConfig creates a new DebuggerConfig.
func NewDebuggerConfig(enabled bool, publishLocalAttach bool, routeLabel string) DebuggerConfig {
	return DebuggerConfig{
		Enabled: enabled,
		PublishLocalAttach: publishLocalAttach,
		RouteLabel: routeLabel,
	}
}

// ContextConfig Pre-init configuration for headless context creation.
type ContextConfig struct {
	Debugger DebuggerConfig
}

// NewContextConfig creates a new ContextConfig.
func NewContextConfig(debugger DebuggerConfig) ContextConfig {
	return ContextConfig{
		Debugger: debugger,
	}
}

// MemoryCategoryStats Tracked current and peak bytes for one debugger memory category.
type MemoryCategoryStats struct {
	CurrentBytes uint64
	PeakBytes uint64
}

// NewMemoryCategoryStats creates a new MemoryCategoryStats.
func NewMemoryCategoryStats(currentBytes uint64, peakBytes uint64) MemoryCategoryStats {
	return MemoryCategoryStats{
		CurrentBytes: currentBytes,
		PeakBytes: peakBytes,
	}
}

// MemorySummary Debugger-owned aggregate memory summary for one route.
type MemorySummary struct {
	Rendering MemoryCategoryStats
	Assets MemoryCategoryStats
	Ecs MemoryCategoryStats
	Ui MemoryCategoryStats
	Audio MemoryCategoryStats
	Network MemoryCategoryStats
	Debugger MemoryCategoryStats
	Other MemoryCategoryStats
	TotalCurrentBytes uint64
	TotalPeakBytes uint64
}

// NewMemorySummary creates a new MemorySummary.
func NewMemorySummary(rendering MemoryCategoryStats, assets MemoryCategoryStats, ecs MemoryCategoryStats, ui MemoryCategoryStats, audio MemoryCategoryStats, network MemoryCategoryStats, debugger MemoryCategoryStats, other MemoryCategoryStats, totalCurrentBytes uint64, totalPeakBytes uint64) MemorySummary {
	return MemorySummary{
		Rendering: rendering,
		Assets: assets,
		Ecs: ecs,
		Ui: ui,
		Audio: audio,
		Network: network,
		Debugger: debugger,
		Other: other,
		TotalCurrentBytes: totalCurrentBytes,
		TotalPeakBytes: totalPeakBytes,
	}
}

// DebuggerCapture Debugger frame capture artifact envelope returned directly by SDK calls.
type DebuggerCapture struct {
	ImagePng []byte
	MetadataJson string
	SnapshotJson string
	MetricsTraceJson string
}

// NewDebuggerCapture creates a new DebuggerCapture.
func NewDebuggerCapture(imagePng []byte, metadataJson string, snapshotJson string, metricsTraceJson string) DebuggerCapture {
	return DebuggerCapture{
		ImagePng: imagePng,
		MetadataJson: metadataJson,
		SnapshotJson: snapshotJson,
		MetricsTraceJson: metricsTraceJson,
	}
}

// DebuggerReplayArtifact Debugger replay recording artifact envelope returned directly by SDK calls.
type DebuggerReplayArtifact struct {
	ManifestJson string
	Data []byte
}

// NewDebuggerReplayArtifact creates a new DebuggerReplayArtifact.
func NewDebuggerReplayArtifact(manifestJson string, data []byte) DebuggerReplayArtifact {
	return DebuggerReplayArtifact{
		ManifestJson: manifestJson,
		Data: data,
	}
}

// RenderCapabilities Capabilities reported by the active render provider
type RenderCapabilities struct {
	MaxTextureUnits uint32
	MaxTextureSize uint32
	SupportsInstancing bool
	SupportsCompute bool
	SupportsMsaa bool
}

// NewRenderCapabilities creates a new RenderCapabilities.
func NewRenderCapabilities(maxTextureUnits uint32, maxTextureSize uint32, supportsInstancing bool, supportsCompute bool, supportsMsaa bool) RenderCapabilities {
	return RenderCapabilities{
		MaxTextureUnits: maxTextureUnits,
		MaxTextureSize: maxTextureSize,
		SupportsInstancing: supportsInstancing,
		SupportsCompute: supportsCompute,
		SupportsMsaa: supportsMsaa,
	}
}

// PhysicsCapabilities Capabilities reported by the active physics provider
type PhysicsCapabilities struct {
	SupportsContinuousCollision bool
	SupportsJoints bool
	MaxBodies uint32
}

// NewPhysicsCapabilities creates a new PhysicsCapabilities.
func NewPhysicsCapabilities(supportsContinuousCollision bool, supportsJoints bool, maxBodies uint32) PhysicsCapabilities {
	return PhysicsCapabilities{
		SupportsContinuousCollision: supportsContinuousCollision,
		SupportsJoints: supportsJoints,
		MaxBodies: maxBodies,
	}
}

// AudioCapabilities Capabilities reported by the active audio provider
type AudioCapabilities struct {
	SupportsSpatial bool
	MaxChannels uint32
}

// NewAudioCapabilities creates a new AudioCapabilities.
func NewAudioCapabilities(supportsSpatial bool, maxChannels uint32) AudioCapabilities {
	return AudioCapabilities{
		SupportsSpatial: supportsSpatial,
		MaxChannels: maxChannels,
	}
}

// InputCapabilities Capabilities reported by the active input provider
type InputCapabilities struct {
	SupportsGamepad bool
	SupportsTouch bool
	MaxGamepads uint32
}

// NewInputCapabilities creates a new InputCapabilities.
func NewInputCapabilities(supportsGamepad bool, supportsTouch bool, maxGamepads uint32) InputCapabilities {
	return InputCapabilities{
		SupportsGamepad: supportsGamepad,
		SupportsTouch: supportsTouch,
		MaxGamepads: maxGamepads,
	}
}

// NetworkCapabilities Capabilities reported by the active network provider
type NetworkCapabilities struct {
	SupportsHosting bool
	MaxConnections uint32
	MaxChannels uint8
	MaxMessageSize uint32
}

// NewNetworkCapabilities creates a new NetworkCapabilities.
func NewNetworkCapabilities(supportsHosting bool, maxConnections uint32, maxChannels uint8, maxMessageSize uint32) NetworkCapabilities {
	return NetworkCapabilities{
		SupportsHosting: supportsHosting,
		MaxConnections: maxConnections,
		MaxChannels: maxChannels,
		MaxMessageSize: maxMessageSize,
	}
}

// NetworkStats Aggregate network statistics for a network handle
type NetworkStats struct {
	BytesSent uint64
	BytesReceived uint64
	PacketsSent uint64
	PacketsReceived uint64
	PacketsLost uint64
	RttMs float32
	SendBandwidthBytesPerSec float32
	ReceiveBandwidthBytesPerSec float32
	PacketLossPercent float32
	JitterMs float32
}

// NewNetworkStats creates a new NetworkStats.
func NewNetworkStats(bytesSent uint64, bytesReceived uint64, packetsSent uint64, packetsReceived uint64, packetsLost uint64, rttMs float32, sendBandwidthBytesPerSec float32, receiveBandwidthBytesPerSec float32, packetLossPercent float32, jitterMs float32) NetworkStats {
	return NetworkStats{
		BytesSent: bytesSent,
		BytesReceived: bytesReceived,
		PacketsSent: packetsSent,
		PacketsReceived: packetsReceived,
		PacketsLost: packetsLost,
		RttMs: rttMs,
		SendBandwidthBytesPerSec: sendBandwidthBytesPerSec,
		ReceiveBandwidthBytesPerSec: receiveBandwidthBytesPerSec,
		PacketLossPercent: packetLossPercent,
		JitterMs: jitterMs,
	}
}

// NetworkSimulationConfig Debug-only network simulation settings for a network handle
type NetworkSimulationConfig struct {
	OneWayLatencyMs uint32
	JitterMs uint32
	PacketLossPercent float32
}

// NewNetworkSimulationConfig creates a new NetworkSimulationConfig.
func NewNetworkSimulationConfig(oneWayLatencyMs uint32, jitterMs uint32, packetLossPercent float32) NetworkSimulationConfig {
	return NetworkSimulationConfig{
		OneWayLatencyMs: oneWayLatencyMs,
		JitterMs: jitterMs,
		PacketLossPercent: packetLossPercent,
	}
}

// NetworkConnectResult Peer-preserving connection result returned by networkConnectWithPeer
type NetworkConnectResult struct {
	Handle int64
	PeerId uint64
}

// NewNetworkConnectResult creates a new NetworkConnectResult.
func NewNetworkConnectResult(handle int64, peerId uint64) NetworkConnectResult {
	return NetworkConnectResult{
		Handle: handle,
		PeerId: peerId,
	}
}

// NetworkPacket Inbound network payload with the sender peer ID preserved
type NetworkPacket struct {
	PeerId uint64
	Data []byte
}

// NewNetworkPacket creates a new NetworkPacket.
func NewNetworkPacket(peerId uint64, data []byte) NetworkPacket {
	return NetworkPacket{
		PeerId: peerId,
		Data: data,
	}
}

// UiStyle C-safe UI style payload for node-level visual overrides.
type UiStyle struct {
	HasBackgroundColor bool
	BackgroundColor Color
	HasForegroundColor bool
	ForegroundColor Color
	HasBorderColor bool
	BorderColor Color
	HasBorderWidth bool
	BorderWidth float32
	HasFontFamily bool
	FontFamilyPtr uintptr
	FontFamilyLen uint
	HasFontSize bool
	FontSize float32
	HasTexturePath bool
	TexturePathPtr uintptr
	TexturePathLen uint
	HasWidgetSpacing bool
	WidgetSpacing float32
}

// NewUiStyle creates a new UiStyle.
func NewUiStyle(hasBackgroundColor bool, backgroundColor Color, hasForegroundColor bool, foregroundColor Color, hasBorderColor bool, borderColor Color, hasBorderWidth bool, borderWidth float32, hasFontFamily bool, fontFamilyPtr uintptr, fontFamilyLen uint, hasFontSize bool, fontSize float32, hasTexturePath bool, texturePathPtr uintptr, texturePathLen uint, hasWidgetSpacing bool, widgetSpacing float32) UiStyle {
	return UiStyle{
		HasBackgroundColor: hasBackgroundColor,
		BackgroundColor: backgroundColor,
		HasForegroundColor: hasForegroundColor,
		ForegroundColor: foregroundColor,
		HasBorderColor: hasBorderColor,
		BorderColor: borderColor,
		HasBorderWidth: hasBorderWidth,
		BorderWidth: borderWidth,
		HasFontFamily: hasFontFamily,
		FontFamilyPtr: fontFamilyPtr,
		FontFamilyLen: fontFamilyLen,
		HasFontSize: hasFontSize,
		FontSize: fontSize,
		HasTexturePath: hasTexturePath,
		TexturePathPtr: texturePathPtr,
		TexturePathLen: texturePathLen,
		HasWidgetSpacing: hasWidgetSpacing,
		WidgetSpacing: widgetSpacing,
	}
}

// UiEvent UI event payload returned by deterministic polling APIs.
type UiEvent struct {
	EventKind uint32
	NodeId uint64
	PreviousNodeId uint64
	CurrentNodeId uint64
}

// NewUiEvent creates a new UiEvent.
func NewUiEvent(eventKind uint32, nodeId uint64, previousNodeId uint64, currentNodeId uint64) UiEvent {
	return UiEvent{
		EventKind: eventKind,
		NodeId: nodeId,
		PreviousNodeId: previousNodeId,
		CurrentNodeId: currentNodeId,
	}
}

// P2pMeshConfig Configuration for P2P mesh networking
type P2pMeshConfig struct {
	MaxPeers uint32
	HostMigration bool
	Topology int32
}

// NewP2pMeshConfig creates a new P2pMeshConfig.
func NewP2pMeshConfig(maxPeers uint32, hostMigration bool, topology int32) P2pMeshConfig {
	return P2pMeshConfig{
		MaxPeers: maxPeers,
		HostMigration: hostMigration,
		Topology: topology,
	}
}

// RollbackConfig Configuration for rollback netcode session
type RollbackConfig struct {
	MaxRollbackFrames uint32
	InputDelayFrames uint32
	DesyncDetection uint8
}

// NewRollbackConfig creates a new RollbackConfig.
func NewRollbackConfig(maxRollbackFrames uint32, inputDelayFrames uint32, desyncDetection uint8) RollbackConfig {
	return RollbackConfig{
		MaxRollbackFrames: maxRollbackFrames,
		InputDelayFrames: inputDelayFrames,
		DesyncDetection: desyncDetection,
	}
}
