// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
package com.goudengine.input

/** Gamepad button identifiers matching the FFI GAMEPAD_BUTTON_* constants. */
enum class GamepadButton(val value: Int) {
    South(0),
    East(1),
    West(2),
    North(3),
    LeftBumper(4),
    RightBumper(5),
    Back(6),
    Start(7),
    Guide(8),
    LeftStick(9),
    RightStick(10),
    DpadUp(11),
    DpadRight(12),
    DpadDown(13),
    DpadLeft(14);

    companion object {
        fun fromValue(value: Int): GamepadButton? =
            entries.firstOrNull { it.value == value }
    }
}
