"""Error and network wrapper generation."""

from sdk_common import HEADER_COMMENT, write_generated, load_errors
from .context import NS, OUT, CS_ROOT, schema

def gen_errors():
    categories, codes = load_errors(schema)
    if not categories:
        return

    lines = [
        f"// {HEADER_COMMENT}",
        "",
        "using System;",
        "using System.Runtime.InteropServices;",
        "using System.Text;",
        "",
        f"namespace {NS}",
        "{",
        "    /// <summary>",
        "    /// Recovery classification for engine errors.",
        "    /// Matches the Rust RecoveryClass enum values returned by",
        "    /// goud_error_recovery_class.",
        "    /// </summary>",
        "    public enum RecoveryClass",
        "    {",
        "        Recoverable = 0,",
        "        Fatal = 1,",
        "        Degraded = 2,",
        "    }",
        "",
        "    /// <summary>",
        "    /// Base exception for all GoudEngine errors. Carries the numeric error",
        "    /// code, human-readable category, subsystem/operation context, and",
        "    /// recovery information retrieved from the Rust FFI layer.",
        "    /// </summary>",
        "    public class GoudException : Exception",
        "    {",
        "        public int ErrorCode { get; }",
        "        public string Category { get; }",
        "        public string Subsystem { get; }",
        "        public string Operation { get; }",
        "        public RecoveryClass Recovery { get; }",
        "        public string RecoveryHint { get; }",
        "",
        "        public GoudException(",
        "            int errorCode,",
        "            string message,",
        "            string category,",
        "            string subsystem,",
        "            string operation,",
        "            RecoveryClass recovery,",
        "            string recoveryHint",
        "        ) : base(message)",
        "        {",
        "            ErrorCode = errorCode;",
        "            Category = category;",
        "            Subsystem = subsystem;",
        "            Operation = operation;",
        "            Recovery = recovery;",
        "            RecoveryHint = recoveryHint;",
        "        }",
        "",
        "        /// <summary>",
        "        /// Queries all FFI error functions and constructs the appropriate",
        "        /// typed exception subclass based on the error code range.",
        "        /// Returns null if no error is set (code == 0).",
        "        /// </summary>",
        "        public static GoudException? FromLastError()",
        "        {",
        "            int code = NativeMethods.goud_last_error_code();",
        "            if (code == 0)",
        "                return null;",
        "",
        "            string message = ReadStringFromFfi(NativeMethods.goud_last_error_message);",
        "            string subsystem = ReadStringFromFfi(NativeMethods.goud_last_error_subsystem);",
        "            string operation = ReadStringFromFfi(NativeMethods.goud_last_error_operation);",
        "",
        "            int recoveryRaw = NativeMethods.goud_error_recovery_class(code);",
        "            var recovery = recoveryRaw switch",
        "            {",
        "                1 => RecoveryClass.Fatal,",
        "                2 => RecoveryClass.Degraded,",
        "                _ => RecoveryClass.Recoverable,",
        "            };",
        "",
        "            string hint = ReadHintFromFfi(code);",
        "            string category = CategoryFromCode(code);",
        "",
        "            return CreateTyped(",
        "                code, message, category, subsystem, operation, recovery, hint",
        "            );",
        "        }",
        "",
        "        private static string CategoryFromCode(int code)",
        "        {",
        "            return code switch",
        "            {",
    ]

    # Build the switch arms from categories, sorted by range_start descending
    sorted_cats = sorted(categories, key=lambda c: c["range_start"], reverse=True)
    for cat in sorted_cats:
        lines.append(f'                >= {cat["range_start"]} => "{cat["name"]}",')
    lines += [
        '                _ => "Unknown",',
        "            };",
        "        }",
        "",
        "        private static GoudException CreateTyped(",
        "            int code,",
        "            string message,",
        "            string category,",
        "            string subsystem,",
        "            string operation,",
        "            RecoveryClass recovery,",
        "            string hint",
        "        )",
        "        {",
        "            return category switch",
        "            {",
    ]

    for cat in categories:
        cls_name = cat["base_class"].replace("Error", "Exception")
        lines.append(
            f'                "{cat["name"]}" => new {cls_name}('
        )
        lines.append(
            "                    code, message, subsystem, operation, recovery, hint),"
        )

    lines += [
        "                _ => new GoudException(",
        "                    code, message, category, subsystem, operation, recovery, hint),",
        "            };",
        "        }",
        "",
        "        // Delegate type matching goud_last_error_message / subsystem / operation",
        "        private delegate int BufferFfiCall(IntPtr buf, nuint bufLen);",
        "",
        "        private static string ReadStringFromFfi(BufferFfiCall ffiCall)",
        "        {",
        "            var buf = new byte[256];",
        "            unsafe",
        "            {",
        "                fixed (byte* ptr = buf)",
        "                {",
        "                    int written = ffiCall((IntPtr)ptr, (nuint)buf.Length);",
        "                    if (written <= 0)",
        "                        return string.Empty;",
        "                    return Encoding.UTF8.GetString(buf, 0, written);",
        "                }",
        "            }",
        "        }",
        "",
        "        // Delegate for goud_error_recovery_hint (takes code + buffer)",
        "        private static string ReadHintFromFfi(int code)",
        "        {",
        "            var buf = new byte[256];",
        "            unsafe",
        "            {",
        "                fixed (byte* ptr = buf)",
        "                {",
        "                    int written = NativeMethods.goud_error_recovery_hint(",
        "                        code, (IntPtr)ptr, (nuint)buf.Length);",
        "                    if (written <= 0)",
        "                        return string.Empty;",
        "                    return Encoding.UTF8.GetString(buf, 0, written);",
        "                }",
        "            }",
        "        }",
        "    }",
        "",
    ]

    # Generate category subclasses
    for cat in categories:
        cls_name = cat["base_class"].replace("Error", "Exception")
        lines += [
            f'    public class {cls_name} : GoudException',
            "    {",
            f"        public {cls_name}(",
            "            int code, string message, string subsystem,",
            "            string operation, RecoveryClass recovery, string hint",
            f'        ) : base(code, message, "{cat["name"]}", subsystem, operation, recovery, hint) {{ }}',
            "    }",
            "",
        ]

    lines.append("}")
    lines.append("")

    write_generated(OUT / "Core" / "Errors.g.cs", "\n".join(lines))


def gen_network_wrappers():
    manager_lines = [
        f"// {HEADER_COMMENT}",
        "",
        "using System;",
        "",
        f"namespace {NS}",
        "{",
        "    /// <summary>",
        "    /// Thin auto-generated convenience wrapper for network lifecycle operations.",
        "    /// </summary>",
        "    public sealed class NetworkManager",
        "    {",
        "        private readonly GoudContext? _context;",
        "        private readonly GoudGame? _game;",
        "",
        "        public NetworkManager(GoudGame game)",
        "        {",
        "            _game = game ?? throw new ArgumentNullException(nameof(game));",
        "        }",
        "",
        "        public NetworkManager(GoudContext context)",
        "        {",
        "            _context = context ?? throw new ArgumentNullException(nameof(context));",
        "        }",
        "",
        "        /// <summary>Hosts a network endpoint. Host endpoints do not have a default peer ID.</summary>",
        "        public NetworkEndpoint Host(NetworkProtocol protocol, ushort port)",
        "        {",
        "            var handle = RunHost((int)protocol, port);",
        "            if (handle < 0)",
        "            {",
        "                throw new InvalidOperationException($\"NetworkHost failed with handle {handle}.\");",
        "            }",
        "",
        "            return new NetworkEndpoint(_game, _context, handle, defaultPeerId: null);",
        "        }",
        "",
        "        /// <summary>",
        "        /// Connects to a remote endpoint and preserves the provider-assigned default peer ID.",
        "        /// </summary>",
        "        public NetworkEndpoint Connect(NetworkProtocol protocol, string address, ushort port)",
        "        {",
        "            var result = RunConnectWithPeer((int)protocol, address, port);",
        "            return new NetworkEndpoint(_game, _context, result.Handle, result.PeerId);",
        "        }",
        "",
        "        private long RunHost(int protocol, ushort port)",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkHost(protocol, port);",
        "            }",
        "",
        "            return _context!.NetworkHost(protocol, port);",
        "        }",
        "",
        "        private NetworkConnectResult RunConnectWithPeer(int protocol, string address, ushort port)",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkConnectWithPeer(protocol, address, port);",
        "            }",
        "",
        "            return _context!.NetworkConnectWithPeer(protocol, address, port);",
        "        }",
        "    }",
        "}",
        "",
    ]

    endpoint_lines = [
        f"// {HEADER_COMMENT}",
        "",
        "using System;",
        "",
        f"namespace {NS}",
        "{",
        "    /// <summary>Auto-generated convenience wrapper for a concrete network handle.</summary>",
        "    public sealed class NetworkEndpoint",
        "    {",
        "        private readonly GoudContext? _context;",
        "        private readonly GoudGame? _game;",
        "",
        "        internal NetworkEndpoint(GoudGame? game, GoudContext? context, long handle, ulong? defaultPeerId)",
        "        {",
        "            _game = game;",
        "            _context = context;",
        "            Handle = handle;",
        "            DefaultPeerId = defaultPeerId;",
        "        }",
        "",
        "        /// <summary>Underlying native network handle.</summary>",
        "        public long Handle { get; }",
        "",
        "        /// <summary>Default peer ID used by Send(byte[], byte).",
        "        /// </summary>",
        "        public ulong? DefaultPeerId { get; }",
        "",
        "        /// <summary>Sends bytes to the endpoint's default peer on the given channel.</summary>",
        "        public int Send(byte[] data, byte channel = 0)",
        "        {",
        "            if (!DefaultPeerId.HasValue)",
        "            {",
        "                throw new InvalidOperationException(\"No default peer ID is available for this endpoint. Use SendTo(...) or connect via NetworkManager.Connect(...).\");",
        "            }",
        "",
        "            return SendTo(DefaultPeerId.Value, data, channel);",
        "        }",
        "",
        "        /// <summary>Sends bytes to a specific peer on the given channel.</summary>",
        "        public int SendTo(ulong peerId, byte[] data, byte channel = 0)",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkSend(Handle, peerId, data, channel);",
        "            }",
        "",
        "            return _context!.NetworkSend(Handle, peerId, data, channel);",
        "        }",
        "",
        "        /// <summary>Polls the provider and buffers pending events/messages for this handle.</summary>",
        "        public int Poll()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkPoll(Handle);",
        "            }",
        "",
        "            return _context!.NetworkPoll(Handle);",
        "        }",
        "",
        "        /// <summary>Receives the next buffered packet or null when no packet is available.</summary>",
        "        public NetworkPacket? Receive()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkReceivePacket(Handle);",
        "            }",
        "",
        "            return _context!.NetworkReceivePacket(Handle);",
        "        }",
        "",
        "        /// <summary>Disconnects this endpoint handle.</summary>",
        "        public int Disconnect()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkDisconnect(Handle);",
        "            }",
        "",
        "            return _context!.NetworkDisconnect(Handle);",
        "        }",
        "",
        "        /// <summary>Returns aggregate stats for this endpoint handle.</summary>",
        "        public NetworkStats GetStats()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.GetNetworkStats(Handle);",
        "            }",
        "",
        "            return _context!.GetNetworkStats(Handle);",
        "        }",
        "",
        "        /// <summary>Returns the number of peers associated with this endpoint handle.</summary>",
        "        public int PeerCount()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.NetworkPeerCount(Handle);",
        "            }",
        "",
        "            return _context!.NetworkPeerCount(Handle);",
        "        }",
        "",
        "        /// <summary>Applies debug network simulation config to this endpoint handle.</summary>",
        "        public int SetSimulation(NetworkSimulationConfig config)",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.SetNetworkSimulation(Handle, config);",
        "            }",
        "",
        "            return _context!.SetNetworkSimulation(Handle, config);",
        "        }",
        "",
        "        /// <summary>Clears debug network simulation config from this endpoint handle.</summary>",
        "        public int ClearSimulation()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.ClearNetworkSimulation(Handle);",
        "            }",
        "",
        "            return _context!.ClearNetworkSimulation(Handle);",
        "        }",
        "",
        "        /// <summary>Routes native network overlay stats to this endpoint handle.</summary>",
        "        public int SetOverlayTarget()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.SetNetworkOverlayHandle(Handle);",
        "            }",
        "",
        "            return _context!.SetNetworkOverlayHandle(Handle);",
        "        }",
        "",
        "        /// <summary>Clears the native network overlay target override for this context.</summary>",
        "        public int ClearOverlayTarget()",
        "        {",
        "            if (_game != null)",
        "            {",
        "                return _game.ClearNetworkOverlayHandle();",
        "            }",
        "",
        "            return _context!.ClearNetworkOverlayHandle();",
        "        }",
        "    }",
        "}",
        "",
    ]

    write_generated(CS_ROOT / "NetworkManager.cs", "\n".join(manager_lines))
    write_generated(CS_ROOT / "NetworkEndpoint.cs", "\n".join(endpoint_lines))


