// swift-tools-version: 5.9
// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.

import PackageDescription

let package = Package(
    name: "GoudEngine",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "GoudEngine", targets: ["GoudEngine"]),
    ],
    targets: [
        .systemLibrary(
            name: "CGoudEngine",
            path: "Sources/CGoudEngine"
        ),
        .target(
            name: "GoudEngine",
            dependencies: ["CGoudEngine"],
            path: "Sources/GoudEngine"
        ),
        .testTarget(
            name: "GoudEngineTests",
            dependencies: ["GoudEngine"],
            path: "Tests/GoudEngineTests"
        ),
    ]
)
