/**
 * Web backend for GoudEngine SDK.
 *
 * Loads the Wasm module produced by `wasm-pack`, creates a canvas,
 * wires browser input events into the engine, and drives the game
 * loop via `requestAnimationFrame`.
 *
 * Usage:
 * ```ts
 * import { createWebGame } from '@goudengine/sdk/web';
 *
 * const game = await createWebGame({
 *   title: 'My Game',
 *   width: 800,
 *   height: 600,
 *   canvas: document.getElementById('canvas') as HTMLCanvasElement,
 * });
 *
 * const player = game.spawnEmpty();
 * game.addTransform2d(player, { positionX: 100, positionY: 200, rotation: 0, scaleX: 1, scaleY: 1 });
 *
 * game.run((ctx) => {
 *   // per-frame update
 * });
 * ```
 */

import type {
  IGameConfig,
  IEntity,
  IGoudGame,
  ITransform2DData,
} from '../types/engine';
import { Key, MouseButton } from '../types/input';
import { attachInputHandlers, codeToKeyCode } from './input';
import { WebAudioManager } from './audio';

// Re-export utilities
export { WebAudioManager } from './audio';
export { codeToKeyCode } from './input';

// ---------------------------------------------------------------------------
// Wasm module typing (generated by wasm-bindgen)
// ---------------------------------------------------------------------------

/** Minimal shape of the wasm-bindgen module default export. */
interface WasmExports {
  WasmGame: {
    new (width: number, height: number, title: string): WasmGameHandle;
  };
}

/** Opaque handle to the Rust `WasmGame` instance. */
interface WasmGameHandle {
  free(): void;
  begin_frame(dt: number): void;
  end_frame(): void;
  readonly delta_time: number;
  readonly total_time: number;
  readonly fps: number;
  readonly frame_count: bigint;
  readonly title: string;
  readonly window_width: number;
  readonly window_height: number;
  set_canvas_size(w: number, h: number): void;
  spawn_empty(): bigint;
  spawn_batch(count: number): BigUint64Array;
  despawn(bits: bigint): boolean;
  entity_count(): number;
  is_alive(bits: bigint): boolean;
  add_transform2d(bits: bigint, px: number, py: number, r: number, sx: number, sy: number): void;
  get_transform2d(bits: bigint): { position_x: number; position_y: number; rotation: number; scale_x: number; scale_y: number } | undefined;
  set_transform2d(bits: bigint, px: number, py: number, r: number, sx: number, sy: number): void;
  has_transform2d(bits: bigint): boolean;
  remove_transform2d(bits: bigint): boolean;
  add_name(bits: bigint, name: string): void;
  get_name(bits: bigint): string | undefined;
  has_name(bits: bigint): boolean;
  remove_name(bits: bigint): boolean;
  press_key(kc: number): void;
  release_key(kc: number): void;
  press_mouse_button(btn: number): void;
  release_mouse_button(btn: number): void;
  set_mouse_position(x: number, y: number): void;
  add_scroll_delta(dx: number, dy: number): void;
  is_key_pressed(kc: number): boolean;
  is_key_just_pressed(kc: number): boolean;
  is_key_just_released(kc: number): boolean;
  is_mouse_button_pressed(btn: number): boolean;
  is_mouse_button_just_pressed(btn: number): boolean;
  mouse_x(): number;
  mouse_y(): number;
  scroll_dx(): number;
  scroll_dy(): number;
}

// ---------------------------------------------------------------------------
// Wasm loader
// ---------------------------------------------------------------------------

let _wasmModule: WasmExports | null = null;

/**
 * Loads the wasm module from the given URL. Defaults to a path relative to
 * the importing script (typical wasm-pack output layout).
 */
export async function initWasm(wasmUrl?: string): Promise<void> {
  if (_wasmModule) return;

  const url = wasmUrl ?? new URL('goud_engine_bg.wasm', import.meta.url).href;

  const initFn: (input?: string | URL | Request | Response) => Promise<WasmExports> =
    // Dynamic import so bundlers can code-split the wasm glue.
    (await import(/* webpackIgnore: true */ url.replace(/_bg\.wasm$/, '.js'))).default;

  _wasmModule = await initFn(url);
}

function getWasm(): WasmExports {
  if (!_wasmModule) {
    throw new Error(
      'Wasm module not loaded. Call `await initWasm()` before creating a game.',
    );
  }
  return _wasmModule;
}

// ---------------------------------------------------------------------------
// Entity wrapper
// ---------------------------------------------------------------------------

class WebEntity implements IEntity {
  private _bits: bigint;

  constructor(bits: bigint) {
    this._bits = bits;
  }

  get index(): number {
    return Number(this._bits & 0xFFFFFFFFn);
  }

  get generation(): number {
    return Number(this._bits >> 32n);
  }

  get isPlaceholder(): boolean {
    return this._bits === 0xFFFFFFFFFFFFFFFFn;
  }

  toBits(): bigint {
    return this._bits;
  }

  toString(): string {
    return `Entity(${this.index}v${this.generation})`;
  }
}

// ---------------------------------------------------------------------------
// Web game config (extends base config with canvas)
// ---------------------------------------------------------------------------

export interface WebGameConfig extends IGameConfig {
  /** Existing canvas to render into. If omitted, one is created and
   *  appended to `document.body`. */
  canvas?: HTMLCanvasElement;
  /** URL to the wasm file. Omit to use the default wasm-pack path. */
  wasmUrl?: string;
}

// ---------------------------------------------------------------------------
// Frame callback context
// ---------------------------------------------------------------------------

export interface FrameContext {
  readonly deltaTime: number;
  readonly totalTime: number;
  readonly fps: number;
  readonly frameCount: number;
}

// ---------------------------------------------------------------------------
// GoudGame — web implementation
// ---------------------------------------------------------------------------

export class GoudGame implements IGoudGame {
  private handle: WasmGameHandle;
  private canvas: HTMLCanvasElement;
  private detachInput: (() => void) | null = null;
  private rafId = 0;
  private running = false;
  private lastTimestamp = 0;

  /** Use `createWebGame()` instead. */
  constructor(handle: WasmGameHandle, canvas: HTMLCanvasElement) {
    this.handle = handle;
    this.canvas = canvas;
  }

  // -- Entity operations ---------------------------------------------------

  spawnEmpty(): IEntity {
    return new WebEntity(this.handle.spawn_empty());
  }

  spawnBatch(count: number): IEntity[] {
    const arr = this.handle.spawn_batch(count);
    const result: IEntity[] = [];
    for (let i = 0; i < arr.length; i++) {
      result.push(new WebEntity(arr[i]));
    }
    return result;
  }

  despawn(entity: IEntity): boolean {
    return this.handle.despawn(entity.toBits());
  }

  entityCount(): number {
    return this.handle.entity_count();
  }

  isAlive(entity: IEntity): boolean {
    return this.handle.is_alive(entity.toBits());
  }

  // -- Transform2D ---------------------------------------------------------

  addTransform2d(entity: IEntity, data: ITransform2DData): void {
    this.handle.add_transform2d(
      entity.toBits(),
      data.positionX, data.positionY,
      data.rotation,
      data.scaleX, data.scaleY,
    );
  }

  getTransform2d(entity: IEntity): ITransform2DData | null {
    const t = this.handle.get_transform2d(entity.toBits());
    if (!t) return null;
    return {
      positionX: t.position_x,
      positionY: t.position_y,
      rotation: t.rotation,
      scaleX: t.scale_x,
      scaleY: t.scale_y,
    };
  }

  setTransform2d(entity: IEntity, data: ITransform2DData): void {
    this.handle.set_transform2d(
      entity.toBits(),
      data.positionX, data.positionY,
      data.rotation,
      data.scaleX, data.scaleY,
    );
  }

  hasTransform2d(entity: IEntity): boolean {
    return this.handle.has_transform2d(entity.toBits());
  }

  removeTransform2d(entity: IEntity): boolean {
    return this.handle.remove_transform2d(entity.toBits());
  }

  // -- Name ----------------------------------------------------------------

  addName(entity: IEntity, name: string): void {
    this.handle.add_name(entity.toBits(), name);
  }

  getName(entity: IEntity): string | null {
    return this.handle.get_name(entity.toBits()) ?? null;
  }

  hasName(entity: IEntity): boolean {
    return this.handle.has_name(entity.toBits());
  }

  removeName(entity: IEntity): boolean {
    return this.handle.remove_name(entity.toBits());
  }

  // -- Frame update (manual) -----------------------------------------------

  updateFrame(deltaTime: number): void {
    this.handle.begin_frame(deltaTime);
    this.handle.end_frame();
  }

  // -- Timing getters ------------------------------------------------------

  get deltaTime(): number { return this.handle.delta_time; }
  get totalTime(): number { return this.handle.total_time; }
  get fps(): number { return this.handle.fps; }
  get frameCount(): number { return Number(this.handle.frame_count); }
  get title(): string { return this.handle.title; }
  get windowWidth(): number { return this.handle.window_width; }
  get windowHeight(): number { return this.handle.window_height; }

  // -- Input queries -------------------------------------------------------

  isKeyPressed(key: Key): boolean {
    return this.handle.is_key_pressed(key);
  }

  isKeyJustPressed(key: Key): boolean {
    return this.handle.is_key_just_pressed(key);
  }

  isKeyJustReleased(key: Key): boolean {
    return this.handle.is_key_just_released(key);
  }

  isMouseButtonPressed(button: MouseButton): boolean {
    return this.handle.is_mouse_button_pressed(button);
  }

  getMousePosition(): { x: number; y: number } {
    return { x: this.handle.mouse_x(), y: this.handle.mouse_y() };
  }

  getScrollDelta(): { x: number; y: number } {
    return { x: this.handle.scroll_dx(), y: this.handle.scroll_dy() };
  }

  // -- Game loop -----------------------------------------------------------

  /**
   * Starts the `requestAnimationFrame` loop. The callback is invoked once
   * per frame with timing information.
   *
   * ```ts
   * game.run((ctx) => {
   *   if (game.isKeyPressed(Key.Space)) { ... }
   * });
   * ```
   */
  run(update: (ctx: FrameContext) => void): void {
    if (this.running) return;
    this.running = true;
    this.lastTimestamp = performance.now();

    this.detachInput = attachInputHandlers(this.canvas, this.handle);

    const loop = (timestamp: number) => {
      if (!this.running) return;

      const dtMs = timestamp - this.lastTimestamp;
      this.lastTimestamp = timestamp;
      const dt = dtMs / 1000;

      this.handle.begin_frame(dt);

      update({
        deltaTime: this.handle.delta_time,
        totalTime: this.handle.total_time,
        fps: this.handle.fps,
        frameCount: Number(this.handle.frame_count),
      });

      this.handle.end_frame();
      this.rafId = requestAnimationFrame(loop);
    };

    this.rafId = requestAnimationFrame(loop);
  }

  /** Stops the game loop and removes event listeners. */
  stop(): void {
    this.running = false;
    if (this.rafId) {
      cancelAnimationFrame(this.rafId);
      this.rafId = 0;
    }
    if (this.detachInput) {
      this.detachInput();
      this.detachInput = null;
    }
  }

  /** Releases all resources (wasm memory, canvas, listeners). */
  destroy(): void {
    this.stop();
    this.handle.free();
  }
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Creates and initialises a web-based GoudGame instance.
 *
 * This is the primary entry point for the web backend. It:
 * 1. Loads the wasm module (if not already loaded)
 * 2. Creates or reuses a canvas element
 * 3. Instantiates the Rust `WasmGame`
 * 4. Returns a fully wired `GoudGame`
 */
export async function createWebGame(config: WebGameConfig = {}): Promise<GoudGame> {
  await initWasm(config.wasmUrl);

  const wasm = getWasm();
  const width = config.width ?? 800;
  const height = config.height ?? 600;
  const title = config.title ?? 'GoudEngine';

  let canvas = config.canvas ?? null;
  if (!canvas) {
    canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    canvas.style.display = 'block';
    document.body.appendChild(canvas);
  } else {
    canvas.width = width;
    canvas.height = height;
  }

  document.title = title;

  const handle = new wasm.WasmGame(width, height, title);

  const resizeObserver = new ResizeObserver((entries) => {
    for (const entry of entries) {
      const { width: w, height: h } = entry.contentRect;
      handle.set_canvas_size(Math.round(w), Math.round(h));
    }
  });
  resizeObserver.observe(canvas);

  return new GoudGame(handle, canvas);
}
