// This file is AUTO-GENERATED by GoudEngine codegen. DO NOT EDIT.
plugins {
    kotlin("jvm") version "2.0.21"
    `maven-publish`
    signing
    id("org.jetbrains.dokka") version "1.9.20"
}

group = "io.github.aram-devdocs"
version = "0.0.842" // x-release-please-version

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    testImplementation(kotlin("test"))
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
    jvmToolchain(17)
}

tasks.test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java.srcDirs("src/main/java")
        kotlin.srcDirs("src/main/kotlin")
        resources.srcDir("build/native")
    }
    test {
        kotlin.srcDirs("src/test/kotlin")
    }
}

// CI pre-stages native libs into src/main/resources/native/.
// buildNative is only needed for local development.
val preStaged = file("src/main/resources/native").let { it.exists() && it.listFiles()?.isNotEmpty() == true }

val buildNative by tasks.registering(Exec::class) {
    group = "build"
    description = "Build the native Rust library (skipped when pre-staged)"
    enabled = !preStaged
    workingDir = rootDir.resolve("../../")
    commandLine("cargo", "build", "--release", "-p", "goud-engine-core")
    doLast {
        val nativeDir = layout.buildDirectory.dir("native").get().asFile
        nativeDir.mkdirs()
        val osName = System.getProperty("os.name").lowercase()
        val libName = when {
            "mac" in osName || "darwin" in osName -> "libgoud_engine.dylib"
            "win" in osName -> "goud_engine.dll"
            else -> "libgoud_engine.so"
        }
        val src = rootDir.resolve("../../target/release/$libName")
        if (src.exists()) {
            src.copyTo(nativeDir.resolve(libName), overwrite = true)
        }
    }
}

tasks.named("processResources") {
    if (!preStaged) dependsOn(buildNative)
}

tasks.jar {
    from("build/native") {
        into("native/")
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.named<Jar>("sourcesJar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        create<MavenPublication>("mavenKotlin") {
            groupId = "io.github.aram-devdocs"
            artifactId = "goudengine"
            from(components["java"])
            pom {
                name.set("GoudEngine Kotlin SDK")
                description.set("Kotlin bindings for the GoudEngine game engine")
                url.set("https://github.com/aram-devdocs/GoudEngine")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/aram-devdocs/GoudEngine.git")
                    developerConnection.set("scm:git:ssh://github.com/aram-devdocs/GoudEngine.git")
                    url.set("https://github.com/aram-devdocs/GoudEngine")
                }
                developers {
                    developer {
                        name.set("GoudEngine Contributors")
                        url.set("https://github.com/aram-devdocs/GoudEngine/graphs/contributors")
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = "LocalStaging"
            url = uri(layout.buildDirectory.dir("staging-deploy"))
        }
    }
}

signing {
    useGpgCmd()
    isRequired = System.getenv("MAVEN_USERNAME") != null
    sign(publishing.publications["mavenKotlin"])
}
