#!/bin/sh
echo "Rsunning pre-commit hook"

echo "Running cargo fmt"
cargo fmt --all -- --check

echo "Running cargo clippy"
cargo clippy --all-targets --all-features -- -D warnings

echo "Running cargo test"
cargo test

echo "Running cargo build"
cargo build

echo "Running cargo check"
cargo check


exit 1