name: Rust Deny Checks

on:
  workflow_run:
    workflows: ["Rust Test"]
    types:
      - completed
    branches: ["main"]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Run cargo deny checks
        run: cargo deny check 